# osirus #######################################################################

[osirus-test-console-x86_64]
src.webpage = "https://dsp56300.wordpress.com/osirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-$ver-Linux_x86_64-OsirusTestConsole.zip"

[osirus-clap-x86_64]
src.webpage = "https://dsp56300.wordpress.com/osirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-$ver-Linux_x86_64-Osirus-CLAP.zip"

[osirus-lv2-x86_64]
src.webpage = "https://dsp56300.wordpress.com/osirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-$ver-Linux_x86_64-Osirus-LV2.zip"

[osirus-vst2-x86_64]
src.webpage = "https://dsp56300.wordpress.com/osirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-$ver-Linux_x86_64-Osirus-VST2.zip"

[osirus-vst3-x86_64]
src.webpage = "https://dsp56300.wordpress.com/osirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-$ver-Linux_x86_64-Osirus-VST3.zip"

[osirusfx-clap-x86_64]
src.webpage = "https://dsp56300.wordpress.com/osirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-$ver-Linux_x86_64-OsirusFX-CLAP.zip"

[osirusfx-lv2-x86_64]
src.webpage = "https://dsp56300.wordpress.com/osirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-$ver-Linux_x86_64-OsirusFX-LV2.zip"

[osirusfx-vst2-x86_64]
src.webpage = "https://dsp56300.wordpress.com/osirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-$ver-Linux_x86_64-OsirusFX-VST2.zip"

[osirusfx-vst3-x86_64]
src.webpage = "https://dsp56300.wordpress.com/osirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-$ver-Linux_x86_64-OsirusFX-VST3.zip"

[osirus-test-console-aarch64]
src.webpage = "https://dsp56300.wordpress.com/osirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-$ver-Linux_aarch64-OsirusTestConsole.zip"

[osirus-clap-aarch64]
src.webpage = "https://dsp56300.wordpress.com/osirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-$ver-Linux_aarch64-Osirus-CLAP.zip"

[osirus-lv2-aarch64]
src.webpage = "https://dsp56300.wordpress.com/osirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-$ver-Linux_aarch64-Osirus-LV2.zip"

[osirus-vst2-aarch64]
src.webpage = "https://dsp56300.wordpress.com/osirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-$ver-Linux_aarch64-Osirus-VST2.zip"

[osirus-vst3-aarch64]
src.webpage = "https://dsp56300.wordpress.com/osirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-$ver-Linux_aarch64-Osirus-VST3.zip"

[osirusfx-clap-aarch64]
src.webpage = "https://dsp56300.wordpress.com/osirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-$ver-Linux_aarch64-OsirusFX-CLAP.zip"

[osirusfx-lv2-aarch64]
src.webpage = "https://dsp56300.wordpress.com/osirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-$ver-Linux_aarch64-OsirusFX-LV2.zip"

[osirusfx-vst2-aarch64]
src.webpage = "https://dsp56300.wordpress.com/osirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-$ver-Linux_aarch64-OsirusFX-VST2.zip"

[osirusfx-vst3-aarch64]
src.webpage = "https://dsp56300.wordpress.com/osirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-$ver-Linux_aarch64-OsirusFX-VST3.zip"

# ostirus ######################################################################

[ostirus-test-console-x86_64]
src.webpage = "https://dsp56300.wordpress.com/ostirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-$ver-Linux_x86_64-OsTIrusTestConsole.zip"

[ostirus-clap-x86_64]
src.webpage = "https://dsp56300.wordpress.com/ostirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-$ver-Linux_x86_64-OsTIrus-CLAP.zip"

[ostirus-lv2-x86_64]
src.webpage = "https://dsp56300.wordpress.com/ostirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-$ver-Linux_x86_64-OsTIrus-LV2.zip"

[ostirus-vst2-x86_64]
src.webpage = "https://dsp56300.wordpress.com/ostirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-$ver-Linux_x86_64-OsTIrus-VST2.zip"

[ostirus-vst3-x86_64]
src.webpage = "https://dsp56300.wordpress.com/ostirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-$ver-Linux_x86_64-OsTIrus-VST3.zip"

[ostirusfx-clap-x86_64]
src.webpage = "https://dsp56300.wordpress.com/ostirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-$ver-Linux_x86_64-OsTIrusFX-CLAP.zip"

[ostirusfx-lv2-x86_64]
src.webpage = "https://dsp56300.wordpress.com/ostirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-$ver-Linux_x86_64-OsTIrusFX-LV2.zip"

[ostirusfx-vst2-x86_64]
src.webpage = "https://dsp56300.wordpress.com/ostirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-$ver-Linux_x86_64-OsTIrusFX-VST2.zip"

[ostirusfx-vst3-x86_64]
src.webpage = "https://dsp56300.wordpress.com/ostirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-$ver-Linux_x86_64-OsTIrusFX-VST3.zip"

[ostirus-test-console-aarch64]
src.webpage = "https://dsp56300.wordpress.com/ostirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-$ver-Linux_aarch64-OsTIrusTestConsole.zip"

[ostirus-clap-aarch64]
src.webpage = "https://dsp56300.wordpress.com/ostirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-$ver-Linux_aarch64-OsTIrus-CLAP.zip"

[ostirus-lv2-aarch64]
src.webpage = "https://dsp56300.wordpress.com/ostirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-$ver-Linux_aarch64-OsTIrus-LV2.zip"

[ostirus-vst2-aarch64]
src.webpage = "https://dsp56300.wordpress.com/ostirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-$ver-Linux_aarch64-OsTIrus-VST2.zip"

[ostirus-vst3-aarch64]
src.webpage = "https://dsp56300.wordpress.com/ostirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-$ver-Linux_aarch64-OsTIrus-VST3.zip"

[ostirusfx-clap-aarch64]
src.webpage = "https://dsp56300.wordpress.com/ostirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-$ver-Linux_aarch64-OsTIrusFX-CLAP.zip"

[ostirusfx-lv2-aarch64]
src.webpage = "https://dsp56300.wordpress.com/ostirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-$ver-Linux_aarch64-OsTIrusFX-LV2.zip"

[ostirusfx-vst2-aarch64]
src.webpage = "https://dsp56300.wordpress.com/ostirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-$ver-Linux_aarch64-OsTIrusFX-VST2.zip"

[ostirusfx-vst3-aarch64]
src.webpage = "https://dsp56300.wordpress.com/ostirus/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-$ver-Linux_aarch64-OsTIrusFX-VST3.zip"

# vavra ########################################################################

[vavra-performance-test-x86_64]
src.webpage = "https://dsp56300.wordpress.com/vavra/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-$ver-Linux_x86_64-VavraPerformanceTest.zip"

[vavra-clap-x86_64]
src.webpage = "https://dsp56300.wordpress.com/vavra/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-$ver-Linux_x86_64-Vavra-CLAP.zip"

[vavra-lv2-x86_64]
src.webpage = "https://dsp56300.wordpress.com/vavra/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-$ver-Linux_x86_64-Vavra-LV2.zip"

[vavra-vst2-x86_64]
src.webpage = "https://dsp56300.wordpress.com/vavra/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-$ver-Linux_x86_64-Vavra-VST2.zip"

[vavra-vst3-x86_64]
src.webpage = "https://dsp56300.wordpress.com/vavra/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-$ver-Linux_x86_64-Vavra-VST3.zip"

[vavrafx-clap-x86_64]
src.webpage = "https://dsp56300.wordpress.com/vavra/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-$ver-Linux_x86_64-VavraFX-CLAP.zip"

[vavrafx-lv2-x86_64]
src.webpage = "https://dsp56300.wordpress.com/vavra/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-$ver-Linux_x86_64-VavraFX-LV2.zip"

[vavrafx-vst2-x86_64]
src.webpage = "https://dsp56300.wordpress.com/vavra/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-$ver-Linux_x86_64-VavraFX-VST2.zip"

[vavrafx-vst3-x86_64]
src.webpage = "https://dsp56300.wordpress.com/vavra/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-$ver-Linux_x86_64-VavraFX-VST3.zip"

[vavra-performance-test-aarch64]
src.webpage = "https://dsp56300.wordpress.com/vavra/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-$ver-Linux_aarch64-VavraPerformanceTest.zip"

[vavra-clap-aarch64]
src.webpage = "https://dsp56300.wordpress.com/vavra/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-$ver-Linux_aarch64-Vavra-CLAP.zip"

[vavra-lv2-aarch64]
src.webpage = "https://dsp56300.wordpress.com/vavra/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-$ver-Linux_aarch64-Vavra-LV2.zip"

[vavra-vst2-aarch64]
src.webpage = "https://dsp56300.wordpress.com/vavra/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-$ver-Linux_aarch64-Vavra-VST2.zip"

[vavra-vst3-aarch64]
src.webpage = "https://dsp56300.wordpress.com/vavra/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-$ver-Linux_aarch64-Vavra-VST3.zip"

[vavrafx-clap-aarch64]
src.webpage = "https://dsp56300.wordpress.com/vavra/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-$ver-Linux_aarch64-VavraFX-CLAP.zip"

[vavrafx-lv2-aarch64]
src.webpage = "https://dsp56300.wordpress.com/vavra/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-$ver-Linux_aarch64-VavraFX-LV2.zip"

[vavrafx-vst2-aarch64]
src.webpage = "https://dsp56300.wordpress.com/vavra/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-$ver-Linux_aarch64-VavraFX-VST2.zip"

[vavrafx-vst3-aarch64]
src.webpage = "https://dsp56300.wordpress.com/vavra/"
src.regex = 'DSP56300Emu-(\d+\.\d+\.\d+)-Linux'
fetch.url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-$ver-Linux_aarch64-VavraFX-VST3.zip"
