# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  niri-gtk = {
    pname = "niri-gtk";
    version = "1948789ac0a1dc3ab133e7be0a8e75ccf73d64ad";
    src = fetchFromGitHub {
      owner = "sameoldlab";
      repo = "niri-gtk";
      rev = "1948789ac0a1dc3ab133e7be0a8e75ccf73d64ad";
      fetchSubmodules = false;
      sha256 = "sha256-Hiurzs/qs72jyIVfKs/QIk8KtKsXFkMg8Zz3cPtYazI=";
    };
    date = "2026-06-19";
  };
}
