# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  niri-gtk = {
    pname = "niri-gtk";
    version = "249eb454468bab9720a11208ac2caac4c4a0f6a1";
    src = fetchFromGitHub {
      owner = "sameoldlab";
      repo = "niri-gtk";
      rev = "249eb454468bab9720a11208ac2caac4c4a0f6a1";
      fetchSubmodules = false;
      sha256 = "sha256-/1Mz5Thei7MispevH8wz2+YFkG8FSK7Vu/pf8PlbfNo=";
    };
    date = "2026-08-22";
  };
}
