# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  niri-gtk = {
    pname = "niri-gtk";
    version = "19c620a287e706bb5f1158030443a651eaf2d6b3";
    src = fetchFromGitHub {
      owner = "sameoldlab";
      repo = "niri-gtk";
      rev = "19c620a287e706bb5f1158030443a651eaf2d6b3";
      fetchSubmodules = false;
      sha256 = "sha256-3ZqrmyeQyeOGYFtRD1CxBBma03p8Nj/L+SQB98/qdtk=";
    };
    date = "2026-08-18";
  };
}
