# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  bassline-101 = {
    pname = "bassline-101";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-BassLine-101_64_linux.zip";
      sha256 = "sha256-KlnO7bFBcSEWRuELjt7usXxC/kOWjZgyK937cBay+kM=";
    };
  };
  chorus-lx = {
    pname = "chorus-lx";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Chorus-LX_64_linux.zip";
      sha256 = "sha256-F2OWyDo/Q9PsCuCxSDwu97lICVJpnMmZ85OZP7p4ag4=";
    };
  };
  dac = {
    pname = "dac";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-DAC_64_linux.zip";
      sha256 = "sha256-/7JDVxEfOQRqiCGPkejmPkbtnk3HqS/QgTskKz7Zfpc=";
    };
  };
  drum = {
    pname = "drum";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Drum_64_linux.zip";
      sha256 = "sha256-YLLjtahnLgyUBTOp495rzOgNvwl6omokSznG+/FaepA=";
    };
  };
  dub-x = {
    pname = "dub-x";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Dub-X_64_linux.zip";
      sha256 = "sha256-eJzombffcyQH87UDb4/YXYIDhOpEyAW6yypLaKzohvA=";
    };
  };
  eq = {
    pname = "eq";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-EQ_64_linux.zip";
      sha256 = "sha256-HoSBVPvg48PQXwiVBAX00eqLU7+WKulNpHcHc3HcAIM=";
    };
  };
  filter-2 = {
    pname = "filter-2";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Filter-2_64_linux.zip";
      sha256 = "sha256-ymwvK21o3+FgqKcjVJ5R0qdFBbPPjEYlgL9QAfOEe+k=";
    };
  };
  g-verb = {
    pname = "g-verb";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-G-Verb_64_linux.zip";
      sha256 = "sha256-wfvfYR1jlLB2uBnu9rYLaK5wMf1OpJ3Ag8CqxpXDKsw=";
    };
  };
  j-8 = {
    pname = "j-8";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-J-8_64_linux.zip";
      sha256 = "sha256-6NMv+jV3xcDOd+s7GoglmnlQaz4JBvpNfisPoliFk18=";
    };
  };
  mod = {
    pname = "mod";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Mod_64_linux.zip";
      sha256 = "sha256-sq0A0Hme8v759Q/4GTMt/dQ5z5fIiYuKYjRz54aRDic=";
    };
  };
  noisemaker = {
    pname = "noisemaker";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-NoiseMaker_64_linux.zip";
      sha256 = "sha256-MoVl5kb5jxTdkxoz+kOKTJ7dxFHnWbktEAX0M2+j/SA=";
    };
  };
  pha = {
    pname = "pha";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Pha_64_linux.zip";
      sha256 = "sha256-Sx4XBIBDiBCL5KeVZc9kYA3rP+AMVu1LYSkolgF66ow=";
    };
  };
  reverb-4 = {
    pname = "reverb-4";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Reverb-4_64_linux.zip";
      sha256 = "sha256-sI2r0JHXUzUBHJqODINud7Ovj8C4iE1LzRYm/LUVW7o=";
    };
  };
  sampler = {
    pname = "sampler";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Sampler_64_linux.zip";
      sha256 = "sha256-VL5Yrh7pAHUPsZjVMpYrvv47AsN8jZ5LNACrbIwHdoo=";
    };
  };
  u-no-lx = {
    pname = "u-no-lx";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-U-NO-LX-V2_64_linux.zip";
      sha256 = "sha256-Y9RktJGdm8u2w5ZM7u2Zbf3YX6G5fxR3bOQEvKtTMt4=";
    };
  };
  vocoder = {
    pname = "vocoder";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Vocoder-2_64_linux.zip";
      sha256 = "sha256-vOSpQqN8DEK4f5vISeQnZBpxhW3AaW1+/0ImajeoPsY=";
    };
  };
}
