# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  bassline-101 = {
    pname = "bassline-101";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-BassLine-101_64_linux.zip";
      sha256 = "sha256-KlnO7bFBcSEWRuELjt7usXxC/kOWjZgyK937cBay+kM=";
    };
  };
  chorus-lx = {
    pname = "chorus-lx";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Chorus-LX_64_linux.zip";
      sha256 = "sha256-F2OWyDo/Q9PsCuCxSDwu97lICVJpnMmZ85OZP7p4ag4=";
    };
  };
  dac = {
    pname = "dac";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-DAC_64_linux.zip";
      sha256 = "sha256-/7JDVxEfOQRqiCGPkejmPkbtnk3HqS/QgTskKz7Zfpc=";
    };
  };
  drum = {
    pname = "drum";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Drum_64_linux.zip";
      sha256 = "sha256-quMuwrOKi4fWa93gZ3RTufPidIhR9fQagZbYQw5Es3I=";
    };
  };
  dub-x = {
    pname = "dub-x";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Dub-X_64_linux.zip";
      sha256 = "sha256-VqCVgU+T65jK66kAdkDlJcCmIs/D7X48H9jN6hhdvSQ=";
    };
  };
  eq = {
    pname = "eq";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-EQ_64_linux.zip";
      sha256 = "sha256-2M2sNf+RPkzmBu+0o3gYYw4/tgc6sa79oX6bcTWQIIA=";
    };
  };
  filter-2 = {
    pname = "filter-2";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Filter-2_64_linux.zip";
      sha256 = "sha256-ymwvK21o3+FgqKcjVJ5R0qdFBbPPjEYlgL9QAfOEe+k=";
    };
  };
  g-verb = {
    pname = "g-verb";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-G-Verb_64_linux.zip";
      sha256 = "sha256-wfvfYR1jlLB2uBnu9rYLaK5wMf1OpJ3Ag8CqxpXDKsw=";
    };
  };
  j-8 = {
    pname = "j-8";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-J-8_64_linux.zip";
      sha256 = "sha256-DlCEnLG241HpcjLZZHJJh+dQk/tzDudq9vAL6VyFe/8=";
    };
  };
  mod = {
    pname = "mod";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Mod_64_linux.zip";
      sha256 = "sha256-sq0A0Hme8v759Q/4GTMt/dQ5z5fIiYuKYjRz54aRDic=";
    };
  };
  noisemaker = {
    pname = "noisemaker";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-NoiseMaker_64_linux.zip";
      sha256 = "sha256-MoVl5kb5jxTdkxoz+kOKTJ7dxFHnWbktEAX0M2+j/SA=";
    };
  };
  pha = {
    pname = "pha";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Pha_64_linux.zip";
      sha256 = "sha256-wcwG3WLoldwSsi3JgV6n4cjl7cLzvDCyP3kDcBUpWdM=";
    };
  };
  reverb-4 = {
    pname = "reverb-4";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Reverb-4_64_linux.zip";
      sha256 = "sha256-sI2r0JHXUzUBHJqODINud7Ovj8C4iE1LzRYm/LUVW7o=";
    };
  };
  sampler = {
    pname = "sampler";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Sampler_64_linux.zip";
      sha256 = "sha256-KJgv0vXmQ3YskoXPMAl7lU0IJk8bODPXTzM5Qzog1d0=";
    };
  };
  u-no-lx = {
    pname = "u-no-lx";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-U-NO-LX-V2_64_linux.zip";
      sha256 = "sha256-LLGwLS4GVfesVLs25t3u7Jd1AmqaXNerHIrNs5HmXjA=";
    };
  };
  vocoder = {
    pname = "vocoder";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Vocoder-2_64_linux.zip";
      sha256 = "sha256-vOSpQqN8DEK4f5vISeQnZBpxhW3AaW1+/0ImajeoPsY=";
    };
  };
}
