# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  bassline-101 = {
    pname = "bassline-101";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-BassLine-101_64_linux.zip";
      sha256 = "sha256-J2nAoxL3XO1+k3f/sZA/K9sQ75Ivj4Vxumg2jxD1Sro=";
    };
  };
  chorus-lx = {
    pname = "chorus-lx";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/Tal-Chorus-LX_64_linux.zip";
      sha256 = "sha256-M0p8a0nuao5JINNHm6pztGGA/cdaFOgWvXsaP31yAXQ=";
    };
  };
  dac = {
    pname = "dac";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-DAC_64_linux.zip";
      sha256 = "sha256-/7JDVxEfOQRqiCGPkejmPkbtnk3HqS/QgTskKz7Zfpc=";
    };
  };
  drum = {
    pname = "drum";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Drum_64_linux.zip";
      sha256 = "sha256-dfqRGrIx48Qs38hHfD/XOqYpj9hxi3yhQ1ZIEhReRho=";
    };
  };
  dub-x = {
    pname = "dub-x";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Dub-X_64_linux.zip";
      sha256 = "sha256-I2awc0tB2Xs529lhs/G6ibqs+i1FNUVFAoRB+wL9gok=";
    };
  };
  filter-2 = {
    pname = "filter-2";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Filter-2_64_linux.zip";
      sha256 = "sha256-ymwvK21o3+FgqKcjVJ5R0qdFBbPPjEYlgL9QAfOEe+k=";
    };
  };
  g-verb = {
    pname = "g-verb";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-G-Verb_64_linux.zip";
      sha256 = "sha256-G/HAtBmQ5/99mfjAjGj1ME+iMSlz1Lc9gMSk4Bd17+A=";
    };
  };
  j-8 = {
    pname = "j-8";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-J-8_64_linux.zip";
      sha256 = "sha256-L6idx2wmBAK6AG2NFt+H/+6yx9M67120mgneI/1nnn4=";
    };
  };
  mod = {
    pname = "mod";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Mod_64_linux.zip";
      sha256 = "sha256-sq0A0Hme8v759Q/4GTMt/dQ5z5fIiYuKYjRz54aRDic=";
    };
  };
  noisemaker = {
    pname = "noisemaker";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-NoiseMaker_64_linux.zip";
      sha256 = "sha256-MoVl5kb5jxTdkxoz+kOKTJ7dxFHnWbktEAX0M2+j/SA=";
    };
  };
  pha = {
    pname = "pha";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Pha_64_linux.zip";
      sha256 = "sha256-TtlS+gFua2lgEHbIEggvXE5CqOqSRs09A7bkYycDtio=";
    };
  };
  reverb-4 = {
    pname = "reverb-4";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Reverb-4_64_linux.zip";
      sha256 = "sha256-sI2r0JHXUzUBHJqODINud7Ovj8C4iE1LzRYm/LUVW7o=";
    };
  };
  sampler = {
    pname = "sampler";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Sampler_64_linux.zip";
      sha256 = "sha256-V0QdpVVKZ9bTAzYLeVZEsV84fxzX1TayMUXM9rRH3Uw=";
    };
  };
  u-no-lx = {
    pname = "u-no-lx";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-U-NO-LX-V2_64_linux.zip";
      sha256 = "sha256-okPSejK2RQTy1s4cmxoM8D7d2ZeoWCITgHS2aT0atKc=";
    };
  };
  vocoder = {
    pname = "vocoder";
    version = "latest";
    src = fetchurl {
      url = "https://tal-software.com/downloads/plugins/TAL-Vocoder-2_64_linux.zip";
      sha256 = "sha256-vOSpQqN8DEK4f5vISeQnZBpxhW3AaW1+/0ImajeoPsY=";
    };
  };
}
