# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  dmenu-flexipatch = {
    pname = "dmenu-flexipatch";
    version = "a686ac9b7277ae0d5cada675f5366d4f2baaa870";
    src = fetchFromGitHub {
      owner = "bakkeby";
      repo = "dmenu-flexipatch";
      rev = "a686ac9b7277ae0d5cada675f5366d4f2baaa870";
      fetchSubmodules = false;
      sha256 = "sha256-bDaxefEqRbXmyHQem9PSPzvXOoELpxMfvn1phiSMGGc=";
    };
    date = "2024-03-20";
  };
  dwm-flexipatch = {
    pname = "dwm-flexipatch";
    version = "36b574eff68239db35df97035118b614cc79d307";
    src = fetchFromGitHub {
      owner = "bakkeby";
      repo = "dwm-flexipatch";
      rev = "36b574eff68239db35df97035118b614cc79d307";
      fetchSubmodules = false;
      sha256 = "sha256-XejZnLwmuNKOgP+oIrztA0ueMlV751yYdfrGWUU/Zio=";
    };
    date = "2024-04-04";
  };
  slock-flexipatch = {
    pname = "slock-flexipatch";
    version = "316de8856f9f25685f6f1c4e94dbf76e4f64c06b";
    src = fetchFromGitHub {
      owner = "bakkeby";
      repo = "slock-flexipatch";
      rev = "316de8856f9f25685f6f1c4e94dbf76e4f64c06b";
      fetchSubmodules = false;
      sha256 = "sha256-jsAfkd2Xtzp4zKwY0bExPhVtcs+OeBdGJA29SPC04jk=";
    };
    date = "2023-10-06";
  };
  st-flexipatch = {
    pname = "st-flexipatch";
    version = "dd8675943d2e6e1eff15d3ac3aac6e5e5643582b";
    src = fetchFromGitHub {
      owner = "bakkeby";
      repo = "st-flexipatch";
      rev = "dd8675943d2e6e1eff15d3ac3aac6e5e5643582b";
      fetchSubmodules = false;
      sha256 = "sha256-gtT+ShmkD/AEip3JtN5QLQHttgEh11VtaEk8gYhQVDw=";
    };
    date = "2024-04-03";
  };
}
