# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  dmenu-flexipatch = {
    pname = "dmenu-flexipatch";
    version = "45c22eaa042822f60a7eb08c4c40909a78910038";
    src = fetchFromGitHub {
      owner = "bakkeby";
      repo = "dmenu-flexipatch";
      rev = "45c22eaa042822f60a7eb08c4c40909a78910038";
      fetchSubmodules = false;
      sha256 = "sha256-4zXYiEDpzS0haNFvfxcfTyOAhZigGSGAorRoc7vAN3c=";
    };
    date = "2025-05-19";
  };
  dwm-flexipatch = {
    pname = "dwm-flexipatch";
    version = "4b6e4020f9d678e16816c89db0f043d3601d6442";
    src = fetchFromGitHub {
      owner = "bakkeby";
      repo = "dwm-flexipatch";
      rev = "4b6e4020f9d678e16816c89db0f043d3601d6442";
      fetchSubmodules = false;
      sha256 = "sha256-H0c47i4upcBworZbASxDMyQ4IQ2UZvhW7GYJqhEPYS4=";
    };
    date = "2025-05-09";
  };
  slock-flexipatch = {
    pname = "slock-flexipatch";
    version = "72023758232e708018d3c7b0b324e61f55cb5c9b";
    src = fetchFromGitHub {
      owner = "bakkeby";
      repo = "slock-flexipatch";
      rev = "72023758232e708018d3c7b0b324e61f55cb5c9b";
      fetchSubmodules = false;
      sha256 = "sha256-/g0P36A+l7GeRrKFam6bT8o6MgpqjuvjnZC82IwEcdE=";
    };
    date = "2025-03-09";
  };
  st-flexipatch = {
    pname = "st-flexipatch";
    version = "f8e451e26c5fdafa6f60cda1e249fc20e7dd450c";
    src = fetchFromGitHub {
      owner = "bakkeby";
      repo = "st-flexipatch";
      rev = "f8e451e26c5fdafa6f60cda1e249fc20e7dd450c";
      fetchSubmodules = false;
      sha256 = "sha256-Vfr81YbCK9wD5rEixCHK6uhoa52r8dkoF59IpXoLH+k=";
    };
    date = "2025-05-06";
  };
}
