# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  wavetable-bin = {
    pname = "wavetable-bin";
    version = "1.0.25";
    src = fetchurl {
      url = "https://github.com/FigBug/Wavetable/releases/download/1.0.25/Wavetable_Linux.zip";
      sha256 = "sha256-T+hxJfA4FUqQkMa7fpLUJ6d12S/QL8SJD1XuYcUQwX4=";
    };
  };
}
