# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  wavetable-bin = {
    pname = "wavetable-bin";
    version = "1.0.23";
    src = fetchurl {
      url = "https://github.com/FigBug/Wavetable/releases/download/1.0.23/Wavetable_Linux.zip";
      sha256 = "sha256-R6SNzAKqUhagCc6CNUFjXjCvofI2W56WMVpk8Ild8N4=";
    };
  };
}
