# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  wavetable-bin = {
    pname = "wavetable-bin";
    version = "v1.0.33";
    src = fetchurl {
      url = "https://github.com/FigBug/Wavetable/releases/download/v1.0.33/Wavetable.deb";
      sha256 = "sha256-56nH8y3//uvKJ/MITtjtWhIJKNxnMBY6REwuQsfN1jc=";
    };
  };
}
