# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  mod-desktop-bin = {
    pname = "mod-desktop-bin";
    version = "0.0.12";
    src = fetchurl {
      url = "https://github.com/mod-audio/mod-desktop/releases/download/0.0.12/mod-desktop-0.0.12-linux-x86_64.tar.xz";
      sha256 = "sha256-0fryCUZB1e9Sfum2AS8T8SVePCeDdzk5scJEmEjHxQw=";
    };
  };
}
