# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  sable = {
    pname = "sable";
    version = "1.14.0";
    src = dockerTools.pullImage {
      imageName = "ghcr.io/sableclient/sable";
      imageDigest = "sha256:eab1f3efec56b8017a13f3612ac665dc7a0e1547698272a90195e41ba06ca79f";
      sha256 = "sha256-chmNPrT8Cn2YYU8wmMgrljFhKfi1CLsHKAuofaqs67Y=";
      finalImageTag = "1.14.0";
    };
  };
}
