# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  sable = {
    pname = "sable";
    version = "1.12.3";
    src = dockerTools.pullImage {
      imageName = "ghcr.io/sableclient/sable";
      imageDigest = "sha256:2b238433b09e0bc77b96669b4ec099d85a738f30316e0110358ea3d79f16712b";
      sha256 = "sha256-bD9uR6q6j0zKMf05Pl9A06rdiyTfQYJlvYIN7wIU9v4=";
      finalImageTag = "1.12.3";
    };
  };
}
