# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  sable = {
    pname = "sable";
    version = "1.11.1";
    src = dockerTools.pullImage {
      imageName = "ghcr.io/sableclient/sable";
      imageDigest = "sha256:ddbc8a0276be5624da8fc086259f706e855a5524d097d0785b4c008f8feb3233";
      sha256 = "sha256-RYfsuaKkgTSdNpXExZi/n1gvJRPw4QnOwx8+HDtDu8E=";
      finalImageTag = "1.11.1";
    };
  };
}
