# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  slock-flexipatch = {
    pname = "slock-flexipatch";
    version = "f387ce4caf0cbde7707ba55da7cabd79c7e23c29";
    src = fetchFromGitHub {
      owner = "bakkeby";
      repo = "slock-flexipatch";
      rev = "f387ce4caf0cbde7707ba55da7cabd79c7e23c29";
      fetchSubmodules = false;
      sha256 = "sha256-mZLi7MoXnY7hUdIpQdlQV95DbFPVndSXSPXYi203a+w=";
    };
    date = "2026-08-17";
  };
}
