# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  slock-flexipatch = {
    pname = "slock-flexipatch";
    version = "bb763ba9865e36eb3b655051a8b73f4301da299b";
    src = fetchFromGitHub {
      owner = "bakkeby";
      repo = "slock-flexipatch";
      rev = "bb763ba9865e36eb3b655051a8b73f4301da299b";
      fetchSubmodules = false;
      sha256 = "sha256-m+bPl6zak6UBVYOXFO3bSQo/cbcLsZjKztAqdXJ1/k4=";
    };
    date = "2025-11-15";
  };
}
