# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  ripplerx = {
    pname = "ripplerx";
    version = "v1.5.16";
    src = fetchFromGitHub {
      owner = "tiagolr";
      repo = "ripplerx";
      rev = "v1.5.16";
      fetchSubmodules = true;
      sha256 = "sha256-56sa8WR2x8tqISOsKO4EVrm6iZqkoA+ul/nzZslwpXo=";
    };
  };
}
