# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  ripplerx = {
    pname = "ripplerx";
    version = "v1.5.17";
    src = fetchFromGitHub {
      owner = "tiagolr";
      repo = "ripplerx";
      rev = "v1.5.17";
      fetchSubmodules = true;
      sha256 = "sha256-aMptuAAMp4HyjW1JhsXP6upy94VCblMSbxKxp4ETTLA=";
    };
  };
}
