# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cherry-doom = {
    pname = "cherry-doom";
    version = "cherry-doom-2.0.0";
    src = fetchFromGitHub {
      owner = "xemonix0";
      repo = "Cherry-Doom";
      rev = "cherry-doom-2.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-f/5b4i5omCp34upJ2/VF7VuvwU9YliXcWnyR4jl9gKA=";
    };
  };
}
