# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  sheepshaver-bin = {
    pname = "sheepshaver-bin";
    version = "2026-02-11";
    src = fetchurl {
      url = "https://github.com/Korkman/macemu-appimage-builder/releases/download/2026-02-11/SheepShaver-x86_64.AppImage";
      sha256 = "sha256-Oq6DSo6uODHvOY5QDSbOl2hsdEzBK94JB/GIWbiuhBo=";
    };
  };
}
