# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  filtr = {
    pname = "filtr";
    version = "v1.0.8";
    src = fetchFromGitHub {
      owner = "tiagolr";
      repo = "filtr";
      rev = "v1.0.8";
      fetchSubmodules = true;
      sha256 = "sha256-9lTpIoYguWmCUBy7n3ZEal20DmpvsOBNkGIIWEooXzI=";
    };
  };
}
