# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  filtr = {
    pname = "filtr";
    version = "v1.0.7";
    src = fetchFromGitHub {
      owner = "tiagolr";
      repo = "filtr";
      rev = "v1.0.7";
      fetchSubmodules = true;
      sha256 = "sha256-+LmX6tJyjTThjGx2basEURfdXkGdCkyqA1GEOkv5sn8=";
    };
  };
}
