# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  digits-bin = {
    pname = "digits-bin";
    version = "2_1";
    src = fetchTarball {
      url = "http://www.extentofthejam.com/DigitsLinux_2_1.tar.gz";
      sha256 = "sha256-4WFuQi05IiNdUH+RnCfpyhNmt17X0NOrlEIi5lo8WtE=";
    };
  };
}
