[crunchrr]
src.github_tag = "blepfx/dist"
fetch.url = "https://github.com/blepfx/dist/releases/download/$ver/crunchrr-x86_64-unknown-linux-gnu.zip"
pinned = true

[destruqtor]
src.github_tag = "blepfx/dist"
fetch.url = "https://github.com/blepfx/dist/releases/download/$ver/destruqtor-x86_64-unknown-linux-gnu.zip"
pinned = true

[filtrr]
src.github_tag = "blepfx/dist"
fetch.url = "https://github.com/blepfx/dist/releases/download/$ver/filtrr-x86_64-unknown-linux-gnu.zip"
pinned = true

[prisma]
src.github_tag = "blepfx/dist"
fetch.url = "https://github.com/blepfx/dist/releases/download/$ver/prisma-x86_64-unknown-linux-gnu.zip"
pinned = true
