# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  proton-cachyos-bin = {
    pname = "proton-cachyos-bin";
    version = "cachyos-9.0-20250426-slr";
    src = fetchurl {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-9.0-20250426-slr/proton-cachyos-9.0-20250426-slr-x86_64_v3.tar.xz";
      sha256 = "sha256-9M4TmnCLiFIlcYy+wsv5s9Nbler1Qa/Cy9RYzLZ9fQM=";
    };
  };
}
