# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  two-filters = {
    pname = "two-filters";
    version = "c6cae0b7703976de26ef641dbfe4e3ab6dfcac19";
    src = fetchgit {
      url = "https://github.com/baconpaul/two-filters";
      rev = "c6cae0b7703976de26ef641dbfe4e3ab6dfcac19";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-/xs7Z/Ln09ZMVEqyLkLcXuuHaW8DPYkWKggaQ2aibJY=";
    };
    date = "2025-09-29";
  };
  vst3sdk = {
    pname = "vst3sdk";
    version = "v3.7.6_build_18";
    src = fetchFromGitHub {
      owner = "steinbergmedia";
      repo = "vst3sdk";
      rev = "v3.7.6_build_18";
      fetchSubmodules = true;
      sha256 = "sha256-jfh+iP5rqov8q++IyG4FXlYKs4PQtFjCwCP6xou8N0E=";
    };
  };
}
