# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  two-filters = {
    pname = "two-filters";
    version = "1436c910d7d5ea90d003e7f427abcaa327a9cc5e";
    src = fetchgit {
      url = "https://github.com/baconpaul/two-filters";
      rev = "1436c910d7d5ea90d003e7f427abcaa327a9cc5e";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-scPjspMToRK1aZ4q5v3yGTZT9X3LGC2XdkX7ssqEZoM=";
    };
    date = "2025-10-07";
  };
  vst3sdk = {
    pname = "vst3sdk";
    version = "v3.7.6_build_18";
    src = fetchFromGitHub {
      owner = "steinbergmedia";
      repo = "vst3sdk";
      rev = "v3.7.6_build_18";
      fetchSubmodules = true;
      sha256 = "sha256-jfh+iP5rqov8q++IyG4FXlYKs4PQtFjCwCP6xou8N0E=";
    };
  };
}
