# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  two-filters = {
    pname = "two-filters";
    version = "3abc7adf1b7b964b286d0a4df24a062dad107c4b";
    src = fetchgit {
      url = "https://github.com/baconpaul/two-filters";
      rev = "3abc7adf1b7b964b286d0a4df24a062dad107c4b";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-m9yBbH55RR7I9lCStvaTfDuzvaSGp1Be997j0opppKs=";
    };
    date = "2026-01-12";
  };
  vst3sdk = {
    pname = "vst3sdk";
    version = "v3.7.6_build_18";
    src = fetchFromGitHub {
      owner = "steinbergmedia";
      repo = "vst3sdk";
      rev = "v3.7.6_build_18";
      fetchSubmodules = true;
      sha256 = "sha256-jfh+iP5rqov8q++IyG4FXlYKs4PQtFjCwCP6xou8N0E=";
    };
  };
}
