[hvcc]
src.github = "Wasted-Audio/hvcc"
fetch.github = "Wasted-Audio/hvcc"

[wstd2daisy]
src.git = "https://github.com/Wasted-Audio/json2daisy"
src.branch = "wstd2daisy"
fetch.git = "https://github.com/Wasted-Audio/json2daisy"
