# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  ACE = {
    pname = "ACE";
    version = "143_16518";
    src = fetchTarball {
      url = "https://uhe-dl.b-cdn.net/releases/ACE_143_16518_Linux.tar.xz";
      sha256 = "sha256-DWmyZtyrbvNoAH2D5gZcMy+ljVjZSxk3bryzX0CkGgg=";
    };
  };
  Bazille = {
    pname = "Bazille";
    version = "113_16518";
    src = fetchTarball {
      url = "https://uhe-dl.b-cdn.net/releases/Bazille_113_16518_Linux.tar.xz";
      sha256 = "sha256-0CRxtka/x5bTrWYIcYmTYu+0u7ngbtz2O3Cj0LBltt4=";
    };
  };
  ColourCopy = {
    pname = "ColourCopy";
    version = "102_16742";
    src = fetchTarball {
      url = "https://uhe-dl.b-cdn.net/releases/ColourCopy_102_16742_Linux.tar.xz";
      sha256 = "sha256-fDfClB+MoDWaUpdQkEi9sage5FToTytPIn6RNRsFTMc=";
    };
  };
  Diva = {
    pname = "Diva";
    version = "148_16519";
    src = fetchTarball {
      url = "https://uhe-dl.b-cdn.net/releases/Diva_148_16519_Linux.tar.xz";
      sha256 = "sha256-3CRzcz7BJCU0M3fEOzxmg8TWgZajiXghyA1hZ3jdFEY=";
    };
  };
  Filterscape = {
    pname = "Filterscape";
    version = "151_15664";
    src = fetchTarball {
      url = "https://uhe-dl.b-cdn.net/releases/Filterscape_151_15664_Linux.tar.xz";
      sha256 = "sha256-glx/yn5/xnPBfRMpOQBpPfDWsTrL4h6J1+hHaOQPYRk=";
    };
  };
  Hive = {
    pname = "Hive";
    version = "212_16520";
    src = fetchTarball {
      url = "https://uhe-dl.b-cdn.net/releases/Hive_212_16520_Linux.tar.xz";
      sha256 = "sha256-q+nlzaeASQJnfdiHAi1RSQTgZGaxNZzFJDPguj8OU+c=";
    };
  };
  MFM2 = {
    pname = "MFM2";
    version = "251_16742";
    src = fetchTarball {
      url = "https://uhe-dl.b-cdn.net/releases/MFM2_251_16742_Linux.tar.xz";
      sha256 = "sha256-qhYctgN+wiOwt97atks6mLhoS1k3MQNWpz91+9w+U28=";
    };
  };
  Podolski = {
    pname = "Podolski";
    version = "123_12092";
    src = fetchTarball {
      url = "https://uhe-dl.b-cdn.net/releases/Podolski_123_12092_Linux.tar.xz";
      sha256 = "sha256-jsCursOUP4sMUNcQoISlIoAg+tLC2EF9uWCb/74+m3E=";
    };
  };
  Presswerk = {
    pname = "Presswerk";
    version = "116_16960";
    src = fetchTarball {
      url = "https://uhe-dl.b-cdn.net/releases/Presswerk_116_16960_Linux.tar.xz";
      sha256 = "sha256-I7H8APPA8o2ptWYSJSVjQhGWgDl0LIJBB4zNUq1XPlE=";
    };
  };
  Protoverb = {
    pname = "Protoverb";
    version = "101_12092";
    src = fetchTarball {
      url = "https://uhe-dl.b-cdn.net/releases/Protoverb_101_12092_Linux.tar.xz";
      sha256 = "sha256-z0+MfrMnxF5I1C6U1AFTu6DFioZGKAyc1EnrN2sPqbE=";
    };
  };
  Repro-1 = {
    pname = "Repro-1";
    version = "113_16797";
    src = fetchTarball {
      url = "https://uhe-dl.b-cdn.net/releases/Repro_113_16797_Linux.tar.xz";
      sha256 = "sha256-LAWvWB+YPrm+fc1aKOcH06VTMlcbMgb0oesHmdEsmDM=";
    };
  };
  Satin = {
    pname = "Satin";
    version = "133_15721";
    src = fetchTarball {
      url = "https://uhe-dl.b-cdn.net/releases/Satin_133_15721_Linux.tar.xz";
      sha256 = "sha256-TkA5MrqwOi23wre/FxGbUlEJ+uck3me9jxq4kUxFhng=";
    };
  };
  TripleCheese = {
    pname = "TripleCheese";
    version = "130_12092";
    src = fetchTarball {
      url = "https://uhe-dl.b-cdn.net/releases/TripleCheese_130_12092_Linux.tar.xz";
      sha256 = "sha256-L+uCW6Envlrd/6CRhTwrnazBSCroqlGrm3ltZ9jPGR0=";
    };
  };
  Twangstrom = {
    pname = "Twangstrom";
    version = "102_16742";
    src = fetchTarball {
      url = "https://uhe-dl.b-cdn.net/releases/Twangstrom_102_16742_Linux.tar.xz";
      sha256 = "sha256-PU5+4UROIPcQ4/bkz3AMcGNMDzNWZqH42zPzt2z7Ius=";
    };
  };
  Uhbik = {
    pname = "Uhbik";
    version = "131_8256";
    src = fetchTarball {
      url = "https://uhe-dl.b-cdn.net/releases/Uhbik_131_8256_Linux.tar.xz";
      sha256 = "sha256-7bxp2xRITNXuq8rpXIZjnqaGPssJT2K8Cr9HPoVtbLU=";
    };
  };
  Zebra2 = {
    pname = "Zebra2";
    version = "294_16765";
    src = fetchTarball {
      url = "https://uhe-dl.b-cdn.net/releases/Zebra_Legacy_294_16765_Linux.zip";
      sha256 = "sha256-COy4yfkdjrL41g7P8eZWgLG9ogPZ6XCazkju0Ot/jHE=";
    };
  };
  patchelf-raphi = {
    pname = "patchelf-raphi";
    version = "9079354d2b94050f38594b5fab5f764f73e4b7e0";
    src = fetchgit {
      url = "https://git.sr.ht/~raphi/patchelf";
      rev = "9079354d2b94050f38594b5fab5f764f73e4b7e0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-fJXkByP2QXo/3tpP1mPCYKmGolwlWLxubGV6xdytmCg=";
    };
    date = "2022-08-30";
  };
}
