# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  jdrummer = {
    pname = "jdrummer";
    version = "83978e58738c4ac4fc486fb821aabfaf4ee19886";
    src = fetchgit {
      url = "https://github.com/jmantra/jdrummer";
      rev = "83978e58738c4ac4fc486fb821aabfaf4ee19886";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-wR7A7aLYi6aD4V+NKp4EjcFffbsg4WC8Fug8lpa193k=";
    };
    date = "2026-01-03";
  };
  juce = {
    pname = "juce";
    version = "7.0.9";
    src = fetchgit {
      url = "https://github.com/juce-framework/JUCE.git";
      rev = "7.0.9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-k8cNTPH9OgOav4dsSLqrd5PlJ1rqO0PLt6Lwmumc2Gg=";
    };
  };
}
