# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  mcp-searxng = {
    pname = "mcp-searxng";
    version = "v1.0.3";
    src = fetchFromGitHub {
      owner = "ihor-sokoliuk";
      repo = "mcp-searxng";
      rev = "v1.0.3";
      fetchSubmodules = false;
      sha256 = "sha256-DEZW6pG/t13I95ZmW7WyIJNfPd64d9cf55ceUyl0SAY=";
    };
    extract = {
      "package-lock.json" = ./. + "/sha256-DEZW6pG_t13I95ZmW7WyIJNfPd64d9cf55ceUyl0SAY=/package-lock.json";
      "package.json" = ./. + "/sha256-DEZW6pG_t13I95ZmW7WyIJNfPd64d9cf55ceUyl0SAY=/package.json";
    };
  };
}
