# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  mcp-searxng = {
    pname = "mcp-searxng";
    version = "v1.12.0";
    src = fetchFromGitHub {
      owner = "ihor-sokoliuk";
      repo = "mcp-searxng";
      rev = "v1.12.0";
      fetchSubmodules = false;
      sha256 = "sha256-27tg5ol1anVVRVXWX4ywjYv+OeI5bWNz27EPu4gNQwU=";
    };
    extract = {
      "package-lock.json" = ./. + "/sha256-27tg5ol1anVVRVXWX4ywjYv+OeI5bWNz27EPu4gNQwU=/package-lock.json";
      "package.json" = ./. + "/sha256-27tg5ol1anVVRVXWX4ywjYv+OeI5bWNz27EPu4gNQwU=/package.json";
    };
  };
}
