# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  mcp-searxng = {
    pname = "mcp-searxng";
    version = "v1.8.0";
    src = fetchFromGitHub {
      owner = "ihor-sokoliuk";
      repo = "mcp-searxng";
      rev = "v1.8.0";
      fetchSubmodules = false;
      sha256 = "sha256-xyNjBJ268JqJVhKOC/wLQ4SqKqTI+TgQEgbSdYLGid0=";
    };
    extract = {
      "package-lock.json" = ./. + "/sha256-xyNjBJ268JqJVhKOC_wLQ4SqKqTI+TgQEgbSdYLGid0=/package-lock.json";
      "package.json" = ./. + "/sha256-xyNjBJ268JqJVhKOC_wLQ4SqKqTI+TgQEgbSdYLGid0=/package.json";
    };
  };
}
