# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  ob-xf = {
    pname = "ob-xf";
    version = "b34831b9873cb38ac055ececce4fa6d960757415";
    src = fetchgit {
      url = "https://github.com/surge-synthesizer/OB-Xf";
      rev = "b34831b9873cb38ac055ececce4fa6d960757415";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-lu8wRDir/lGja80swR/CM0ho5389qGrBMRO//02K+8M=";
    };
    date = "2026-02-20";
  };
}
