# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  ob-xf = {
    pname = "ob-xf";
    version = "e076498cabf08efda736cc7264b2b8ddcca5f4f2";
    src = fetchgit {
      url = "https://github.com/surge-synthesizer/OB-Xf";
      rev = "e076498cabf08efda736cc7264b2b8ddcca5f4f2";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ojiCKCyi5KDkYEEEuZaHlW3Q8W7eONR5aXxkoRruxWM=";
    };
    date = "2025-10-02";
  };
}
