# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  ob-xf = {
    pname = "ob-xf";
    version = "6f4e75be53e7971ed5ef23da10f063becd7598a1";
    src = fetchgit {
      url = "https://github.com/surge-synthesizer/OB-Xf";
      rev = "6f4e75be53e7971ed5ef23da10f063becd7598a1";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-uWx7jWFMhPHEm89yu/FcvmMLlUzy4pF+x9I0S61h3V0=";
    };
    date = "2026-03-24";
  };
}
