# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  zlint-bin-aarch64-darwin = {
    pname = "zlint-bin-aarch64-darwin";
    version = "v0.4.3";
    src = fetchurl {
      url = "https://github.com/DonIsaac/zlint/releases/download/v0.4.3/zlint-macos-aarch64";
      sha256 = "sha256-SK8zfhewCs5vDBeJRLmJL1KIOOB+ak0be9Y3ZFYce5Q=";
    };
  };
  zlint-bin-aarch64-linux = {
    pname = "zlint-bin-aarch64-linux";
    version = "v0.4.3";
    src = fetchurl {
      url = "https://github.com/DonIsaac/zlint/releases/download/v0.4.3/zlint-linux-aarch64";
      sha256 = "sha256-CuXsF8arVp1Uzi7ygNYHdlJqhcOkABr3TeqhtVs4LgU=";
    };
  };
  zlint-bin-x86_64-darwin = {
    pname = "zlint-bin-x86_64-darwin";
    version = "v0.4.3";
    src = fetchurl {
      url = "https://github.com/DonIsaac/zlint/releases/download/v0.4.3/zlint-macos-x86_64";
      sha256 = "sha256-qCQoMiPCqb/WoTorR60fmgRHZnMoPLE2v9yfWEJKJz8=";
    };
  };
  zlint-bin-x86_64-linux = {
    pname = "zlint-bin-x86_64-linux";
    version = "v0.4.3";
    src = fetchurl {
      url = "https://github.com/DonIsaac/zlint/releases/download/v0.4.3/zlint-linux-x86_64";
      sha256 = "sha256-u62D3aNSWyv8OZQbVct8qNMS1nhnZ1sRqaPFOtJNm0c=";
    };
  };
}
