[dwm-flexipatch]
src.git = "https://github.com/bakkeby/dwm-flexipatch"
fetch.github = "bakkeby/dwm-flexipatch"

[st-flexipatch]
src.git = "https://github.com/bakkeby/st-flexipatch"
fetch.github = "bakkeby/st-flexipatch"

[dmenu-flexipatch]
src.git = "https://github.com/bakkeby/dmenu-flexipatch"
fetch.github = "bakkeby/dmenu-flexipatch"

[slock-flexipatch]
src.git = "https://github.com/bakkeby/slock-flexipatch"
fetch.github = "bakkeby/slock-flexipatch"

[taffybar]
src.git = "https://github.com/taffybar/taffybar"
fetch.github = "taffybar/taffybar"

[xmonad-entryhelper]
src.git = "https://github.com/Javran/xmonad-entryhelper"
fetch.github = "Javran/xmonad-entryhelper"

[kiwmi]
src.git = "https://github.com/buffet/kiwmi"
fetch.github = "buffet/kiwmi"

[zrythm]
src.git = "https://git.sr.ht/~alextee/zrythm"
fetch.git = "https://git.sr.ht/~alextee/zrythm"

[libadwaita]
src.git = "https://gitlab.gnome.org/GNOME/libadwaita"
fetch.git = "https://gitlab.gnome.org/GNOME/libadwaita"

[luakit]
src.git = "https://github.com/luakit/luakit"
src.branch = "develop"
fetch.github = "luakit/luakit"
