[dwm-flexipatch]
src.git = "https://github.com/bakkeby/dwm-flexipatch"
fetch.github = "bakkeby/dwm-flexipatch"

[st-flexipatch]
src.git = "https://github.com/bakkeby/st-flexipatch"
fetch.github = "bakkeby/st-flexipatch"
