# libraries

[xmonad-entryhelper]
src.git = "https://github.com/Javran/xmonad-entryhelper"
fetch.github = "Javran/xmonad-entryhelper"

[zix-git]
src.git = "https://github.com/drobilla/zix"
fetch.github = "drobilla/zix"

[lua-dbus_proxy]
src.github_tag = "stefano-m/lua-dbus_proxy"
fetch.github = "stefano-m/lua-dbus_proxy"

[lua-dbus]
src.git = "https://github.com/dodo/lua-dbus"
fetch.github = "dodo/lua-dbus"

[bling]
src.git = "https://github.com/blingcorp/bling"
fetch.github = "blingcorp/bling"

[zmusic]
src.github = "ZDoom/ZMusic"
fetch.github = "ZDoom/ZMusic"

[carla-git]
src.git = "https://github.com/falkTX/Carla"
fetch.github = "falkTX/Carla"

[gtk-4_13_0]
src.manual = "4.13.0"
fetch.github = "GNOME/gtk"

[libadwaita-1_4]
src.manual = "1.4.rc"
fetch.github = "GNOME/libadwaita"

# programs

[dwm-flexipatch]
src.git = "https://github.com/bakkeby/dwm-flexipatch"
fetch.github = "bakkeby/dwm-flexipatch"

[st-flexipatch]
src.git = "https://github.com/bakkeby/st-flexipatch"
fetch.github = "bakkeby/st-flexipatch"

[dmenu-flexipatch]
src.git = "https://github.com/bakkeby/dmenu-flexipatch"
fetch.github = "bakkeby/dmenu-flexipatch"

[slock-flexipatch]
src.git = "https://github.com/bakkeby/slock-flexipatch"
fetch.github = "bakkeby/slock-flexipatch"

[taffybar]
src.git = "https://github.com/taffybar/taffybar"
fetch.github = "taffybar/taffybar"

[kiwmi]
src.git = "https://github.com/buffet/kiwmi"
fetch.github = "buffet/kiwmi"

[zrythm]
src.git = "https://git.sr.ht/~alextee/zrythm"
fetch.git = "https://git.sr.ht/~alextee/zrythm"

[luakit]
src.git = "https://github.com/luakit/luakit"
src.branch = "develop"
fetch.github = "luakit/luakit"

[tailwindcss-intellisense]
src.git = "https://github.com/tailwindlabs/tailwindcss-intellisense"
fetch.github = "tailwindlabs/tailwindcss-intellisense"

[lv2vst]
src.git = "https://github.com/x42/lv2vst"
fetch.github = "x42/lv2vst"

[raze]
src.github = "ZDoom/Raze"
fetch.github = "ZDoom/Raze"

[cardinal]
src.git = "https://github.com/DISTRHO/Cardinal"
fetch.github = "DISTRHO/Cardinal"
git.fetchSubmodules = true

[keepmenu]
src.git = "https://github.com/firecat53/keepmenu"
fetch.github = "firecat53/keepmenu"

[dpf-plugins]
src.github = "DISTRHO/DPF-Plugins"
fetch.github = "DISTRHO/DPF-Plugins"

[kmonad]
src.git = "https://github.com/kmonad/kmonad"
fetch.github = "kmonad/kmonad"

[fennel-language-server]
src.git = "https://github.com/rydesun/fennel-language-server"
fetch.github = "rydesun/fennel-language-server"
cargo_locks = ["Cargo.lock"]

[ildaeil]
src.git = "https://github.com/DISTRHO/Ildaeil"
fetch.github = "DISTRHO/Ildaeil"
git.fetchSubmodules = true

[macemu]
src.git = "https://github.com/kanjitalk755/macemu"
fetch.github = "kanjitalk755/macemu"

[basiliskii-bin]
src.github_tag = "Korkman/macemu-appimage-builder"
fetch.url = "https://github.com/Korkman/macemu-appimage-builder/releases/download/$ver/BasiliskII-x86_64.AppImage"
# fetch.force = true

[sheepshaver-bin]
src.github_tag = "Korkman/macemu-appimage-builder"
fetch.url = "https://github.com/Korkman/macemu-appimage-builder/releases/download/$ver/SheepShaver-x86_64.AppImage"
# fetch.force = true
