# libraries

[xmonad-entryhelper]
src.git = "https://github.com/Javran/xmonad-entryhelper"
fetch.github = "Javran/xmonad-entryhelper"

[libadwaita]
src.git = "https://gitlab.gnome.org/GNOME/libadwaita"
fetch.git = "https://gitlab.gnome.org/GNOME/libadwaita"

[zix]
src.git = "https://github.com/drobilla/zix"
fetch.github = "drobilla/zix"

[lua-dbus_proxy]
src.git = "https://github.com/stefano-m/lua-dbus_proxy"
fetch.github = "stefano-m/lua-dbus_proxy"

[lua-dbus]
src.git = "https://github.com/dodo/lua-dbus"
fetch.github = "dodo/lua-dbus"

[zmusic]
src.git = "https://github.com/ZDoom/ZMusic"
fetch.github = "ZDoom/ZMusic"

# programs

[dwm-flexipatch]
src.git = "https://github.com/bakkeby/dwm-flexipatch"
fetch.github = "bakkeby/dwm-flexipatch"

[st-flexipatch]
src.git = "https://github.com/bakkeby/st-flexipatch"
fetch.github = "bakkeby/st-flexipatch"

[dmenu-flexipatch]
src.git = "https://github.com/bakkeby/dmenu-flexipatch"
fetch.github = "bakkeby/dmenu-flexipatch"

[slock-flexipatch]
src.git = "https://github.com/bakkeby/slock-flexipatch"
fetch.github = "bakkeby/slock-flexipatch"

[taffybar]
src.git = "https://github.com/taffybar/taffybar"
fetch.github = "taffybar/taffybar"

[kiwmi]
src.git = "https://github.com/buffet/kiwmi"
fetch.github = "buffet/kiwmi"

[zrythm]
src.git = "https://git.sr.ht/~alextee/zrythm"
fetch.git = "https://git.sr.ht/~alextee/zrythm"

[luakit]
src.git = "https://github.com/luakit/luakit"
src.branch = "develop"
fetch.github = "luakit/luakit"

[tailwindcss-intellisense]
src.git = "https://github.com/tailwindlabs/tailwindcss-intellisense"
fetch.github = "tailwindlabs/tailwindcss-intellisense"

[lv2vst]
src.git = "https://github.com/x42/lv2vst"
fetch.github = "x42/lv2vst"

[raze]
src.git = "https://github.com/ZDoom/Raze"
fetch.github = "ZDoom/Raze"
