# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  ildaeil = {
    pname = "ildaeil";
    version = "10c9089d261567f4feec04859135924f003415e3";
    src = fetchFromGitHub {
      owner = "DISTRHO";
      repo = "Ildaeil";
      rev = "10c9089d261567f4feec04859135924f003415e3";
      fetchSubmodules = true;
      sha256 = "sha256-zHD82RNTqkFpvbh4Js5VFIAULIHv8qFRaiUi67LRZT4=";
    };
    date = "2024-04-18";
  };
}
