# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  proton-cachyos = {
    pname = "proton-cachyos";
    version = "cachyos-11.0-20260429-slr";
    src = fetchTarball {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-11.0-20260429-slr/proton-cachyos-11.0-20260429-slr-x86_64_v3.tar.xz";
      sha256 = "sha256-Ba+muUD9stahXexvCK46E2Oqdkppb+x1EW3nnrkfElo=";
    };
  };
  proton-em = {
    pname = "proton-em";
    version = "EM-10.0-37-HDR";
    src = fetchTarball {
      url = "https://github.com/Etaash-mathamsetty/Proton/releases/download/EM-10.0-37-HDR/proton-EM-10.0-37-HDR.tar.xz";
      sha256 = "sha256-yap/7G6TeJ9vMtc5H/iWu8w3sM8mI6762G+K2JzSlgk=";
    };
  };
  proton-ge = {
    pname = "proton-ge";
    version = "GE-Proton10-34";
    src = fetchTarball {
      url = "https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton10-34/GE-Proton10-34.tar.gz";
      sha256 = "sha256-lzPsYYcrp5NoT3B0WFj3o10Z7tXx7xva1wEP3edeuqM=";
    };
  };
  proton-sarek = {
    pname = "proton-sarek";
    version = "Proton-Sarek10-29";
    src = fetchTarball {
      url = "https://github.com/pythonlover02/Proton-Sarek/releases/download/Proton-Sarek10-29/Proton-Sarek10-29.tar.gz";
      sha256 = "sha256-evX7PztqFIVhugMyxWs8J6qQCglY901f8StlpwzgGqw=";
    };
  };
  proton-sarek-async = {
    pname = "proton-sarek-async";
    version = "Proton-Sarek10-29";
    src = fetchTarball {
      url = "https://github.com/pythonlover02/Proton-Sarek/releases/download/Proton-Sarek10-29/Proton-Sarek10-29-async.tar.gz";
      sha256 = "sha256-ojAGHAPJzWPb0WLjxJr50J2lqryR1hDMbZT6iKb0Vec=";
    };
  };
}
