# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  proton-cachyos = {
    pname = "proton-cachyos";
    version = "cachyos-10.0-20260102-slr";
    src = fetchurl {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-10.0-20260102-slr/proton-cachyos-10.0-20260102-slr-x86_64_v3.tar.xz";
      sha256 = "sha256-lQtTLrPBVPd9sRPWhyXOse8TwuHQ6NmiRKiUnxdJb+E=";
    };
  };
  proton-ge = {
    pname = "proton-ge";
    version = "GE-Proton10-28";
    src = fetchurl {
      url = "https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton10-28/GE-Proton10-28.tar.gz";
      sha256 = "sha256-TFzEbn8a9T9hDgLGC8lHDbDYLgcrAHI3LvWIqCxN4xY=";
    };
  };
  proton-sarek = {
    pname = "proton-sarek";
    version = "Proton-Sarek10-17";
    src = fetchurl {
      url = "https://github.com/pythonlover02/Proton-Sarek/releases/download/Proton-Sarek10-17/Proton-Sarek10-17.tar.gz";
      sha256 = "sha256-4CsQ08bYdKepWv2nMhDVi9BEmS9mGqMp4sqXxdoLGew=";
    };
  };
  proton-sarek-async = {
    pname = "proton-sarek-async";
    version = "Proton-Sarek10-17";
    src = fetchurl {
      url = "https://github.com/pythonlover02/Proton-Sarek/releases/download/Proton-Sarek10-17/Proton-Sarek10-17-async.tar.gz";
      sha256 = "sha256-mDrhl4kY0lD1TX06A/oJ5QXtbjT+Q+He+QopmYQTaH8=";
    };
  };
}
