# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  uzdoom = {
    pname = "uzdoom";
    version = "b4eeea220389f8ae026e6b9537f165f2a0b7c99f";
    src = fetchgit {
      url = "https://github.com/UZDoom/UZDoom";
      rev = "b4eeea220389f8ae026e6b9537f165f2a0b7c99f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-kusQZE/dTiRZILmLRC5ynajKJtdhn1g+ypL+SFD27pk=";
    };
    date = "2025-11-28";
  };
}
