# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  uzdoom = {
    pname = "uzdoom";
    version = "b01b9ed6cd13b20f4af737b7ca483e0a3e008d5a";
    src = fetchgit {
      url = "https://github.com/UZDoom/UZDoom";
      rev = "b01b9ed6cd13b20f4af737b7ca483e0a3e008d5a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-8sPdEBJSEmklgLtl257S0zHRrJ/IjfFg02mra2Babcg=";
    };
    date = "2025-11-27";
  };
}
