# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  uzdoom = {
    pname = "uzdoom";
    version = "df7ff511e270dee3659478c046250a1bc175d50f";
    src = fetchgit {
      url = "https://github.com/UZDoom/UZDoom";
      rev = "df7ff511e270dee3659478c046250a1bc175d50f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-NTQJL1Pk3Lont0GQEYcvYibqmxX3BcHRsOuGEVQt4ig=";
    };
    date = "2025-11-20";
  };
}
