# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  crepe-vamp-plugin-bin = {
    pname = "crepe-vamp-plugin-bin";
    version = "3.0.0";
    src = fetchurl {
      url = "https://github.com/Ircam-Partiels/crepe-vamp-plugin/releases/download/3.0.0/Crepe-Linux.tar.gz";
      sha256 = "sha256-hTy1x14ztAHfnPvi5tLHqH9HsJQvn5BB4YtEV4eMqoI=";
    };
  };
}
