[just-a-sample-bin]
src.github = "BOBONA/Just-a-Sample"
src.from_pattern = '-latest'
src.to_pattern = ""
src.prefix = "v"
fetch.url = "https://github.com/BOBONA/Just-a-Sample/releases/download/v$ver-latest/JAS.Linux.VST3.v$ver.0.zip"
