# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  osirus-clap-aarch64 = {
    pname = "osirus-clap-aarch64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_aarch64-Osirus-CLAP.zip";
      sha256 = "sha256-hz1PUQJCRXQ7STf1poydTy8oM078P99YdOUlWLcJjl4=";
    };
  };
  osirus-clap-x86_64 = {
    pname = "osirus-clap-x86_64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_x86_64-Osirus-CLAP.zip";
      sha256 = "sha256-3ZPQ3agzLI7jxzAUIcczCOE5u3WTJCxIJ4xsp/H4guY=";
    };
  };
  osirus-lv2-aarch64 = {
    pname = "osirus-lv2-aarch64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_aarch64-Osirus-LV2.zip";
      sha256 = "sha256-Ii9GlTi7mGzmtki6XbdFT37rtywAtfChvn8nVlA97Zg=";
    };
  };
  osirus-lv2-x86_64 = {
    pname = "osirus-lv2-x86_64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_x86_64-Osirus-LV2.zip";
      sha256 = "sha256-jLnRBgiuhiSEfeXULIzcbCoz/EnFni9XdaDDPlPn410=";
    };
  };
  osirus-test-console-aarch64 = {
    pname = "osirus-test-console-aarch64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_aarch64-OsirusTestConsole.zip";
      sha256 = "sha256-Js1Gz+MM2/lw/fzBj59h/SGohBVCGAK2iqN7ai7rjMY=";
    };
  };
  osirus-test-console-x86_64 = {
    pname = "osirus-test-console-x86_64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_x86_64-OsirusTestConsole.zip";
      sha256 = "sha256-hV7IHPE50TqMPZ9S1VI3CqsNLVqHdtpmbwRI9o8OHEo=";
    };
  };
  osirus-vst2-aarch64 = {
    pname = "osirus-vst2-aarch64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_aarch64-Osirus-VST2.zip";
      sha256 = "sha256-/JBOcWrUH2ENTk4ckvnj8+3i10OsPgylSMT2Ph2F5gs=";
    };
  };
  osirus-vst2-x86_64 = {
    pname = "osirus-vst2-x86_64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_x86_64-Osirus-VST2.zip";
      sha256 = "sha256-nf0Vr7iaK8SF5Kjzlw+RlSEQeedvznnKuO2Wpb6L5hg=";
    };
  };
  osirus-vst3-aarch64 = {
    pname = "osirus-vst3-aarch64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_aarch64-Osirus-VST3.zip";
      sha256 = "sha256-X8Rdm8rz93cYGBYt6HwmLUKxlXKqAdIIKDZXbFOVvnc=";
    };
  };
  osirus-vst3-x86_64 = {
    pname = "osirus-vst3-x86_64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_x86_64-Osirus-VST3.zip";
      sha256 = "sha256-lRrbF1DXXJvcIGVEGRrKm2HHNmnRbyIgKu72JKmfW2s=";
    };
  };
  osirusfx-clap-aarch64 = {
    pname = "osirusfx-clap-aarch64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_aarch64-OsirusFX-CLAP.zip";
      sha256 = "sha256-3yu6mg6UL7rAJmPBPEvqV+5RstbUlzEA1ylRSTbjpAc=";
    };
  };
  osirusfx-clap-x86_64 = {
    pname = "osirusfx-clap-x86_64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_x86_64-OsirusFX-CLAP.zip";
      sha256 = "sha256-ch6gBO77rgTTBiIv60BSN/QO5C30Sh9V/r/fxVcZb/g=";
    };
  };
  osirusfx-lv2-aarch64 = {
    pname = "osirusfx-lv2-aarch64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_aarch64-OsirusFX-LV2.zip";
      sha256 = "sha256-qZHC6zuA/v2/XRlVrha3RrvfSYLBYLHVRdhmZg/lcxA=";
    };
  };
  osirusfx-lv2-x86_64 = {
    pname = "osirusfx-lv2-x86_64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_x86_64-OsirusFX-LV2.zip";
      sha256 = "sha256-WjXD01lE1UTl/a9nn57yw6W/RhLrLtFx5O0Uh/gYRgU=";
    };
  };
  osirusfx-vst2-aarch64 = {
    pname = "osirusfx-vst2-aarch64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_aarch64-OsirusFX-VST2.zip";
      sha256 = "sha256-NYHYxSx/P5FI5sz+wfYA7MuFx+nZerzv0boCGRV1UWo=";
    };
  };
  osirusfx-vst2-x86_64 = {
    pname = "osirusfx-vst2-x86_64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_x86_64-OsirusFX-VST2.zip";
      sha256 = "sha256-tgBB0K9X6SrGkQzAyaKwYbucIfIVxi7tuxya05HgZzs=";
    };
  };
  osirusfx-vst3-aarch64 = {
    pname = "osirusfx-vst3-aarch64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_aarch64-OsirusFX-VST3.zip";
      sha256 = "sha256-TwVgNa5RMUmtEVCBIM77Pi2huas05uqgI8VQ2CmtzwY=";
    };
  };
  osirusfx-vst3-x86_64 = {
    pname = "osirusfx-vst3-x86_64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_x86_64-OsirusFX-VST3.zip";
      sha256 = "sha256-IycZI6O91vSPjMEISg0e187T4BFxKzhUR0O/fPahcZA=";
    };
  };
  ostirus-clap-aarch64 = {
    pname = "ostirus-clap-aarch64";
    version = "1.3.15";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-1.3.15-Linux_aarch64-OsTIrus-CLAP.zip";
      sha256 = "sha256-0jnL+OHjWockNZ0u7Gs6B/fx/tXrTFo8ZYKGbWThzBc=";
    };
  };
  ostirus-clap-x86_64 = {
    pname = "ostirus-clap-x86_64";
    version = "1.3.15";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-1.3.15-Linux_x86_64-OsTIrus-CLAP.zip";
      sha256 = "sha256-sK3HugjmtVukTGJH3EL+IRF6c/CYETkpWHSIxAHveSk=";
    };
  };
  ostirus-lv2-aarch64 = {
    pname = "ostirus-lv2-aarch64";
    version = "1.3.15";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-1.3.15-Linux_aarch64-OsTIrus-LV2.zip";
      sha256 = "sha256-4E0OCMqrqM3IqeOpqMSdTJ76xMpUG8Yshs3UnU9CSxw=";
    };
  };
  ostirus-lv2-x86_64 = {
    pname = "ostirus-lv2-x86_64";
    version = "1.3.15";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-1.3.15-Linux_x86_64-OsTIrus-LV2.zip";
      sha256 = "sha256-Jt/wyoa+z3QKe38QYxHnArX3cwJ5CA2ZGI9exZlmgko=";
    };
  };
  ostirus-test-console-aarch64 = {
    pname = "ostirus-test-console-aarch64";
    version = "1.3.15";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-1.3.15-Linux_aarch64-OsTIrusTestConsole.zip";
      sha256 = "sha256-Olmugl9Nzq+J0JE5ly3WMYfcRTFknI0c6M/GUkq4cVM=";
    };
  };
  ostirus-test-console-x86_64 = {
    pname = "ostirus-test-console-x86_64";
    version = "1.3.15";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-1.3.15-Linux_x86_64-OsTIrusTestConsole.zip";
      sha256 = "sha256-5j33IZgZQH5r0Q0OdrcbOclOygmr+oHgwfk1xEAPwDg=";
    };
  };
  ostirus-vst2-aarch64 = {
    pname = "ostirus-vst2-aarch64";
    version = "1.3.15";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-1.3.15-Linux_aarch64-OsTIrus-VST2.zip";
      sha256 = "sha256-3XhInGTbOE2jawVdxR/kK8oV3IeGXz9rdftVhMjhrXk=";
    };
  };
  ostirus-vst2-x86_64 = {
    pname = "ostirus-vst2-x86_64";
    version = "1.3.15";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-1.3.15-Linux_x86_64-OsTIrus-VST2.zip";
      sha256 = "sha256-aDv4PsLJt+shuS1gAn+6aYtoQUJoH20dc9Rqdu4X3Mw=";
    };
  };
  ostirus-vst3-aarch64 = {
    pname = "ostirus-vst3-aarch64";
    version = "1.3.15";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-1.3.15-Linux_aarch64-OsTIrus-VST3.zip";
      sha256 = "sha256-UdBXdwQSXgfpFBp92TAMKUMC2Rp/GTgtfFQYzTwCD1U=";
    };
  };
  ostirus-vst3-x86_64 = {
    pname = "ostirus-vst3-x86_64";
    version = "1.3.15";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-1.3.15-Linux_x86_64-OsTIrus-VST3.zip";
      sha256 = "sha256-hjhJBTqZzVzLfL5JR5wy01O6Hog+moAqkydEy6jukqQ=";
    };
  };
  ostirusfx-clap-aarch64 = {
    pname = "ostirusfx-clap-aarch64";
    version = "1.3.15";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-1.3.15-Linux_aarch64-OsTIrusFX-CLAP.zip";
      sha256 = "sha256-OO/lbXvphKBVpmYhjFvYERfNGow63/BBuawQBjnav3c=";
    };
  };
  ostirusfx-clap-x86_64 = {
    pname = "ostirusfx-clap-x86_64";
    version = "1.3.15";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-1.3.15-Linux_x86_64-OsTIrusFX-CLAP.zip";
      sha256 = "sha256-pbcv+iY9D3Wbit9jCtXORMYC13z94LFT2WhL0vz5kQk=";
    };
  };
  ostirusfx-lv2-aarch64 = {
    pname = "ostirusfx-lv2-aarch64";
    version = "1.3.15";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-1.3.15-Linux_aarch64-OsTIrusFX-LV2.zip";
      sha256 = "sha256-m5EVub/jsENn4Fx7J6qVnGfoahfef++CNDfutpFoKTI=";
    };
  };
  ostirusfx-lv2-x86_64 = {
    pname = "ostirusfx-lv2-x86_64";
    version = "1.3.15";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-1.3.15-Linux_x86_64-OsTIrusFX-LV2.zip";
      sha256 = "sha256-ktsd1uI8x0UY2Q9ZbHjoplNl3l8LaOaYOArjZcFktLI=";
    };
  };
  ostirusfx-vst2-aarch64 = {
    pname = "ostirusfx-vst2-aarch64";
    version = "1.3.15";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-1.3.15-Linux_aarch64-OsTIrusFX-VST2.zip";
      sha256 = "sha256-rEFLw+djBAslZnO2Deoqd1XMIozzAy8eTf4CEVjF9JY=";
    };
  };
  ostirusfx-vst2-x86_64 = {
    pname = "ostirusfx-vst2-x86_64";
    version = "1.3.15";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-1.3.15-Linux_x86_64-OsTIrusFX-VST2.zip";
      sha256 = "sha256-YIMp3wFJtbCDe2TNsM+EZurAK3RDdoVkjd13jnojmmA=";
    };
  };
  ostirusfx-vst3-aarch64 = {
    pname = "ostirusfx-vst3-aarch64";
    version = "1.3.15";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-1.3.15-Linux_aarch64-OsTIrusFX-VST3.zip";
      sha256 = "sha256-REaoe+SSMyLxf0nXmdld+5v25Np2vopxwN3A4NAcbvE=";
    };
  };
  ostirusfx-vst3-x86_64 = {
    pname = "ostirusfx-vst3-x86_64";
    version = "1.3.15";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/ostirus/DSP56300Emu-1.3.15-Linux_x86_64-OsTIrusFX-VST3.zip";
      sha256 = "sha256-Ar/wHXlQsSQTY5F9Qw55YVidGwJe76Y79TajbAR+sog=";
    };
  };
  vavra-clap-aarch64 = {
    pname = "vavra-clap-aarch64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-1.3.14-Linux_aarch64-Vavra-CLAP.zip";
      sha256 = "sha256-YmFELfJcRpME841fP9KIJ1NY8es/9s+5BUXUqj6EWHc=";
    };
  };
  vavra-clap-x86_64 = {
    pname = "vavra-clap-x86_64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-1.3.14-Linux_x86_64-Vavra-CLAP.zip";
      sha256 = "sha256-BkPgRZ5cWX+4HE54lsSAgwMF7I5VOBy4+Bnj/5zIU+g=";
    };
  };
  vavra-lv2-aarch64 = {
    pname = "vavra-lv2-aarch64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-1.3.14-Linux_aarch64-Vavra-LV2.zip";
      sha256 = "sha256-hDNmc6ur0XOejlGMbN/gZ6Fz9TaslKosz7TzITwOKD0=";
    };
  };
  vavra-lv2-x86_64 = {
    pname = "vavra-lv2-x86_64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-1.3.14-Linux_x86_64-Vavra-LV2.zip";
      sha256 = "sha256-yunW13nTokmiNHKdfMQNPEWKdqrbhQdArxY8lch2iYk=";
    };
  };
  vavra-performance-test-aarch64 = {
    pname = "vavra-performance-test-aarch64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-1.3.14-Linux_aarch64-VavraPerformanceTest.zip";
      sha256 = "sha256-KKuU8lARZLXhOuGakQF7s2Pnpx0AiTqCxzql98oZdYM=";
    };
  };
  vavra-performance-test-x86_64 = {
    pname = "vavra-performance-test-x86_64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-1.3.14-Linux_x86_64-VavraPerformanceTest.zip";
      sha256 = "sha256-P76Iq95CPaFMFlA5h2uIkpIvr40XnLcSa1K/xisSiBM=";
    };
  };
  vavra-vst2-aarch64 = {
    pname = "vavra-vst2-aarch64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-1.3.14-Linux_aarch64-Vavra-VST2.zip";
      sha256 = "sha256-8MaAkJk51tqiezYzp1o8li1ndoQh82oJJFH/WBUi0Ws=";
    };
  };
  vavra-vst2-x86_64 = {
    pname = "vavra-vst2-x86_64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-1.3.14-Linux_x86_64-Vavra-VST2.zip";
      sha256 = "sha256-YdPsRH2/lG660zl5jXYE8M7XqfM7issEOi4wtv5jZEA=";
    };
  };
  vavra-vst3-aarch64 = {
    pname = "vavra-vst3-aarch64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-1.3.14-Linux_aarch64-Vavra-VST3.zip";
      sha256 = "sha256-0PPXYMMgogPgumVr2qNi4ZCcEofjbK4oLMuZx+2h/JQ=";
    };
  };
  vavra-vst3-x86_64 = {
    pname = "vavra-vst3-x86_64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-1.3.14-Linux_x86_64-Vavra-VST3.zip";
      sha256 = "sha256-e0z/gA64H0owG5C/bNF8YpBb7wuWBwMUakZougF79hE=";
    };
  };
  vavrafx-clap-aarch64 = {
    pname = "vavrafx-clap-aarch64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-1.3.14-Linux_aarch64-VavraFX-CLAP.zip";
      sha256 = "sha256-lMnSf0rHRONWC0tc6Y+G5A+CkSH/yNXCH2pz/2slLQM=";
    };
  };
  vavrafx-clap-x86_64 = {
    pname = "vavrafx-clap-x86_64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-1.3.14-Linux_x86_64-VavraFX-CLAP.zip";
      sha256 = "sha256-Fxsy+zwoWI0uHtwf7gjG9LSu54zb//p3t+yrs5O0Qqk=";
    };
  };
  vavrafx-lv2-aarch64 = {
    pname = "vavrafx-lv2-aarch64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-1.3.14-Linux_aarch64-VavraFX-LV2.zip";
      sha256 = "sha256-jr2H9CJkwYzFK48464xOSnepMNf9GlpVWGHM52hovtA=";
    };
  };
  vavrafx-lv2-x86_64 = {
    pname = "vavrafx-lv2-x86_64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-1.3.14-Linux_x86_64-VavraFX-LV2.zip";
      sha256 = "sha256-l+yyqmKCcfleLoDtk6BFyBSLQnWjcgUl64rNwnDMkkc=";
    };
  };
  vavrafx-vst2-aarch64 = {
    pname = "vavrafx-vst2-aarch64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-1.3.14-Linux_aarch64-VavraFX-VST2.zip";
      sha256 = "sha256-23Xhc4kiNLneDLpFaRmOjvQ2vPo+tImCUd6SnaDCuOU=";
    };
  };
  vavrafx-vst2-x86_64 = {
    pname = "vavrafx-vst2-x86_64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-1.3.14-Linux_x86_64-VavraFX-VST2.zip";
      sha256 = "sha256-c2J9vv+D4VX2ZTNYtqwbV2UPXpQUU3rFmknoky5VWqA=";
    };
  };
  vavrafx-vst3-aarch64 = {
    pname = "vavrafx-vst3-aarch64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-1.3.14-Linux_aarch64-VavraFX-VST3.zip";
      sha256 = "sha256-PoTTdl3XuhpEQytd2l1kbORuC6UJHO8ITTYUgTyXF6U=";
    };
  };
  vavrafx-vst3-x86_64 = {
    pname = "vavrafx-vst3-x86_64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/vavra/DSP56300Emu-1.3.14-Linux_x86_64-VavraFX-VST3.zip";
      sha256 = "sha256-/2TQG+QyAW5G+nKO4Ix1Fq1tgyn85HpV91OKjYKQKo4=";
    };
  };
}
