[digits-bin]
src.webpage = "http://www.extentofthejam.com/"
src.regex = 'Digits (\d+\.\d+)'
src.from_pattern = '\.'
src.to_pattern = "_"
fetch.url = "http://www.extentofthejam.com/DigitsLinux_$ver.tar.gz"
