[fennel-language-server]
src.git = "https://github.com/rydesun/fennel-language-server"
fetch.url = "https://github.com/rydesun/fennel-language-server/archive/$ver.tar.gz"
cargo_locks = ["Cargo.lock"]
