# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  symbols-nerd-font = {
    pname = "symbols-nerd-font";
    version = "v3.4.0";
    src = fetchurl {
      url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/NerdFontsSymbolsOnly.zip";
      sha256 = "sha256-jmF5BLmA/jZIpLEWgIeI/lDJnS1JU3bLfAutvYpWTEc=";
    };
  };
}
