# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  perfetto = {
    pname = "perfetto";
    version = "v48.1";
    src = fetchFromGitHub {
      owner = "google";
      repo = "perfetto";
      rev = "v48.1";
      fetchSubmodules = false;
      sha256 = "sha256-3ce5bomy3BdsF+Fd0epekRESftbESZgAzYmGx7iC4Vk=";
    };
  };
  resonarium = {
    pname = "resonarium";
    version = "v0.0.10";
    src = fetchFromGitHub {
      owner = "gabrielsoule";
      repo = "resonarium";
      rev = "v0.0.10";
      fetchSubmodules = true;
      sha256 = "sha256-m0U0qwZktBMSMVVogb3LvxLAPOxz0q0qchw6rH1Wbbc=";
    };
  };
}
