# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  waterfox-bin = {
    pname = "waterfox-bin";
    version = "6.5.10";
    src = fetchurl {
      url = "https://cdn1.waterfox.net/waterfox/releases/6.5.10/Linux_x86_64/waterfox-6.5.10.tar.bz2";
      sha256 = "sha256-O0+R7NFFL3q7hSupyIBNI3xBVMmRvAL+TgbLaCwlKm8=";
    };
  };
}
