[lua-dbus_proxy]
src.github_tag = "stefano-m/lua-dbus_proxy"
fetch.github = "stefano-m/lua-dbus_proxy"

[lua-dbus]
src.git = "https://github.com/dodo/lua-dbus"
fetch.github = "dodo/lua-dbus"

[bling]
src.git = "https://github.com/blingcorp/bling"
fetch.github = "blingcorp/bling"
