[lua-dbus_proxy]
src.git = "https://github.com/stefano-m/lua-dbus_proxy"
fetch.git = "https://github.com/stefano-m/lua-dbus_proxy"

[lua-dbus]
src.git = "https://github.com/dodo/lua-dbus"
fetch.git = "https://github.com/dodo/lua-dbus"

[bling]
src.git = "https://github.com/blingcorp/bling"
fetch.git = "https://github.com/blingcorp/bling"
