# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  misstrhortion = {
    pname = "misstrhortion";
    version = "7504ab4036cc6598b61ba768b2b803a6b3f86178";
    src = fetchgit {
      url = "https://github.com/bandithedoge/misstrhortion";
      rev = "7504ab4036cc6598b61ba768b2b803a6b3f86178";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-CN1q8pO8so10o06qKjtJqT8Le/E7RluPoopnjK53XrE=";
    };
    date = "2024-11-02";
  };
}
