# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  ghidra-mcp = {
    pname = "ghidra-mcp";
    version = "v5.13.1";
    src = fetchFromGitHub {
      owner = "bethington";
      repo = "ghidra-mcp";
      rev = "v5.13.1";
      fetchSubmodules = false;
      sha256 = "sha256-fxUY+RKmDkPjCYXz7Fj/TWRBd0IeDap1VZ2NdqbbiJI=";
    };
  };
}
