# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  ghidra-mcp = {
    pname = "ghidra-mcp";
    version = "v5.11.0";
    src = fetchFromGitHub {
      owner = "bethington";
      repo = "ghidra-mcp";
      rev = "v5.11.0";
      fetchSubmodules = false;
      sha256 = "sha256-FrHFR822Ukcb9cTdRYP9H6O/t7LDB+vItl6mogRi6ZM=";
    };
  };
}
