# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  ghidra-mcp = {
    pname = "ghidra-mcp";
    version = "v5.10.0";
    src = fetchFromGitHub {
      owner = "bethington";
      repo = "ghidra-mcp";
      rev = "v5.10.0";
      fetchSubmodules = false;
      sha256 = "sha256-khqvuzjNB3X0SfTqbUlKFxTPRIaUeb8Vi4FPSbABdK4=";
    };
  };
}
