# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  blender-radeon-prorender = {
    pname = "blender-radeon-prorender";
    version = "v3.6.11/RadeonProRenderForBlender_3.6.11_Ubuntu24-325eb7f";
    src = fetchurl {
      url = "https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases/download/v3.6.11/RadeonProRenderForBlender_3.6.11_Ubuntu24-325eb7f-linux.zip";
      sha256 = "sha256-Tya4xRvSQEsyG0+VXJaDAbvW/444Y57iMiWO/R78S58=";
    };
  };
}
