# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  zerostack = {
    pname = "zerostack";
    version = "v1.5.1-rc1";
    src = fetchFromGitHub {
      owner = "gi-dellav";
      repo = "zerostack";
      rev = "v1.5.1-rc1";
      fetchSubmodules = false;
      sha256 = "sha256-saTgIgVeOx//IsjWBHlLPQua06iAJe0hPsF58ZRMhHU=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-saTgIgVeOx__IsjWBHlLPQua06iAJe0hPsF58ZRMhHU=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
}
