# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  zerostack = {
    pname = "zerostack";
    version = "v1.1.0";
    src = fetchFromGitHub {
      owner = "gi-dellav";
      repo = "zerostack";
      rev = "v1.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-fqCExsiolUEYyEQDTscvx35pRIeTvKYEDnmO6a9orwA=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-fqCExsiolUEYyEQDTscvx35pRIeTvKYEDnmO6a9orwA=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
}
