# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  zerostack = {
    pname = "zerostack";
    version = "v1.5.0-rc1";
    src = fetchFromGitHub {
      owner = "gi-dellav";
      repo = "zerostack";
      rev = "v1.5.0-rc1";
      fetchSubmodules = false;
      sha256 = "sha256-RLEk5nluM/vD+VljZyEx5A9QIAkz2uLvV+m+yHGTM90=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-RLEk5nluM_vD+VljZyEx5A9QIAkz2uLvV+m+yHGTM90=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
}
