# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  sox-ng = {
    pname = "sox-ng";
    version = "9f4b0097d59c5f315b0b0e9c944bfdc8aa996176";
    src = fetchgit {
      url = "https://codeberg.org/sox_ng/sox_ng.git";
      rev = "9f4b0097d59c5f315b0b0e9c944bfdc8aa996176";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-R5m1JubAZ7Uqu32QWTE5AUjSJFncL5RlJAYhya7t85E=";
    };
    date = "2025-12-29";
  };
}
