# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  sox-ng = {
    pname = "sox-ng";
    version = "6a408528f562163815ea0cad5349b2c46821ceeb";
    src = fetchgit {
      url = "https://codeberg.org/sox_ng/sox_ng.git";
      rev = "6a408528f562163815ea0cad5349b2c46821ceeb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-idJUGkaPWg0XIMzbZPkFsNGSrSUgHArk2ip/vU3OmhU=";
    };
    date = "2026-01-26";
  };
}
