# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  whisper-vamp-plugin-bin = {
    pname = "whisper-vamp-plugin-bin";
    version = "3.0.0";
    src = fetchurl {
      url = "https://github.com/Ircam-Partiels/whisper-vamp-plugin/releases/download/3.0.0/Whisper-Linux.tar.gz";
      sha256 = "sha256-BhUnGm0I+aZ/944RaxVKAbbGafOJ+5tR6LVZ8UeKIPk=";
    };
  };
}
