# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  whisper-vamp-plugin-bin = {
    pname = "whisper-vamp-plugin-bin";
    version = "1.0.0";
    src = fetchurl {
      url = "https://github.com/Ircam-Partiels/whisper-vamp-plugin/releases/download/1.0.0/Whisper-Linux.tar.gz";
      sha256 = "sha256-JmW6yftXqRvyalka3+byMh15TONQAX8xWWcYrGa+X7g=";
    };
  };
}
