[carla-git]
src.git = "https://github.com/falkTX/Carla"
fetch.github = "falkTX/Carla"

[zrythm]
src.git = "https://gitlab.zrythm.org/zrythm/zrythm.git"
fetch.git = "https://gitlab.zrythm.org/zrythm/zrythm.git"
