[carla-git]
src.git = "https://github.com/falkTX/Carla"
fetch.github = "falkTX/Carla"

[gtk-4_13_4]
src.manual = "4.13.4"
fetch.github = "GNOME/gtk"

[rtaudio-git]
src.github = "thestk/rtaudio"
fetch.github = "thestk/rtaudio"

[libadwaita-git]
src.git = "https://gitlab.gnome.org/GNOME/libadwaita"
fetch.git = "https://gitlab.gnome.org/GNOME/libadwaita"

[zrythm]
src.git = "https://gitlab.zrythm.org/zrythm/zrythm.git"
fetch.git = "https://gitlab.zrythm.org/zrythm/zrythm.git"
