# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  nu-plugin-bexpand = {
    pname = "nu-plugin-bexpand";
    version = "aab59283343e2d06d119311abf5e8c028c7579e8";
    src = fetchgit {
      url = "https://forge.axfive.net/Taylor/nu-plugin-bexpand.git";
      rev = "aab59283343e2d06d119311abf5e8c028c7579e8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-aO3SL7DO6932nW0kVRtYoWCtzR8fzGAZ5mBdF++GinY=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-aO3SL7DO6932nW0kVRtYoWCtzR8fzGAZ5mBdF++GinY=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2026-04-13";
  };
}
