# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  nu-plugin-bexpand = {
    pname = "nu-plugin-bexpand";
    version = "de17e2756684ad3d6130ff1c91aac0f1e900917a";
    src = fetchgit {
      url = "https://forge.axfive.net/Taylor/nu-plugin-bexpand.git";
      rev = "de17e2756684ad3d6130ff1c91aac0f1e900917a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-mN+54dn/to7JOXL3uCFd0/LmKEz21R3heVG6tGgiapw=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-mN+54dn_to7JOXL3uCFd0_LmKEz21R3heVG6tGgiapw=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2026-05-25";
  };
}
