# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  tree-sitter-hypr = {
    pname = "tree-sitter-hypr";
    version = "d719158abe537b1916daaea6fa03287089f0b601";
    src = fetchFromGitHub {
      owner = "luckasRanarison";
      repo = "tree-sitter-hypr";
      rev = "d719158abe537b1916daaea6fa03287089f0b601";
      fetchSubmodules = false;
      sha256 = "sha256-5iflQ4FDEvVRuaytPl08Q9CYXm2dfZ49qJyvcsOrzuI=";
    };
    date = "2025-01-21";
  };
}
