# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  tree-sitter-hypr = {
    pname = "tree-sitter-hypr";
    version = "af796443b66d7ab00184992daa3bdaede0955c87";
    src = fetchFromGitHub {
      owner = "luckasRanarison";
      repo = "tree-sitter-hypr";
      rev = "af796443b66d7ab00184992daa3bdaede0955c87";
      fetchSubmodules = false;
      sha256 = "sha256-DsiJ9+Tc5KuxjRywfrofZqft/iIGedzC6cLijq1MZvA=";
    };
    date = "2025-01-20";
  };
}
