# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  tree-sitter-hypr = {
    pname = "tree-sitter-hypr";
    version = "d0441fd4b883ecc0e70140723a1cf5907992639a";
    src = fetchFromGitHub {
      owner = "luckasRanarison";
      repo = "tree-sitter-hypr";
      rev = "d0441fd4b883ecc0e70140723a1cf5907992639a";
      fetchSubmodules = false;
      sha256 = "sha256-pNAN5TF01Bnqfcsoa0IllchCCBph9/SowzIoMyQcN5w=";
    };
    date = "2025-05-09";
  };
}
