# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  dmenu-flexipatch = {
    pname = "dmenu-flexipatch";
    version = "5c1be5d667ac7094742228de85af4dbdc12706ef";
    src = fetchFromGitHub ({
      owner = "bakkeby";
      repo = "dmenu-flexipatch";
      rev = "5c1be5d667ac7094742228de85af4dbdc12706ef";
      fetchSubmodules = false;
      sha256 = "sha256-WD22+terfPhN73rDiv1J9D2N53hgTOJx9deMl+YkqHs=";
    });
  };
  dwm-flexipatch = {
    pname = "dwm-flexipatch";
    version = "54070d7e51aec3d35c19cd2fe855c861af2fc21b";
    src = fetchFromGitHub ({
      owner = "bakkeby";
      repo = "dwm-flexipatch";
      rev = "54070d7e51aec3d35c19cd2fe855c861af2fc21b";
      fetchSubmodules = false;
      sha256 = "sha256-xfINbL9WyzlJKkR3CyA1RxjJOcj+ih5m1NoZLaKtxYQ=";
    });
  };
  kiwmi = {
    pname = "kiwmi";
    version = "822e5b5063059ae169b7690c66484c65097e4cdd";
    src = fetchFromGitHub ({
      owner = "buffet";
      repo = "kiwmi";
      rev = "822e5b5063059ae169b7690c66484c65097e4cdd";
      fetchSubmodules = false;
      sha256 = "sha256-ZhPk95dMyA4ia2ChtJRUGMfe55zwC7Vi80glFWBXOPk=";
    });
  };
  kmonad = {
    pname = "kmonad";
    version = "f9df30991c1adfdcf4e4ef1623b9e716704e40eb";
    src = fetchFromGitHub ({
      owner = "kmonad";
      repo = "kmonad";
      rev = "f9df30991c1adfdcf4e4ef1623b9e716704e40eb";
      fetchSubmodules = false;
      sha256 = "sha256-OZCcqFhHqXa0nuZ1mpuUW970oaxvYtCZDvmgIIDs1Ec=";
    });
  };
  st-flexipatch = {
    pname = "st-flexipatch";
    version = "df36caf56bae629044249c4ee3a4468f6418606f";
    src = fetchFromGitHub ({
      owner = "bakkeby";
      repo = "st-flexipatch";
      rev = "df36caf56bae629044249c4ee3a4468f6418606f";
      fetchSubmodules = false;
      sha256 = "sha256-wpVVb1EHq3MUG/1SQxUMcDGrpQCstJWIlmB67gprWuw=";
    });
  };
  taffybar = {
    pname = "taffybar";
    version = "945a08452660de603193da8d297d559fdca497d1";
    src = fetchFromGitHub ({
      owner = "taffybar";
      repo = "taffybar";
      rev = "945a08452660de603193da8d297d559fdca497d1";
      fetchSubmodules = false;
      sha256 = "sha256-3H8sRK7qszYpVnX9o1UMCDUGTGtS+KLhyZ+Pu0h8EbY=";
    });
  };
  xmonad-entryhelper = {
    pname = "xmonad-entryhelper";
    version = "ee2d0c14f9258503d7bd62907aa731dd64fa34d0";
    src = fetchFromGitHub ({
      owner = "Javran";
      repo = "xmonad-entryhelper";
      rev = "ee2d0c14f9258503d7bd62907aa731dd64fa34d0";
      fetchSubmodules = false;
      sha256 = "sha256-CGaibR0Yejng9IQInm92Zx0pEZS29tJjWvPgaiWgUNQ=";
    });
  };
}
