# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  dmenu-flexipatch = {
    pname = "dmenu-flexipatch";
    version = "5c1be5d667ac7094742228de85af4dbdc12706ef";
    src = fetchFromGitHub ({
      owner = "bakkeby";
      repo = "dmenu-flexipatch";
      rev = "5c1be5d667ac7094742228de85af4dbdc12706ef";
      fetchSubmodules = false;
      sha256 = "sha256-WD22+terfPhN73rDiv1J9D2N53hgTOJx9deMl+YkqHs=";
    });
  };
  dwm-flexipatch = {
    pname = "dwm-flexipatch";
    version = "c553f93b528449ed2e7d4b424f063ef3c1d3d8f6";
    src = fetchFromGitHub ({
      owner = "bakkeby";
      repo = "dwm-flexipatch";
      rev = "c553f93b528449ed2e7d4b424f063ef3c1d3d8f6";
      fetchSubmodules = false;
      sha256 = "sha256-6aji4pxzpqyEU42oRlgK3jAQEPMihgxS+AUMWA9w5gA=";
    });
  };
  st-flexipatch = {
    pname = "st-flexipatch";
    version = "3e41e252b1f85babab0a6c8a3cf084a0e06831a2";
    src = fetchFromGitHub ({
      owner = "bakkeby";
      repo = "st-flexipatch";
      rev = "3e41e252b1f85babab0a6c8a3cf084a0e06831a2";
      fetchSubmodules = false;
      sha256 = "sha256-SIq+OhAEWcOH/CCaZhcSLkNgVOXYkYBwSSUFpeQi8bk=";
    });
  };
}
