# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  cantata = {
    pname = "cantata";
    version = "c8d035f4ecc738eef27ee3999dde101140fa4049";
    src = fetchgit {
      url = "https://github.com/nullobsi/cantata";
      rev = "c8d035f4ecc738eef27ee3999dde101140fa4049";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-tEmpGbwwFLjZW7XC8bGIovQB0xgPQL60rWiBKz7KFKc=";
    };
    date = "2025-04-24";
  };
}
