# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  cantata = {
    pname = "cantata";
    version = "v3.2.1";
    src = fetchFromGitHub {
      owner = "nullobsi";
      repo = "cantata";
      rev = "v3.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-H7+IuT9hDfFkHLLzlTzHy1XSPUmREQ88DEiJPWgxerw=";
    };
  };
}
