# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  cantata = {
    pname = "cantata";
    version = "8306905b613b6a9dacbac008dd822f09e4fd0b46";
    src = fetchgit {
      url = "https://github.com/nullobsi/cantata";
      rev = "8306905b613b6a9dacbac008dd822f09e4fd0b46";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-KXOb7SpTF1vAyDBFrSlYAAYICfugxwqVRZVz7Ed8gLI=";
    };
    date = "2025-04-24";
  };
}
