# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  beets-lyricsmanager = {
    pname = "beets-lyricsmanager";
    version = "v0.0.3";
    src = fetchFromGitHub {
      owner = "zytx";
      repo = "beets-lyrics-manager";
      rev = "v0.0.3";
      fetchSubmodules = false;
      sha256 = "sha256-8UP0UhmlOPfhwL5/GzAiHfsQ6Ogx2d4G2h8LeWgpImc=";
    };
  };
}
