# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cardinal = {
    pname = "cardinal";
    version = "53550324430858918a55c90ffb54b4bff4785981";
    src = fetchFromGitHub {
      owner = "DISTRHO";
      repo = "Cardinal";
      rev = "53550324430858918a55c90ffb54b4bff4785981";
      fetchSubmodules = true;
      sha256 = "sha256-ZFXxUSIgLsWnuAbM534tYwOkHOUIK3NvuEuM499XbA0=";
    };
    date = "2026-05-26";
  };
}
