# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  cardinal = {
    pname = "cardinal";
    version = "4b3b458ffaeec8e9459d3d97cd31cc60ae82192c";
    src = fetchFromGitHub {
      owner = "DISTRHO";
      repo = "Cardinal";
      rev = "4b3b458ffaeec8e9459d3d97cd31cc60ae82192c";
      fetchSubmodules = true;
      sha256 = "sha256-XuCjOgsnTCNF9jxhwDrcrJfycGu7UEAsN/Cn1+JKrms=";
    };
    date = "2024-03-01";
  };
}
