# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  cardinal = {
    pname = "cardinal";
    version = "c6e865d2450758bfc599ba764ff45545f3b16f1b";
    src = fetchFromGitHub {
      owner = "DISTRHO";
      repo = "Cardinal";
      rev = "c6e865d2450758bfc599ba764ff45545f3b16f1b";
      fetchSubmodules = true;
      sha256 = "sha256-CAuT1Gt+4nJYsgOWzCz0Crom/6G+o1HQe/GPDU793bs=";
    };
    date = "2024-10-05";
  };
}
