# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  charlatan = {
    pname = "charlatan";
    version = "3.3.1";
    src = fetchurl {
      url = "https://blaukraut.info/downloads/charlatan3_3.3.1_linux.zip";
      sha256 = "sha256-06JaHcwkUaYp65V7DWqHo2wh+csggEBM+AodmfO8wFI=";
    };
  };
}
