# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  charlatan = {
    pname = "charlatan";
    version = "3.3.0";
    src = fetchurl {
      url = "https://blaukraut.info/downloads/charlatan3_3.3.0_linux.zip";
      sha256 = "sha256-pdG0FKZY8D9qKfOx5sLcCo6LASd2D08pqfTeWSgnqg0=";
    };
  };
}
