# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  oneknob-series = {
    pname = "oneknob-series";
    version = "f5b53149f0e3577ea4664aa68041b42434773b12";
    src = fetchgit {
      url = "https://github.com/DISTRHO/OneKnob-Series";
      rev = "f5b53149f0e3577ea4664aa68041b42434773b12";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-RSGfAUwelmepFnC9exU0EUWNRTI7rIDxYIvn+AU72Ks=";
    };
    date = "2025-11-13";
  };
}
