# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  oneknob-series = {
    pname = "oneknob-series";
    version = "6733edfe5af0e1c08331beda3a4a02a20cf6c049";
    src = fetchgit {
      url = "https://github.com/DISTRHO/OneKnob-Series";
      rev = "6733edfe5af0e1c08331beda3a4a02a20cf6c049";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-/FcuCnuKPexKLmk8rzMzQ968EPdeZ88hlZVyk2pKr9w=";
    };
    date = "2025-09-17";
  };
}
