# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  morewaita = {
    pname = "morewaita";
    version = "4e1fb0519242405e8f4528b382403eecdd9d73f0";
    src = fetchgit {
      url = "https://github.com/somepaulo/MoreWaita";
      rev = "4e1fb0519242405e8f4528b382403eecdd9d73f0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Y719Rspkh5yKmbkDCvg4R7OTuKpoHenCDw7qWzd/ttY=";
    };
    date = "2026-04-11";
  };
}
