# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  morewaita = {
    pname = "morewaita";
    version = "17c578ac9ddaabdd56d07076752157eccc36354a";
    src = fetchgit {
      url = "https://github.com/somepaulo/MoreWaita";
      rev = "17c578ac9ddaabdd56d07076752157eccc36354a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-keyhwM4hs8XIrVzAUdL6bFsdWKlCZ9NHIQeHFLiaioM=";
    };
    date = "2025-12-01";
  };
}
