# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  morewaita = {
    pname = "morewaita";
    version = "33b08b85b062027d621f4463c42a3ada0d3d00b2";
    src = fetchgit {
      url = "https://github.com/somepaulo/MoreWaita";
      rev = "33b08b85b062027d621f4463c42a3ada0d3d00b2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Gi73Cn/FwI055Inodo8huHeaWGTy9IR3qPMbjAHBsPw=";
    };
    date = "2025-07-07";
  };
}
