[proton-cachyos]
src.github = "CachyOS/proton-cachyos"
fetch.url = "https://github.com/CachyOS/proton-cachyos/releases/download/$ver/proton-$ver-x86_64_v3.tar.xz"

[proton-sarek]
src.github = "pythonlover02/Proton-Sarek"
fetch.url = "https://github.com/pythonlover02/Proton-Sarek/releases/download/$ver/$ver.tar.gz"

[proton-sarek-async]
src.github = "pythonlover02/Proton-Sarek"
fetch.url = "https://github.com/pythonlover02/Proton-Sarek/releases/download/$ver/$ver-async.tar.gz"

[proton-ge]
src.github = "GloriousEggroll/proton-ge-custom"
fetch.url = "https://github.com/GloriousEggroll/proton-ge-custom/releases/download/$ver/$ver.tar.gz"
