# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  aporetic-nerd-font = {
    pname = "aporetic-nerd-font";
    version = "baf71c3d0a34da71685d52adf276afdbb745c663";
    src = fetchgit {
      url = "https://github.com/Echinoidea/Aporetic-Nerd-Font";
      rev = "baf71c3d0a34da71685d52adf276afdbb745c663";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-4aMMqP899KzgevB2/Y3zjxD8zByb3S7wMHpJb/hMd9M=";
    };
    date = "2025-05-31";
  };
}
