# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  resonarium-bin = {
    pname = "resonarium-bin";
    version = "0.1.0";
    src = fetchurl {
      url = "https://github.com/gabrielsoule/resonarium/releases/download/v0.1.0/Resonarium-Instrument-0.1.0-Linux.zip";
      sha256 = "sha256-qDJU90fEShT4LCrgEn/etCwy8mPgCjxXn8+CB1Hxuc0=";
    };
  };
  resonarium-effect-bin = {
    pname = "resonarium-effect-bin";
    version = "0.1.0";
    src = fetchurl {
      url = "https://github.com/gabrielsoule/resonarium/releases/download/v0.1.0/Resonarium-Effect-0.1.0-Linux.zip";
      sha256 = "sha256-GFos0HLM6CTU99DLB6e4OuySgODcZDdxheM+K2VHOUY=";
    };
  };
}
