# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  nu-plugin-file = {
    pname = "nu-plugin-file";
    version = "v0.27.0";
    src = fetchFromGitHub {
      owner = "fdncred";
      repo = "nu_plugin_file";
      rev = "v0.27.0";
      fetchSubmodules = false;
      sha256 = "sha256-TC5XlHSg4K+eJ5vu7Q1JAKPL7qTUfEWTP7CQY6wYzgg=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-TC5XlHSg4K+eJ5vu7Q1JAKPL7qTUfEWTP7CQY6wYzgg=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
}
