# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  nu-plugin-file = {
    pname = "nu-plugin-file";
    version = "v0.25.2";
    src = fetchFromGitHub {
      owner = "fdncred";
      repo = "nu_plugin_file";
      rev = "v0.25.2";
      fetchSubmodules = false;
      sha256 = "sha256-0mYd3uaFqZLSiOAy/dXRSjZNEaL2cgdYuwuEhPt0OHo=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-0mYd3uaFqZLSiOAy_dXRSjZNEaL2cgdYuwuEhPt0OHo=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
}
