[zlint-bin-x86_64-linux]
src.github = "DonIsaac/zlint"
fetch.url = "https://github.com/DonIsaac/zlint/releases/download/$ver/zlint-linux-x86_64"

[zlint-bin-aarch64-linux]
src.github = "DonIsaac/zlint"
fetch.url = "https://github.com/DonIsaac/zlint/releases/download/$ver/zlint-linux-aarch64"

[zlint-bin-x86_64-darwin]
src.github = "DonIsaac/zlint"
fetch.url = "https://github.com/DonIsaac/zlint/releases/download/$ver/zlint-macos-x86_64"

[zlint-bin-aarch64-darwin]
src.github = "DonIsaac/zlint"
fetch.url = "https://github.com/DonIsaac/zlint/releases/download/$ver/zlint-macos-aarch64"
