# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  destruqtor = {
    pname = "destruqtor";
    version = "release-49";
    src = fetchurl {
      url = "https://github.com/blepfx/dist/releases/download/release-49/destruqtor-x86_64-unknown-linux-gnu.zip";
      sha256 = "sha256-Gl9twVyEN0s/hl0NhQAvzj5NYjN3O96OOtUalEgqGXM=";
    };
  };
}
