# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  destruqtor = {
    pname = "destruqtor";
    version = "release-45";
    src = fetchurl {
      url = "https://github.com/blepfx/dist/releases/download/release-45/destruqtor-x86_64-unknown-linux-gnu.zip";
      sha256 = "sha256-dUs/jqoPjr1Td2UZHjTHM4gLC2OX+as/GMH6lElynhg=";
    };
  };
}
