# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  destruqtor = {
    pname = "destruqtor";
    version = "release-65";
    src = fetchurl {
      url = "https://github.com/blepfx/dist/releases/download/release-65/destruqtor-x86_64-unknown-linux-gnu.zip";
      sha256 = "sha256-89j+BUzxD2SFXUN76byNrNj6tRjjGD/HPJSyd9KyIvQ=";
    };
  };
}
