# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  partiels = {
    pname = "partiels";
    version = "2.0.9";
    src = fetchFromGitHub {
      owner = "Ircam-Partiels";
      repo = "Partiels";
      rev = "2.0.9";
      fetchSubmodules = true;
      sha256 = "sha256-QCow7bIdzNqVLaekjFDLGMVdp0yAmSvttUlPSZcQmVA=";
    };
  };
  vamp-plugin-sdk = {
    pname = "vamp-plugin-sdk";
    version = "d7ceb7d1d490674c93d334e5378108c4328e9e05";
    src = fetchgit {
      url = "https://github.com/vamp-plugins/vamp-plugin-sdk.git";
      rev = "d7ceb7d1d490674c93d334e5378108c4328e9e05";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-CCcjHIykhaplN12GZUp9Q0EAEy5YL6ih/C+qpQmlcIM=";
    };
  };
}
