# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  distrho-ports = {
    pname = "distrho-ports";
    version = "31afd943cfa93da7f0193b6db7ba275ff810e5a8";
    src = fetchFromGitHub {
      owner = "DISTRHO";
      repo = "DISTRHO-Ports";
      rev = "31afd943cfa93da7f0193b6db7ba275ff810e5a8";
      fetchSubmodules = true;
      sha256 = "sha256-dDRkcJe1MNfjnjktguVT9jOho7+VIRdabANjZ/F18uY=";
    };
    date = "2024-04-27";
  };
}
