# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  distrho-ports = {
    pname = "distrho-ports";
    version = "43330739392197cd1b3b0df23b194879ddf68f23";
    src = fetchFromGitHub {
      owner = "DISTRHO";
      repo = "DISTRHO-Ports";
      rev = "43330739392197cd1b3b0df23b194879ddf68f23";
      fetchSubmodules = true;
      sha256 = "sha256-r/hhk/WmREtUSlWhQeJbWWlefJKX3ji6S25LI8heT6Q=";
    };
    date = "2025-04-24";
  };
}
