# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  dmenu-flexipatch = {
    pname = "dmenu-flexipatch";
    version = "ce504573d0fba602678c79a650830ee74e9e35ca";
    src = fetchFromGitHub {
      owner = "bakkeby";
      repo = "dmenu-flexipatch";
      rev = "ce504573d0fba602678c79a650830ee74e9e35ca";
      fetchSubmodules = false;
      sha256 = "sha256-1PN/71sfu1LoFDxyDzG3JzSTqusbt18zrMG6Qbgucaw=";
    };
    date = "2026-02-18";
  };
}
