# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  dmenu-flexipatch = {
    pname = "dmenu-flexipatch";
    version = "9ff7289ffc07a29183aa5d63154ac6c29ccfc201";
    src = fetchFromGitHub {
      owner = "bakkeby";
      repo = "dmenu-flexipatch";
      rev = "9ff7289ffc07a29183aa5d63154ac6c29ccfc201";
      fetchSubmodules = false;
      sha256 = "sha256-kGqx84CmOi8YG2VxdtknhZMImsnScM+/sLgdEO2fLK0=";
    };
    date = "2025-12-05";
  };
}
