# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  dmenu-flexipatch = {
    pname = "dmenu-flexipatch";
    version = "20b0a054fb9a517987e187f298b821dab6e7114a";
    src = fetchFromGitHub {
      owner = "bakkeby";
      repo = "dmenu-flexipatch";
      rev = "20b0a054fb9a517987e187f298b821dab6e7114a";
      fetchSubmodules = false;
      sha256 = "sha256-SHxlcDLZCM1jPBolTx1EOuWM39+6yIyhiHhjxSGFGP4=";
    };
    date = "2026-02-03";
  };
}
