# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  kmonad = {
    pname = "kmonad";
    version = "356c69f45b8cbb3c875616c91892f8b28ce40c13";
    src = fetchFromGitHub {
      owner = "kmonad";
      repo = "kmonad";
      rev = "356c69f45b8cbb3c875616c91892f8b28ce40c13";
      fetchSubmodules = false;
      sha256 = "sha256-ns7btNiKU6+JViXt6k3g7iQp2Xyy0ZCi3wf59y3lS6s=";
    };
    date = "2025-02-19";
  };
  taffybar = {
    pname = "taffybar";
    version = "c4f92b56d69b44336e4344d629cc88f75b7f7953";
    src = fetchFromGitHub {
      owner = "taffybar";
      repo = "taffybar";
      rev = "c4f92b56d69b44336e4344d629cc88f75b7f7953";
      fetchSubmodules = false;
      sha256 = "sha256-0rfHN1g2upyLSIYJhvOapdH18uv/aCSpMknogjTrH8o=";
    };
    date = "2025-01-07";
  };
  xmonad-entryhelper = {
    pname = "xmonad-entryhelper";
    version = "ee2d0c14f9258503d7bd62907aa731dd64fa34d0";
    src = fetchFromGitHub {
      owner = "Javran";
      repo = "xmonad-entryhelper";
      rev = "ee2d0c14f9258503d7bd62907aa731dd64fa34d0";
      fetchSubmodules = false;
      sha256 = "sha256-CGaibR0Yejng9IQInm92Zx0pEZS29tJjWvPgaiWgUNQ=";
    };
    date = "2022-05-18";
  };
}
