# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  kmonad = {
    pname = "kmonad";
    version = "964ebcfc8ce2a3f0ae830fe72474452d5b92ce1e";
    src = fetchFromGitHub {
      owner = "kmonad";
      repo = "kmonad";
      rev = "964ebcfc8ce2a3f0ae830fe72474452d5b92ce1e";
      fetchSubmodules = false;
      sha256 = "sha256-3zqH3j31nBzYWm+8jYZ43lOc8co52X/Y4KZIeB7WoLM=";
    };
    date = "2025-02-17";
  };
  taffybar = {
    pname = "taffybar";
    version = "c4f92b56d69b44336e4344d629cc88f75b7f7953";
    src = fetchFromGitHub {
      owner = "taffybar";
      repo = "taffybar";
      rev = "c4f92b56d69b44336e4344d629cc88f75b7f7953";
      fetchSubmodules = false;
      sha256 = "sha256-0rfHN1g2upyLSIYJhvOapdH18uv/aCSpMknogjTrH8o=";
    };
    date = "2025-01-07";
  };
  xmonad-entryhelper = {
    pname = "xmonad-entryhelper";
    version = "ee2d0c14f9258503d7bd62907aa731dd64fa34d0";
    src = fetchFromGitHub {
      owner = "Javran";
      repo = "xmonad-entryhelper";
      rev = "ee2d0c14f9258503d7bd62907aa731dd64fa34d0";
      fetchSubmodules = false;
      sha256 = "sha256-CGaibR0Yejng9IQInm92Zx0pEZS29tJjWvPgaiWgUNQ=";
    };
    date = "2022-05-18";
  };
}
