# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  kmonad = {
    pname = "kmonad";
    version = "7467692244cae5a681f7df42718eab2561c0e076";
    src = fetchFromGitHub {
      owner = "kmonad";
      repo = "kmonad";
      rev = "7467692244cae5a681f7df42718eab2561c0e076";
      fetchSubmodules = false;
      sha256 = "sha256-+u0+NKv1uVQGFOtGKSa9RiJCG95GlnlkejlX2cLxUFQ=";
    };
    date = "2025-03-25";
  };
  taffybar = {
    pname = "taffybar";
    version = "f6110354b8c98361c99fb44ac3e007a4c9f3e44b";
    src = fetchFromGitHub {
      owner = "taffybar";
      repo = "taffybar";
      rev = "f6110354b8c98361c99fb44ac3e007a4c9f3e44b";
      fetchSubmodules = false;
      sha256 = "sha256-fAq6ikwU4vDAP/vuRYcttI8OU1316Omw4tGS9kUMaa4=";
    };
    date = "2025-03-05";
  };
  xmonad-entryhelper = {
    pname = "xmonad-entryhelper";
    version = "ee2d0c14f9258503d7bd62907aa731dd64fa34d0";
    src = fetchFromGitHub {
      owner = "Javran";
      repo = "xmonad-entryhelper";
      rev = "ee2d0c14f9258503d7bd62907aa731dd64fa34d0";
      fetchSubmodules = false;
      sha256 = "sha256-CGaibR0Yejng9IQInm92Zx0pEZS29tJjWvPgaiWgUNQ=";
    };
    date = "2022-05-18";
  };
}
