# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  helion-bin = {
    pname = "helion-bin";
    version = "0.9.9.0";
    src = fetchurl {
      url = "https://github.com/Helion-Engine/Helion/releases/download/0.9.9.0/Helion-0.9.9.0-linux-x64_AOT.zip";
      sha256 = "sha256-FPbiN43StBYHH9VzaR2x7w0weorTw7GZqKp4YaALzwg=";
    };
  };
}
