# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  helion-bin = {
    pname = "helion-bin";
    version = "0.9.6.0";
    src = fetchurl {
      url = "https://github.com/Helion-Engine/Helion/releases/download/0.9.6.0/Helion-0.9.6.0-linux-x64.zip";
      sha256 = "sha256-LBUIgqN6W2hqYC678887eXvkTBNiTdEsScwll2Ck5G4=";
    };
  };
}
