# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  raze = {
    pname = "raze";
    version = "1.10.2";
    src = fetchFromGitHub {
      owner = "ZDoom";
      repo = "Raze";
      rev = "1.10.2";
      fetchSubmodules = false;
      sha256 = "sha256-8kr+BLwfTQ0kx6TMqu1AUxiCgvwJd2urZqJ09FH48lo=";
    };
  };
  zmusic = {
    pname = "zmusic";
    version = "89f3d65734470fb7ec0c1e69f73a0cfcc88ed557";
    src = fetchgit {
      url = "https://github.com/ZDoom/ZMusic";
      rev = "89f3d65734470fb7ec0c1e69f73a0cfcc88ed557";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-rEE3MZLwqnvn5MqbSTCErbsGRjKMK8cC3wTJxtf8WaU=";
    };
    date = "2024-10-09";
  };
}
