# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  raze = {
    pname = "raze";
    version = "1.9.1";
    src = fetchFromGitHub {
      owner = "ZDoom";
      repo = "Raze";
      rev = "1.9.1";
      fetchSubmodules = false;
      sha256 = "sha256-lXBH2uLAV7wF/sO5t86EB8gwubWkpm56A6E42wJX68I=";
    };
  };
  zmusic = {
    pname = "zmusic";
    version = "b31b43efd0e92c8bff5501e95b31d9439642b711";
    src = fetchgit {
      url = "https://github.com/ZDoom/ZMusic";
      rev = "b31b43efd0e92c8bff5501e95b31d9439642b711";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-AkrqMb5PLO6D2UMsFVvxdNXNQKZvBDRMmAGkieTl6WU=";
    };
    date = "2024-04-03";
  };
}
