# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  yadaw-bin-aarch64 = {
    pname = "yadaw-bin-aarch64";
    version = "0.6.1";
    src = fetchTarball {
      url = "https://github.com/mlm-games/yadaw/releases/download/0.6.1/yadaw-0.6.1-aarch64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-BJ/6jFNcUaIDaK/6JeMWCmSnPF1ykRvGwYgcbVNxnOM=";
    };
  };
  yadaw-bin-x86_64 = {
    pname = "yadaw-bin-x86_64";
    version = "0.6.1";
    src = fetchTarball {
      url = "https://github.com/mlm-games/yadaw/releases/download/0.6.1/yadaw-0.6.1-x86_64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-wPKhpDgXhQ1YJAHP9ZmquyeeYUef4VgltOa42jiRbzE=";
    };
  };
}
