# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  yadaw-bin-aarch64 = {
    pname = "yadaw-bin-aarch64";
    version = "0.7.11";
    src = fetchTarball {
      url = "https://github.com/mlm-games/yadaw/releases/download/0.7.11/yadaw-0.7.11-aarch64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-RtJ2PbLK9bRbYnvKdN7BLja0p5+GUlPj8R6OKVsz4jA=";
    };
  };
  yadaw-bin-x86_64 = {
    pname = "yadaw-bin-x86_64";
    version = "0.7.11";
    src = fetchTarball {
      url = "https://github.com/mlm-games/yadaw/releases/download/0.7.11/yadaw-0.7.11-x86_64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-bS8Eov1d4upQc7ARpxXQ9cS0kvQbuvIax7nj7sDnpXk=";
    };
  };
}
