# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  k-whooms = {
    pname = "k-whooms";
    version = "2025.03";
    src = fetchurl {
      url = "https://www.hansen-audio.org/download/K-Whooms-2025.03-Linux.tar.gz";
      sha256 = "sha256-8tESW1GCgJgsQlkiX+P4qXRbizST8RUaqHvHx8FwgSQ=";
    };
  };
}
