# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  reev-r = {
    pname = "reev-r";
    version = "v1.3.1";
    src = fetchFromGitHub {
      owner = "tiagolr";
      repo = "reevr";
      rev = "v1.3.1";
      fetchSubmodules = true;
      sha256 = "sha256-ONzh3fDaMdRm5uAGZjYzAuQp9bEAhMfG5lhs0/awvl0=";
    };
  };
}
