# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  reev-r = {
    pname = "reev-r";
    version = "v1.1.0";
    src = fetchFromGitHub {
      owner = "tiagolr";
      repo = "reevr";
      rev = "v1.1.0";
      fetchSubmodules = true;
      sha256 = "sha256-2JGBDYyxXIGM+8/T6srGn81YbhhknAHKbVllz1jIwOY=";
    };
  };
}
