# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  reev-r = {
    pname = "reev-r";
    version = "v1.2.0";
    src = fetchFromGitHub {
      owner = "tiagolr";
      repo = "reevr";
      rev = "v1.2.0";
      fetchSubmodules = true;
      sha256 = "sha256-XN5gRRQf7UX5Y76DGSO1KXtcBuSA98HgCpy0v3fZ2hk=";
    };
  };
}
