# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  ircam-vamp-plugins-bin = {
    pname = "ircam-vamp-plugins-bin";
    version = "2.1.0";
    src = fetchurl {
      url = "https://github.com/Ircam-Partiels/ircam-vamp-plugins/releases/download/2.1.0/Ircam-Vamp-Plugins-Linux.zip";
      sha256 = "sha256-yeskOFda9duIjWxP1vB0t6tXIHlzza1st2u9Qciy770=";
    };
  };
}
