# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  zine-bin-aarch64-darwin = {
    pname = "zine-bin-aarch64-darwin";
    version = "v0.11.2";
    src = fetchurl {
      url = "https://github.com/kristoff-it/zine/releases/download/v0.11.2/aarch64-macos.zip";
      sha256 = "sha256-+zv3BlePbA4xIuXa8qsfL00QH2AG7Mcie7W71onYl74=";
    };
  };
  zine-bin-aarch64-linux = {
    pname = "zine-bin-aarch64-linux";
    version = "v0.11.2";
    src = fetchurl {
      url = "https://github.com/kristoff-it/zine/releases/download/v0.11.2/aarch64-linux-musl.tar.xz";
      sha256 = "sha256-lBOc2l5fjJ48cA0HdqQ0ws3u0VSMy/W6HyzhFM78YQI=";
    };
  };
  zine-bin-x86_64-darwin = {
    pname = "zine-bin-x86_64-darwin";
    version = "v0.11.2";
    src = fetchurl {
      url = "https://github.com/kristoff-it/zine/releases/download/v0.11.2/x86_64-macos.zip";
      sha256 = "sha256-c93nLJGjhRVr7CORxkNn86JVUUyb/41NYPosF5YoxgI=";
    };
  };
  zine-bin-x86_64-linux = {
    pname = "zine-bin-x86_64-linux";
    version = "v0.11.2";
    src = fetchurl {
      url = "https://github.com/kristoff-it/zine/releases/download/v0.11.2/x86_64-linux-musl.tar.xz";
      sha256 = "sha256-urP0fgfvuBJkKPgDXs9G5DNElltDCq5fiW1lp0f1wZw=";
    };
  };
}
