# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  zine-bin-aarch64-darwin = {
    pname = "zine-bin-aarch64-darwin";
    version = "v0.11.3";
    src = fetchurl {
      url = "https://github.com/kristoff-it/zine/releases/download/v0.11.3/aarch64-macos.zip";
      sha256 = "sha256-g2VuamLbPnAA1D4MToMMrdMOmAIoE2IARbPLRBIfyjs=";
    };
  };
  zine-bin-aarch64-linux = {
    pname = "zine-bin-aarch64-linux";
    version = "v0.11.3";
    src = fetchurl {
      url = "https://github.com/kristoff-it/zine/releases/download/v0.11.3/aarch64-linux-musl.tar.xz";
      sha256 = "sha256-ZYUauYgE9pO30+3RI+2cmhGMU1dKiyFC+TrVSXgq4/c=";
    };
  };
  zine-bin-x86_64-darwin = {
    pname = "zine-bin-x86_64-darwin";
    version = "v0.11.3";
    src = fetchurl {
      url = "https://github.com/kristoff-it/zine/releases/download/v0.11.3/x86_64-macos.zip";
      sha256 = "sha256-dNv5lVZ+sIPkTZa2SK/sxxtTud0rEQTmEaACOYHdvdo=";
    };
  };
  zine-bin-x86_64-linux = {
    pname = "zine-bin-x86_64-linux";
    version = "v0.11.3";
    src = fetchurl {
      url = "https://github.com/kristoff-it/zine/releases/download/v0.11.3/x86_64-linux-musl.tar.xz";
      sha256 = "sha256-wl5Tcril0nWfK35YGu+5DIAZ/wBWojCpfv48jtqzvBk=";
    };
  };
}
