# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  zine-bin-aarch64-darwin = {
    pname = "zine-bin-aarch64-darwin";
    version = "v0.12.0";
    src = fetchurl {
      url = "https://github.com/kristoff-it/zine/releases/download/v0.12.0/aarch64-macos.zip";
      sha256 = "sha256-ISe3uzq+wzZzhdaWOIdXV6l79QvWuiYAE0ppr/eknLc=";
    };
  };
  zine-bin-aarch64-linux = {
    pname = "zine-bin-aarch64-linux";
    version = "v0.12.0";
    src = fetchurl {
      url = "https://github.com/kristoff-it/zine/releases/download/v0.12.0/aarch64-linux-musl.tar.xz";
      sha256 = "sha256-rGhSCUPADDLRUuBuU/dw7LmUZGbMpb42j0udblRONrk=";
    };
  };
  zine-bin-x86_64-darwin = {
    pname = "zine-bin-x86_64-darwin";
    version = "v0.12.0";
    src = fetchurl {
      url = "https://github.com/kristoff-it/zine/releases/download/v0.12.0/x86_64-macos.zip";
      sha256 = "sha256-s0sIX+rlm3/4eWJBWz9oNK6syHrlt3BwFqVRyC56wxk=";
    };
  };
  zine-bin-x86_64-linux = {
    pname = "zine-bin-x86_64-linux";
    version = "v0.12.0";
    src = fetchurl {
      url = "https://github.com/kristoff-it/zine/releases/download/v0.12.0/x86_64-linux-musl.tar.xz";
      sha256 = "sha256-Cm1/6TjXwF6KghIFmd/WEpmk889e+2tMrkwlSd6ZctQ=";
    };
  };
}
