# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  umu = {
    pname = "umu";
    version = "3aee06109c30b1f8f3d4511566ef443bcb820fec";
    src = fetchgit {
      url = "https://github.com/Open-Wine-Components/umu-launcher";
      rev = "3aee06109c30b1f8f3d4511566ef443bcb820fec";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-qD1lz0DlJ/fb6dp3J0IH6m+x8MsG0GUKoqsHDUUS8GQ=";
    };
    date = "2024-11-23";
  };
}
