# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  umu = {
    pname = "umu";
    version = "4d1860eefd79d6c04e964774155dbe13be65121a";
    src = fetchgit {
      url = "https://github.com/Open-Wine-Components/umu-launcher";
      rev = "4d1860eefd79d6c04e964774155dbe13be65121a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sparseCheckout = [];
      sha256 = "sha256-9GrKo0/FD/tgo/cSf/Zm5LGWe2R5YpogUclbJJxDQqg=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./umu-4d1860eefd79d6c04e964774155dbe13be65121a/Cargo.lock;
      outputHashes = {
      };
    };
    date = "2025-01-25";
  };
}
