# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  serena = {
    pname = "serena";
    version = "v1.5.3";
    src = fetchFromGitHub {
      owner = "oraios";
      repo = "serena";
      rev = "v1.5.3";
      fetchSubmodules = false;
      sha256 = "sha256-8RHjJG8loqC742LoFK7O3MK7JDEhb1qw8VMBhzj04MM=";
    };
  };
}
