[element]
src.git = "https://gitlab.com/kushview/element.git"
fetch.git = "https://gitlab.com/kushview/element.git"
git.leaveDotGit = true

[juce-element]
src.git = "https://gitlab.com/kushview/juce"
src.branch = "element"
fetch.git = "https://gitlab.com/kushview/juce"

[lvtk]
src.manual = "7316c51a08609bcb7cb0bc33105dfe6319e6ff9f"
fetch.git = "https://github.com/lvtk/lvtk.git"
