[element]
src.git = "https://gitlab.com/kushview/element.git"
fetch.git = "https://gitlab.com/kushview/element.git"
git.leaveDotGit = true

[juce-element]
src.git = "https://gitlab.com/kushview/juce"
src.branch = "element"
fetch.git = "https://gitlab.com/kushview/juce"

[lvtk]
src.git = "https://github.com/lvtk/lvtk.git"
fetch.git = "https://github.com/lvtk/lvtk.git"

[clap]
src.manual = "1.2.3"
fetch.git = "https://github.com/free-audio/clap.git"

[clap-helpers]
src.git = "https://github.com/mfisher31/clap-helpers"
fetch.git = "https://github.com/mfisher31/clap-helpers"
src.branch = "meson-and-host-ext"

[lvtk-host]
src.git = "https://github.com/lvtk/lvtk-host.git"
fetch.git = "https://github.com/lvtk/lvtk-host.git"
