# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  juce = {
    pname = "juce";
    version = "8.0.1";
    src = fetchgit {
      url = "https://github.com/juce-framework/JUCE";
      rev = "8.0.1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-2Bx3QHRcYRPrnw2zZzwleUQ+Q1zOKr4bl8cmsT7vUNs=";
    };
  };
  ysfx = {
    pname = "ysfx";
    version = "v0.0.37";
    src = fetchFromGitHub {
      owner = "JoepVanlier";
      repo = "ysfx";
      rev = "v0.0.37";
      fetchSubmodules = true;
      sha256 = "sha256-yKIKx/Yt7X1OEGTylx4SDSthIxtP1I7daY6+2pRK46g=";
    };
  };
}
