# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  fastcrw = {
    pname = "fastcrw";
    version = "v0.16.0";
    src = fetchFromGitHub {
      owner = "us";
      repo = "crw";
      rev = "v0.16.0";
      fetchSubmodules = false;
      sha256 = "sha256-FtFmPhq6iHaLOfV7CC+B+DyntL4fYTnWAcZbWNk+c8k=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-FtFmPhq6iHaLOfV7CC+B+DyntL4fYTnWAcZbWNk+c8k=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
}
