# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  fastcrw = {
    pname = "fastcrw";
    version = "v0.31.0";
    src = fetchFromGitHub {
      owner = "us";
      repo = "crw";
      rev = "v0.31.0";
      fetchSubmodules = false;
      sha256 = "sha256-xHB7LibVrWjM+X23ImIJC8yBDy5lBb8XR7wn7hXJ9aA=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-xHB7LibVrWjM+X23ImIJC8yBDy5lBb8XR7wn7hXJ9aA=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
}
