# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  fastcrw = {
    pname = "fastcrw";
    version = "v0.15.2";
    src = fetchFromGitHub {
      owner = "us";
      repo = "crw";
      rev = "v0.15.2";
      fetchSubmodules = false;
      sha256 = "sha256-K9s7XkM1hZ+XeNjiYLg6B7dGtHMiN2ND2YADWa9P+JA=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-K9s7XkM1hZ+XeNjiYLg6B7dGtHMiN2ND2YADWa9P+JA=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
}
