# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  quetzalcoatl-bin = {
    pname = "quetzalcoatl-bin";
    version = "0.9.0";
    src = fetchurl {
      url = "https://github.com/publicsamples/Quetzalcoatl/releases/download/0.9.0/Quetzalcoatl.vst3.Linux.tar.xz";
      sha256 = "sha256-npSHwnqaiPjQMJjK+i0rW+cVeKuMp+LlGS2Zvpk5a+A=";
    };
  };
}
