# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  quetzalcoatl-bin = {
    pname = "quetzalcoatl-bin";
    version = "0.9.0";
    src = fetchurl {
      url = "https://github.com/publicsamples/Quetzalcoatl/releases/download/0.9.0/Quetzalcoatl.vst3.Linux.tar.xz";
      sha256 = "sha256-npSHwnqaiPjQMJjK+i0rW+cVeKuMp+LlGS2Zvpk5a+A=";
    };
  };
  quetzalcoatl-presets = {
    pname = "quetzalcoatl-presets";
    version = "0.9.0";
    src = fetchTarball {
      url = "https://github.com/publicsamples/Quetzalcoatl/releases/download/0.9.0/Quetzalcoatl_Presets_Wavetables.zip";
      sha256 = "sha256-FT9Few5C67BnE5U9iMjZDOv+fQ+9oVxqHEb4WRmdBuA=";
    };
  };
  quetzalcoatl-samples = {
    pname = "quetzalcoatl-samples";
    version = "0.9.0";
    src = fetchTarball {
      url = "https://github.com/publicsamples/Quetzalcoatl/releases/download/0.9.0/Quetzalcoatl_Samples.zip";
      sha256 = "sha256-F7oGkKVe7zAbRx9zZxKflE96G0rt5xQdap5cO99ozHs=";
    };
  };
}
