# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  molot-lite = {
    pname = "molot-lite";
    version = "1.1.0";
    src = fetchFromGitHub {
      owner = "magnetophon";
      repo = "molot-lite";
      rev = "1.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-0tmobsdCNon6udbkbQw7+EYQKBg2oaXlHIgNEf9U3XE=";
    };
  };
}
