# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  six-sines = {
    pname = "six-sines";
    version = "v1.1.0";
    src = fetchFromGitHub {
      owner = "baconpaul";
      repo = "six-sines";
      rev = "v1.1.0";
      fetchSubmodules = true;
      sha256 = "sha256-IQLGC86FqS3dptPzNpHEYKB59MWFDKsOPGM+FuzGcPo=";
    };
  };
  vst3sdk = {
    pname = "vst3sdk";
    version = "v3.7.6_build_18";
    src = fetchFromGitHub {
      owner = "steinbergmedia";
      repo = "vst3sdk";
      rev = "v3.7.6_build_18";
      fetchSubmodules = true;
      sha256 = "sha256-t/icDZairksROZmFOVFZ57s/9QSqTyijrhM7JmjYIlo=";
    };
  };
}
