# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  juce = {
    pname = "juce";
    version = "8.0.13";
    src = fetchFromGitHub {
      owner = "juce-framework";
      repo = "JUCE";
      rev = "8.0.13";
      fetchSubmodules = false;
      sha256 = "sha256-TKqW2rsFMAO1HJZ9IFQ7myOzNRScqR0gmLSLQA5Sw28=";
    };
  };
}
