# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  juce = {
    pname = "juce";
    version = "8.0.10";
    src = fetchFromGitHub {
      owner = "juce-framework";
      repo = "JUCE";
      rev = "8.0.10";
      fetchSubmodules = false;
      sha256 = "sha256-YSNVQ337/IAlz3mFNgJisIY5D9wPz6sFboMNwsjcGBo=";
    };
  };
}
