# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  winegui = {
    pname = "winegui";
    version = "v3.1.0";
    src = fetchFromGitHub {
      owner = "winegui";
      repo = "WineGUI";
      rev = "v3.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-Y/qdXG0LVcui6rqYYC6QKi2uL/GGZ7SwASmE0Mv9BLM=";
    };
  };
}
