# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  winegui = {
    pname = "winegui";
    version = "v4.2.0";
    src = fetchFromGitHub {
      owner = "winegui";
      repo = "WineGUI";
      rev = "v4.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-rnwmCmLD0dR0Egp+IoHSny1wc0Bq5RYVhxLiIrL1mQA=";
    };
  };
}
