# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  polarity-md = {
    pname = "polarity-md";
    version = "0.1.34";
    src = fetchurl {
      url = "https://polarity.productions/polarity-md/downloads/PolarityMD-v0.1.34-Linux.zip";
      sha256 = "sha256-eSIw2LrBbKdWk6xpGme1HHK2S/d4DmHdchIHeCb52ss=";
    };
  };
}
