# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  dsp56300 = {
    pname = "dsp56300";
    version = "2.0.0";
    src = fetchFromGitHub {
      owner = "dsp56300";
      repo = "gearmulator";
      rev = "2.0.0";
      fetchSubmodules = true;
      sha256 = "sha256-2JzomKCoJKaCA8RtxsheeaxqpT8Zql1N6qoSn/O73ho=";
    };
  };
}
