# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  dsp56300 = {
    pname = "dsp56300";
    version = "2.2.5";
    src = fetchFromGitHub {
      owner = "dsp56300";
      repo = "gearmulator";
      rev = "2.2.5";
      fetchSubmodules = true;
      sha256 = "sha256-YMHW4Fuq2RUh1DO148jynlWrzsE78FzlXLwY1rMll2M=";
    };
  };
}
