# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  dsp56300 = {
    pname = "dsp56300";
    version = "2.2.2";
    src = fetchFromGitHub {
      owner = "dsp56300";
      repo = "gearmulator";
      rev = "2.2.2";
      fetchSubmodules = true;
      sha256 = "sha256-2ByXbmR4SR5RhazAkJige1gTjdjyRkCbX9dH+PHYw7c=";
    };
  };
}
