[bassdrive]
fetch.url = "https://www.tonelib.net/download/ToneLib-BassDrive-amd64.deb"
src.webpage = "https://tonelib.net/downloads.html"
src.regex = 'BassDrive.+\n.+Version: (\d+.\d+.\d+)'

[easycomp]
fetch.url = "https://tonelib.net/download/ToneLib-EasyComp-amd64.deb"
src.webpage = "https://tonelib.net/downloads.html"
src.regex = 'EasyComp.+\n.+Version: (\d+.\d+.\d+)'

[noisereducer]
fetch.url = "https://www.tonelib.net/download/ToneLib-NoiseReducer-amd64.deb"
src.webpage = "https://tonelib.net/downloads.html"
src.regex = 'NoiseReducer.+\n.+Version: (\d+.\d+.\d+)'

[tubewarmth]
fetch.url = "https://www.tonelib.net/download/ToneLib-TubeWarmth-amd64.deb"
src.webpage = "https://tonelib.net/downloads.html"
src.regex = 'TubeWarmth.+\n.+Version: (\d+.\d+.\d+)'

[zoom]
fetch.url = "https://www.tonelib.net/download/ToneLib-Zoom-amd64.deb"
src.webpage = "https://tonelib.net/downloads.html"
src.regex = 'Zoom.+\n.+Version: (\d+.\d+.\d+)'
