# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  astal-lua = {
    pname = "astal-lua";
    version = "edb48def4ae02825a9ffb87711b072be47f8337f";
    src = fetchgit {
      url = "https://github.com/tokyob0t/astal-lua";
      rev = "edb48def4ae02825a9ffb87711b072be47f8337f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-wxyocEvjYNw30R7p6xFdubPzDoOiYZrm0S0f/k8kmGI=";
    };
    date = "2025-10-05";
  };
  bling = {
    pname = "bling";
    version = "bcfb671248cf9ff636b7fd7d7120d8ed9deaa395";
    src = fetchgit {
      url = "https://github.com/blingcorp/bling";
      rev = "bcfb671248cf9ff636b7fd7d7120d8ed9deaa395";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-rhhUsXQ3awjFiEHEG0axilSCWS6pR+w74K/pIfEUc5w=";
    };
    date = "2024-12-17";
  };
  lua-dbus = {
    pname = "lua-dbus";
    version = "cdef26d09aa61d7f1f175675040383f6ae0becbb";
    src = fetchgit {
      url = "https://github.com/dodo/lua-dbus";
      rev = "cdef26d09aa61d7f1f175675040383f6ae0becbb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-S+W6QTqv4kdyR86GCyDLnkml10dO4ZVNXEd3/7vDFGE=";
    };
    date = "2015-04-22";
  };
  lua-dbus_proxy = {
    pname = "lua-dbus_proxy";
    version = "986bf1a4dc481a753c812c6035d2277a149c9b2a";
    src = fetchgit {
      url = "https://github.com/stefano-m/lua-dbus_proxy";
      rev = "986bf1a4dc481a753c812c6035d2277a149c9b2a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-AeKYKaPYADWkufB9OicPNTrcm1mQfkuMI+7WKidppNw=";
    };
    date = "2024-10-04";
  };
}
