# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  sg-323 = {
    pname = "sg-323";
    version = "1.0.1";
    src = fetchFromGitHub {
      owner = "greyboxaudio";
      repo = "SG-323";
      rev = "1.0.1";
      fetchSubmodules = true;
      sha256 = "sha256-DvA9Y7eAG0pWLmHEZmJlo0JLU+0B4c8rlkX1bbVcnL8=";
    };
  };
}
