# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  sg-323 = {
    pname = "sg-323";
    version = "1.1.1";
    src = fetchFromGitHub {
      owner = "greyboxaudio";
      repo = "SG-323";
      rev = "1.1.1";
      fetchSubmodules = true;
      sha256 = "sha256-7zqIWLF9gcqHFg2LYauvF+6qUTIohYC5vZEn76siS7o=";
    };
  };
}
