# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  nugget-doom = {
    pname = "nugget-doom";
    version = "nugget-doom-4.2.0";
    src = fetchFromGitHub {
      owner = "MrAlaux";
      repo = "Nugget-Doom";
      rev = "nugget-doom-4.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-Ros31NPs0GKbAt2cI18Ue4uKPUh1e2vMjL7Wa0+YaHQ=";
    };
  };
}
