# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nugget-doom = {
    pname = "nugget-doom";
    version = "nugget-doom-4.1.0";
    src = fetchFromGitHub {
      owner = "MrAlaux";
      repo = "Nugget-Doom";
      rev = "nugget-doom-4.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-zvmFfQOzDX5ghSB0vr8hIATWbzEuH4yIAXKNC6q7y2s=";
    };
  };
}
