# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  nugget-doom = {
    pname = "nugget-doom";
    version = "nugget-doom-4.3.0";
    src = fetchFromGitHub {
      owner = "MrAlaux";
      repo = "Nugget-Doom";
      rev = "nugget-doom-4.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-T85UwCl75/RPOscfcRVlF3HhjlDVM2+W1L002UGNLZU=";
    };
  };
}
