# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  swift-mesonlsp-bin = {
    pname = "swift-mesonlsp-bin";
    version = "v3.1.4";
    src = fetchurl {
      url = "https://github.com/JCWasmx86/Swift-MesonLSP/releases/download/v3.1.4/Swift-MesonLSP.zip";
      sha256 = "sha256-Jdm8onZ8GPywVv0M0NIqoAkP9iVh1ebdtalpCdCoYtA=";
    };
  };
}
