# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  vgmtrans = {
    pname = "vgmtrans";
    version = "bcd511b9bf68f333ba9899fbd8954e17ecd47c7a";
    src = fetchgit {
      url = "https://github.com/vgmtrans/vgmtrans";
      rev = "bcd511b9bf68f333ba9899fbd8954e17ecd47c7a";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-lZxKNq5kjFf3fNOUVgC8k2eXJs7wgq4ena/UB7+kmd4=";
    };
    date = "2025-09-29";
  };
}
