# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  vgmtrans = {
    pname = "vgmtrans";
    version = "889073634ae010a43b2d6faba3d50d2afb4a80d0";
    src = fetchgit {
      url = "https://github.com/vgmtrans/vgmtrans";
      rev = "889073634ae010a43b2d6faba3d50d2afb4a80d0";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-7KIFWTPM6/fpA9/NNPDC+sgbzyKN536rX1uaRTGpIAU=";
    };
    date = "2026-02-21";
  };
}
