# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  filt-r = {
    pname = "filt-r";
    version = "v1.1.0";
    src = fetchFromGitHub {
      owner = "tiagolr";
      repo = "filtr";
      rev = "v1.1.0";
      fetchSubmodules = true;
      sha256 = "sha256-LRVwJ/Eh+XeNGnlbd2c56hWV8StHZGhxy0XLjGZ0toY=";
    };
  };
}
