# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  inshellah = {
    pname = "inshellah";
    version = "1897d1c3b2636b93ed4375b4a605b40b6656fee6";
    src = fetchFromGitHub {
      owner = "manic-systems";
      repo = "inshellah";
      rev = "1897d1c3b2636b93ed4375b4a605b40b6656fee6";
      fetchSubmodules = false;
      sha256 = "sha256-31eKu4dFki7vpWP62PZzDy3oTiPfhtxvduhTdFSYvPE=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-31eKu4dFki7vpWP62PZzDy3oTiPfhtxvduhTdFSYvPE=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2026-06-08";
  };
}
