# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  inshellah = {
    pname = "inshellah";
    version = "fd27ae9323301b5038f39506a043c39cc51ccaa7";
    src = fetchFromGitHub {
      owner = "manic-systems";
      repo = "inshellah";
      rev = "fd27ae9323301b5038f39506a043c39cc51ccaa7";
      fetchSubmodules = false;
      sha256 = "sha256-g9tgF7wGfoUvpRUq79JSsiODhd7pZOismfeqT+kTxY4=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-g9tgF7wGfoUvpRUq79JSsiODhd7pZOismfeqT+kTxY4=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2026-06-06";
  };
}
