# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  inshellah = {
    pname = "inshellah";
    version = "60963b2ac9072353ccdb7f721980e8b3206b6990";
    src = fetchFromGitHub {
      owner = "manic-systems";
      repo = "inshellah";
      rev = "60963b2ac9072353ccdb7f721980e8b3206b6990";
      fetchSubmodules = false;
      sha256 = "sha256-zO2UZTHci0QUziMw4Cs2w+lk70MBFPVcORCwJ1PvEVQ=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-zO2UZTHci0QUziMw4Cs2w+lk70MBFPVcORCwJ1PvEVQ=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2026-06-25";
  };
}
