# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  actuate = {
    pname = "actuate";
    version = "v1.4.2";
    src = fetchFromGitHub {
      owner = "ardura";
      repo = "Actuate";
      rev = "v1.4.2";
      fetchSubmodules = false;
      sha256 = "sha256-pg5vgjINpOhoxWjhWQWpfbOaQPkCRzRbQy3FSNUWChw=";
    };
  };
}
