# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  crunchrr = {
    pname = "crunchrr";
    version = "release-97";
    src = fetchurl {
      url = "https://github.com/blepfx/dist/releases/download/release-97/crunchrr-x86_64-unknown-linux-gnu.zip";
      sha256 = "sha256-3zBYbHCQc6t2Ro3vRg/y5jaqeoeGnwTGRUAozWbeHWc=";
    };
  };
  destruqtor = {
    pname = "destruqtor";
    version = "release-97";
    src = fetchurl {
      url = "https://github.com/blepfx/dist/releases/download/release-97/destruqtor-x86_64-unknown-linux-gnu.zip";
      sha256 = "sha256-4h6lrJHnAUuT4XyvlLkALugz8rLYmow0hG2HSb8BLdI=";
    };
  };
  filtrr = {
    pname = "filtrr";
    version = "release-97";
    src = fetchurl {
      url = "https://github.com/blepfx/dist/releases/download/release-97/filtrr-x86_64-unknown-linux-gnu.zip";
      sha256 = "sha256-VRKfhcN/3tb03GAwQ2C9LbBpc1M/7qw/DPF75DpwEMk=";
    };
  };
  prisma = {
    pname = "prisma";
    version = "release-97";
    src = fetchurl {
      url = "https://github.com/blepfx/dist/releases/download/release-97/prisma-x86_64-unknown-linux-gnu.zip";
      sha256 = "sha256-1DacKLL5kK2LzvQNFQKtXxgdN2/M+nVTULUzWw1HrhI=";
    };
  };
}
