# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  crunchrr = {
    pname = "crunchrr";
    version = "release-86";
    src = fetchurl {
      url = "https://github.com/blepfx/dist/releases/download/release-86/crunchrr-x86_64-unknown-linux-gnu.zip";
      sha256 = "sha256-ATS/ST1vzuT+f82YiQPjCj5KMNVl1QxccpUBHx7QLCs=";
    };
  };
  destruqtor = {
    pname = "destruqtor";
    version = "release-86";
    src = fetchurl {
      url = "https://github.com/blepfx/dist/releases/download/release-86/destruqtor-x86_64-unknown-linux-gnu.zip";
      sha256 = "sha256-toje9FekSxjoPD0PH8PoNyPym76Dw/P+E2Q8xTMYiJs=";
    };
  };
  filtrr = {
    pname = "filtrr";
    version = "release-86";
    src = fetchurl {
      url = "https://github.com/blepfx/dist/releases/download/release-86/filtrr-x86_64-unknown-linux-gnu.zip";
      sha256 = "sha256-1H2Rz9XyaBa+LOHVyjrsTxMbo9ayLOccwBZIjOlb8cw=";
    };
  };
  prisma = {
    pname = "prisma";
    version = "release-86";
    src = fetchurl {
      url = "https://github.com/blepfx/dist/releases/download/release-86/prisma-x86_64-unknown-linux-gnu.zip";
      sha256 = "sha256-XIBGAGiDHGIScS4H3tBNqtakVMNB/3QEJrEjZDHuGpM=";
    };
  };
}
