# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  crunchrr = {
    pname = "crunchrr";
    version = "release-94";
    src = fetchurl {
      url = "https://github.com/blepfx/dist/releases/download/release-94/crunchrr-x86_64-unknown-linux-gnu.zip";
      sha256 = "sha256-NKcN2hCgHKnc/oZmwyzMnWZOD6EbNtBfNGnYesF9Hd0=";
    };
  };
  destruqtor = {
    pname = "destruqtor";
    version = "release-94";
    src = fetchurl {
      url = "https://github.com/blepfx/dist/releases/download/release-94/destruqtor-x86_64-unknown-linux-gnu.zip";
      sha256 = "sha256-jX/rbi6RC4I1xkSzlWISI8CVUJT03RlwKYk4Y15vno4=";
    };
  };
  filtrr = {
    pname = "filtrr";
    version = "release-94";
    src = fetchurl {
      url = "https://github.com/blepfx/dist/releases/download/release-94/filtrr-x86_64-unknown-linux-gnu.zip";
      sha256 = "sha256-WYwtR6/fWUvT6arx8a9WCyKxUUq84Wm4cPrv0i+BaFE=";
    };
  };
  prisma = {
    pname = "prisma";
    version = "release-94";
    src = fetchurl {
      url = "https://github.com/blepfx/dist/releases/download/release-94/prisma-x86_64-unknown-linux-gnu.zip";
      sha256 = "sha256-jxzWsAdK4WY1NPlIiXioCW8tmudn+b3AN6Y7Yy4TYVU=";
    };
  };
}
