[six-sines]
src.github = "baconpaul/six-sines"
fetch.github = "baconpaul/six-sines"
git.fetchSubmodules = true

[vst3sdk]
src.manual = "v3.7.6_build_18"
fetch.github = "steinbergmedia/vst3sdk"
git.fetchSubmodules = true
