# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  nyan-doom = {
    pname = "nyan-doom";
    version = "v1.4.2";
    src = fetchFromGitHub {
      owner = "andrikpowell";
      repo = "nyan-doom";
      rev = "v1.4.2";
      fetchSubmodules = false;
      sha256 = "sha256-3tewNab2McgTbIP3J3ooa2AN/ik46EusIONyWEYC/IY=";
    };
  };
}
