# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  nyan-doom = {
    pname = "nyan-doom";
    version = "v1.2.2";
    src = fetchFromGitHub {
      owner = "andrikpowell";
      repo = "nyan-doom";
      rev = "v1.2.2";
      fetchSubmodules = false;
      sha256 = "sha256-+rhfo6rHGmlgunuJity5PfyK8+DPlFcmaOIdk4vTwGg=";
    };
  };
}
