# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  nyan-doom = {
    pname = "nyan-doom";
    version = "v1.5.0";
    src = fetchFromGitHub {
      owner = "andrikpowell";
      repo = "nyan-doom";
      rev = "v1.5.0";
      fetchSubmodules = false;
      sha256 = "sha256-y7u6lNdTmLCY2cK3SwskPGJGZxtV5R48545eQ6Lu9qY=";
    };
  };
}
