# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  chainner-bin = {
    pname = "chainner-bin";
    version = "0.24.1";
    src = fetchurl {
      url = "https://github.com/chaiNNer-org/chaiNNer/releases/download/v0.24.1/chaiNNer-linux-x64-0.24.1.zip";
      sha256 = "sha256-WwTkJtN8K3B39XfLHJBn0akGU8wcr4dolDMx9MekesE=";
    };
  };
}
