# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  chainner-bin-nightly = {
    pname = "chainner-bin-nightly";
    version = "2025-10-23";
    src = fetchurl {
      url = "https://github.com/chaiNNer-org/chaiNNer-nightly/releases/download/2025-10-23/chaiNNer-ubuntu-latest-nightly.2025-10-23.zip";
      sha256 = "sha256-hqiPJtam+5lflh5uY/OCMXvdNxAb+y85luJ2sZApkno=";
    };
  };
  chainner-bin-stable = {
    pname = "chainner-bin-stable";
    version = "0.25.1";
    src = fetchurl {
      url = "https://github.com/chaiNNer-org/chaiNNer/releases/download/v0.25.1/chaiNNer-linux-x64-0.25.1-portable.zip";
      sha256 = "sha256-BFl4S/C8veI/DV+ntesoUvAc3s1q8+LwFIEE3VuDyyU=";
    };
  };
}
