[yadaw-bin-x86_64]
src.github = "mlm-games/yadaw"
fetch.tarball = "https://github.com/mlm-games/yadaw/releases/download/$ver/yadaw-$ver-x86_64-unknown-linux-gnu.tar.gz"

[yadaw-bin-aarch64]
src.github = "mlm-games/yadaw"
fetch.tarball = "https://github.com/mlm-games/yadaw/releases/download/$ver/yadaw-$ver-aarch64-unknown-linux-gnu.tar.gz"
