# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  astal-niri = {
    pname = "astal-niri";
    version = "8ebaca7f913ea2c1af48a5adb424a0122d4a8cb1";
    src = fetchFromGitHub {
      owner = "sameoldlab";
      repo = "astal";
      rev = "8ebaca7f913ea2c1af48a5adb424a0122d4a8cb1";
      fetchSubmodules = false;
      sha256 = "sha256-4WAab6GmBTjpkm1I6vaWAiFdnuDCo7wMXLegGCXbuSs=";
    };
    date = "2025-12-10";
  };
}
