# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  cinelerra-gg = {
    pname = "cinelerra-gg";
    version = "20241231";
    src = fetchurl {
      url = "https://cinelerra-gg.org/download/images/CinGG-20241231-x86_64.AppImage";
      sha256 = "sha256-FQxmdhVoNiqCZTniYVy9WlRyOUiyNtBm+0FC8KT/ovo=";
    };
  };
}
