# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  js80p = {
    pname = "js80p";
    version = "v4.0.0";
    src = fetchFromGitHub {
      owner = "attilammagyar";
      repo = "js80p";
      rev = "v4.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-A36GvIoBUkmHlKSE6DDFD3B0AFUG8D5FAPqH4FHpCUE=";
    };
  };
}
