# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  js80p = {
    pname = "js80p";
    version = "v3.1.3";
    src = fetchFromGitHub {
      owner = "attilammagyar";
      repo = "js80p";
      rev = "v3.1.3";
      fetchSubmodules = false;
      sha256 = "sha256-Q2jVsFomTLU+0ofaWOwAIDGhnWsVNFugJ6cisybNFAg=";
    };
  };
}
