[valentine]
src.github = "tote-bag-labs/valentine"
fetch.github = "tote-bag-labs/valentine"
git.fetchSubmodules = true

[catch2]
src.manual = "v3.4.0"
fetch.git = "https://github.com/catchorg/Catch2.git"
