# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  just-a-sample-bin = {
    pname = "just-a-sample-bin";
    version = "v1.3-latest/JAS.Linux.VST3.v1.3.1";
    src = fetchurl {
      url = "https://github.com/BOBONA/Just-a-Sample/releases/download/v1.3-latest/JAS.Linux.VST3.v1.3.1.zip";
      sha256 = "sha256-XMxPjrV5lMlHKjs0tm7OTp2cGe2fbPgqij+eOJVuu5w=";
    };
  };
}
