# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  just-a-sample-bin = {
    pname = "just-a-sample-bin";
    version = "v1.02";
    src = fetchurl {
      url = "https://github.com/BOBONA/Just-a-Sample/releases/download/v1.02/Linux.VST3.zip";
      sha256 = "sha256-9JhioE5PnPhOKNrKj4PvUPOYIa1Pq2VfzayhvK1nKno=";
    };
  };
}
