# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  juce = {
    pname = "juce";
    version = "8.0.8";
    src = fetchFromGitHub {
      owner = "juce-framework";
      repo = "JUCE";
      rev = "8.0.8";
      fetchSubmodules = false;
      sha256 = "sha256-kp3rMaHWBbEh4UaRMxcLo/DiSJV942OY+LYxh6W7dFc=";
    };
  };
  perceptomap = {
    pname = "perceptomap";
    version = "v0.10";
    src = fetchFromGitHub {
      owner = "hqrrr";
      repo = "PerceptoMap";
      rev = "v0.10";
      fetchSubmodules = false;
      sha256 = "sha256-uh60O7RzSvdiHLPVYw/z74/VDtlAwlVTR20mRGt7YaU=";
    };
  };
}
