# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  octasine = {
    pname = "octasine";
    version = "v0.9.1";
    src = fetchurl {
      url = "https://github.com/greatest-ape/OctaSine/archive/v0.9.1.tar.gz";
      sha256 = "sha256-tn/mGdeZtCAJVjBO3TvH8BlSMZ/LGhHAEJZi6yPiT3U=";
    };
  };
}
