# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  git-pages-bin-aarch64-darwin = {
    pname = "git-pages-bin-aarch64-darwin";
    version = "v0.6.1";
    src = fetchurl {
      url = "https://codeberg.org/git-pages/git-pages/releases/download/v0.6.1/git-pages.darwin-arm64";
      sha256 = "sha256-G4qCnGLdHUlvCnOn9KEsO48Cl6rqb6AFI7YcuNFoPlU=";
    };
  };
  git-pages-bin-aarch64-linux = {
    pname = "git-pages-bin-aarch64-linux";
    version = "v0.6.1";
    src = fetchurl {
      url = "https://codeberg.org/git-pages/git-pages/releases/download/v0.6.1/git-pages.linux-arm64";
      sha256 = "sha256-/Ig3MXUNqPFX48vIJQSEMFpuZ6APxbIaDsktY8HpYDo=";
    };
  };
  git-pages-bin-x86_64-linux = {
    pname = "git-pages-bin-x86_64-linux";
    version = "v0.6.1";
    src = fetchurl {
      url = "https://codeberg.org/git-pages/git-pages/releases/download/v0.6.1/git-pages.linux-amd64";
      sha256 = "sha256-mvbsJ6OaMTzLCHiUuvNEdI4rLt0mcEaXnIAeadFrWCY=";
    };
  };
}
