# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  envtool-bin = {
    pname = "envtool-bin";
    version = "v1.4.2";
    src = fetchurl {
      url = "https://github.com/klknn/kdr/releases/download/v1.4.2/ubuntu-latest-envtool.zip";
      sha256 = "sha256-foXXDcAGmzAgnpndZ/pCaExJrl6I2EKxxyaW5oYfRh4=";
    };
  };
  epiano2-bin = {
    pname = "epiano2-bin";
    version = "v1.4.2";
    src = fetchurl {
      url = "https://github.com/klknn/kdr/releases/download/v1.4.2/ubuntu-latest-epiano2.zip";
      sha256 = "sha256-kJgsu9KTkVk2LD/NN3xgUG5C4YVRSNKPTBNSwbDfZTo=";
    };
  };
  freeverb-bin = {
    pname = "freeverb-bin";
    version = "v1.4.2";
    src = fetchurl {
      url = "https://github.com/klknn/kdr/releases/download/v1.4.2/ubuntu-latest-freeverb.zip";
      sha256 = "sha256-mJBVg9IW09izeKgMj1rr5LP+KqDowQguArh8IwmMw1Q=";
    };
  };
  synth2-bin = {
    pname = "synth2-bin";
    version = "v1.4.2";
    src = fetchurl {
      url = "https://github.com/klknn/kdr/releases/download/v1.4.2/ubuntu-latest-synth2.zip";
      sha256 = "sha256-HDtSoouLmCe++5Ly0UXPuiZoBs1+cqM0A/XW/7CaA/A=";
    };
  };
}
