# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  propertree = {
    pname = "propertree";
    version = "3a41fb514765d0cf89fc78fa79f3c90ad16f1738";
    src = fetchgit {
      url = "https://github.com/corpnewt/ProperTree";
      rev = "3a41fb514765d0cf89fc78fa79f3c90ad16f1738";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-uAwvRVPPXH78WI8g6dvwJSz/9u/5b3EpZHEL4xlvbeU=";
    };
    date = "2025-05-11";
  };
}
