# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  propertree = {
    pname = "propertree";
    version = "dcd1dcc46d848bd6f728a0c7483309c572e50ea3";
    src = fetchgit {
      url = "https://github.com/corpnewt/ProperTree";
      rev = "dcd1dcc46d848bd6f728a0c7483309c572e50ea3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-v9rFWzqD9VRTHQSj2GuoUpLa6Mf7G82DRb4N4XzIyCQ=";
    };
    date = "2024-10-27";
  };
}
