# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  propertree = {
    pname = "propertree";
    version = "1075ad49b17e0d2b28c132cac262af348b98c297";
    src = fetchgit {
      url = "https://github.com/corpnewt/ProperTree";
      rev = "1075ad49b17e0d2b28c132cac262af348b98c297";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-COlyNlplUkZpR3GhzaqMA4UyOqcd9mVzD7bZBD4nrHo=";
    };
    date = "2024-12-05";
  };
}
