[two-filters]
src.git = "https://github.com/baconpaul/two-filters"
fetch.git = "https://github.com/baconpaul/two-filters"
git.fetchSubmodules = true

[vst3sdk]
src.manual = "v3.7.6_build_18"
fetch.github = "steinbergmedia/vst3sdk"
git.fetchSubmodules = true
