# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  time-12 = {
    pname = "time-12";
    version = "v1.2.2";
    src = fetchFromGitHub {
      owner = "tiagolr";
      repo = "time12";
      rev = "v1.2.2";
      fetchSubmodules = true;
      sha256 = "sha256-kyh1IMiOykkSglpuJo2DnNOluUdO38Z25ONXh0mi400=";
    };
  };
}
