# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  time-12 = {
    pname = "time-12";
    version = "v1.1.8";
    src = fetchFromGitHub {
      owner = "tiagolr";
      repo = "time12";
      rev = "v1.1.8";
      fetchSubmodules = true;
      sha256 = "sha256-VPOYiHXjDJBoCLeViMHlboce9B/Jb9JZgczXfdeE9AM=";
    };
  };
}
