# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  tack = {
    pname = "tack";
    version = "v0.1.1";
    src = fetchFromGitHub {
      owner = "manic-systems";
      repo = "tack";
      rev = "v0.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-WUzhuU/LN5M491PQLn3LyTXbwbqDpLNHLNjvXpkleG8=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-WUzhuU_LN5M491PQLn3LyTXbwbqDpLNHLNjvXpkleG8=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
}
