# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  tack = {
    pname = "tack";
    version = "v1.0.0";
    src = fetchFromGitHub {
      owner = "manic-systems";
      repo = "tack";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-KhJb0NWLhj8AkD8uWEbXt179YlFLemk0OgOltw4jEk8=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-KhJb0NWLhj8AkD8uWEbXt179YlFLemk0OgOltw4jEk8=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
}
