# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  catch2 = {
    pname = "catch2";
    version = "v3.8.1";
    src = fetchFromGitHub {
      owner = "catchorg";
      repo = "Catch2";
      rev = "v3.8.1";
      fetchSubmodules = false;
      sha256 = "sha256-blhSdtNXwe4wKPVKlopsE0omgikMdl12JjwqASwJM2w=";
    };
  };
  punkott = {
    pname = "punkott";
    version = "12a7d865f69086c54cec36b3d820ee588558c0bd";
    src = fetchgit {
      url = "https://github.com/gmoican/PunkOTT.git";
      rev = "12a7d865f69086c54cec36b3d820ee588558c0bd";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-9qMiIJEYQUuMoUJynkL6gNluSJHpFXfavXkWxoT6ciY=";
    };
    date = "2025-12-26";
  };
}
