# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  catch2 = {
    pname = "catch2";
    version = "v3.8.1";
    src = fetchFromGitHub {
      owner = "catchorg";
      repo = "Catch2";
      rev = "v3.8.1";
      fetchSubmodules = false;
      sha256 = "sha256-blhSdtNXwe4wKPVKlopsE0omgikMdl12JjwqASwJM2w=";
    };
  };
  punkott = {
    pname = "punkott";
    version = "9e41e48e4194f58e8142c54d12ee9eb2e0e32002";
    src = fetchgit {
      url = "https://github.com/gmoican/PunkOTT.git";
      rev = "9e41e48e4194f58e8142c54d12ee9eb2e0e32002";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-J9F0Sa5tohFi4iqZjXJG923APwPiyDB7EZ9Dq/VR6hI=";
    };
    date = "2025-12-29";
  };
}
