# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  catch2-populate = {
    pname = "catch2-populate";
    version = "v3.8.1";
    src = fetchFromGitHub {
      owner = "catchorg";
      repo = "Catch2";
      rev = "v3.8.1";
      fetchSubmodules = false;
      sha256 = "sha256-blhSdtNXwe4wKPVKlopsE0omgikMdl12JjwqASwJM2w=";
    };
  };
  punkott = {
    pname = "punkott";
    version = "f1186796bbc91ba99da0b3b60f3b0c31d186ae1e";
    src = fetchgit {
      url = "https://github.com/gmoican/PunkOTT.git";
      rev = "f1186796bbc91ba99da0b3b60f3b0c31d186ae1e";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-u/dEcUJfwcDxP//jYA3Oh978ONwYvvL9hN4jYgBFcOE=";
    };
    date = "2025-12-19";
  };
}
