# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  geonkick = {
    pname = "geonkick";
    version = "v3.5.2";
    src = fetchFromGitHub {
      owner = "Geonkick-Synthesizer";
      repo = "geonkick";
      rev = "v3.5.2";
      fetchSubmodules = false;
      sha256 = "sha256-QtBzrYW/yYnWSXyHV63gKzgdAR5kamij9Z0g+15CTPg=";
    };
  };
}
