# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  darvaza = {
    pname = "darvaza";
    version = "1.0.3";
    src = fetchFromGitHub {
      owner = "igorski";
      repo = "darvaza";
      rev = "1.0.3";
      fetchSubmodules = false;
      sha256 = "sha256-NvPpTEBNGhz6fcbfJndRSWVcEbnTZafFxkFAGUMNy+Q=";
    };
  };
  delirion = {
    pname = "delirion";
    version = "1.1.0";
    src = fetchFromGitHub {
      owner = "igorski";
      repo = "delirion";
      rev = "1.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-w13DfRyIAcfG+DHLRfEV/qUygLWfQkyPcUAHYmklYyo=";
    };
  };
  fogpad = {
    pname = "fogpad";
    version = "1.0.3";
    src = fetchFromGitHub {
      owner = "igorski";
      repo = "fogpad";
      rev = "1.0.3";
      fetchSubmodules = false;
      sha256 = "sha256-viZldEegL8Jc1OKYo4fbmo/bc+mBMDCI8LfTVw5v2gs=";
    };
  };
  homecorrupter = {
    pname = "homecorrupter";
    version = "v1.1.3";
    src = fetchFromGitHub {
      owner = "igorski";
      repo = "homecorrupter";
      rev = "v1.1.3";
      fetchSubmodules = false;
      sha256 = "sha256-eGHyCQ0u3Xxr0x2KDGYtJYqVkrzhM7AGH4V/Gf8nYQg=";
    };
  };
  juce = {
    pname = "juce";
    version = "8.0.7";
    src = fetchFromGitHub {
      owner = "juce-framework";
      repo = "JUCE";
      rev = "8.0.7";
      fetchSubmodules = false;
      sha256 = "sha256-nl4pUSkUKqpMoehzq0MS5pjHpYDkrFpUsY8BwpQObCM=";
    };
  };
  rechoir = {
    pname = "rechoir";
    version = "1.0.0";
    src = fetchFromGitHub {
      owner = "igorski";
      repo = "rechoir";
      rev = "1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-khVKTGlhPuuBb51A/njcnGKNVMixDPUUsRIoMKGmyY0=";
    };
  };
  regrader = {
    pname = "regrader";
    version = "1.0.5";
    src = fetchFromGitHub {
      owner = "igorski";
      repo = "regrader";
      rev = "1.0.5";
      fetchSubmodules = false;
      sha256 = "sha256-tu1xfsnlc+55BdheF9y1N8OyeCrugGu+bHNg6tFK8Ys=";
    };
  };
  transformant = {
    pname = "transformant";
    version = "v1.0.4";
    src = fetchFromGitHub {
      owner = "igorski";
      repo = "transformant";
      rev = "v1.0.4";
      fetchSubmodules = false;
      sha256 = "sha256-W8quhA+W7pdT6DLGkI92Y+R270jzXM6yr5lizWJwydI=";
    };
  };
  vst3sdk = {
    pname = "vst3sdk";
    version = "v3.7.11_build_10";
    src = fetchFromGitHub {
      owner = "steinbergmedia";
      repo = "vst3sdk";
      rev = "v3.7.11_build_10";
      fetchSubmodules = true;
      sha256 = "sha256-DnWdMFT6i7C6jhqEpRHiNkg/WEgs0iLDVJWR2xgMxeM=";
    };
  };
  vstsid = {
    pname = "vstsid";
    version = "v1.1.2";
    src = fetchFromGitHub {
      owner = "igorski";
      repo = "VSTSID";
      rev = "v1.1.2";
      fetchSubmodules = false;
      sha256 = "sha256-pcX5CJsVJCa/E22B6GF2z3BIzfjkjbjVyZx7118qarU=";
    };
  };
}
