# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cade = {
    pname = "cade";
    version = "af37795a76b6c5080947e9e4a6ef216c230cbf7a";
    src = fetchFromGitHub {
      owner = "manic-systems";
      repo = "cade";
      rev = "af37795a76b6c5080947e9e4a6ef216c230cbf7a";
      fetchSubmodules = false;
      sha256 = "sha256-azVM8fRDhLYqpZycir47yNDEvb7XCJ96M0r4symB3zc=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-azVM8fRDhLYqpZycir47yNDEvb7XCJ96M0r4symB3zc=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2026-06-04";
  };
}
