# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cade = {
    pname = "cade";
    version = "d119b4f3d1199209f571b7bfdeebc0cf20c04ae6";
    src = fetchFromGitHub {
      owner = "manic-systems";
      repo = "cade";
      rev = "d119b4f3d1199209f571b7bfdeebc0cf20c04ae6";
      fetchSubmodules = false;
      sha256 = "sha256-7PKZV/3rH0SYioQUBWBVE2f4pJoqe4hbyrSLFRaH/e8=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-7PKZV_3rH0SYioQUBWBVE2f4pJoqe4hbyrSLFRaH_e8=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2026-08-16";
  };
}
