# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cade = {
    pname = "cade";
    version = "1497101e2e826f4a172bfc485edf1abfb15ce2bc";
    src = fetchFromGitHub {
      owner = "manic-systems";
      repo = "cade";
      rev = "1497101e2e826f4a172bfc485edf1abfb15ce2bc";
      fetchSubmodules = false;
      sha256 = "sha256-ExnFgjePOUeZwdwlkNbJLsUYVkD3q+7XdVIlubhxhgI=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-ExnFgjePOUeZwdwlkNbJLsUYVkD3q+7XdVIlubhxhgI=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2026-07-22";
  };
}
