# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  satty = {
    pname = "satty";
    version = "4824c262f8ac1c72f5537a7c93f2054323ce4e8b";
    src = fetchFromGitHub {
      owner = "gabm";
      repo = "Satty";
      rev = "4824c262f8ac1c72f5537a7c93f2054323ce4e8b";
      fetchSubmodules = false;
      sha256 = "sha256-oy56IDqXfr0xk77vTjEaeQy2w811WvS2OGGyPjPiNBY=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./satty-4824c262f8ac1c72f5537a7c93f2054323ce4e8b/Cargo.lock;
      outputHashes = {
      };
    };
    date = "2024-04-23";
  };
}
