# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  satty = {
    pname = "satty";
    version = "v0.17.0";
    src = fetchurl {
      url = "https://github.com/gabm/Satty/archive/v0.17.0.tar.gz";
      sha256 = "sha256-uYClQXjYsyQhM8pU4zVabXYnhswbG6AvSsKPKgEdLYw=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./satty-v0.17.0/Cargo.lock;
      outputHashes = {
      };
    };
  };
}
