# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  snyk-ls-bin-aarch64-darwin = {
    pname = "snyk-ls-bin-aarch64-darwin";
    version = "20241112.105448";
    src = fetchurl {
      url = "https://static.snyk.io/snyk-ls/16/snyk-ls_20241112.105448_darwin_arm64";
      sha256 = "sha256-WQo1UyO2kM1+U1xeN3F5UQlam3HBsKwztMV8oo59Uso=";
    };
  };
  snyk-ls-bin-aarch64-linux = {
    pname = "snyk-ls-bin-aarch64-linux";
    version = "20241112.105448";
    src = fetchurl {
      url = "https://static.snyk.io/snyk-ls/16/snyk-ls_20241112.105448_linux_arm64";
      sha256 = "sha256-sXDVL/KyUIOf4bfyfPZqIv5ntCX42AYjPh2NtVTiJrw=";
    };
  };
  snyk-ls-bin-i686-linux = {
    pname = "snyk-ls-bin-i686-linux";
    version = "20241112.105448";
    src = fetchurl {
      url = "https://static.snyk.io/snyk-ls/16/snyk-ls_20241112.105448_linux_386";
      sha256 = "sha256-OJFYkIBtOj8PbC+1fEm7xaZ9qNFER2ofTJF0WL+fRx8=";
    };
  };
  snyk-ls-bin-x86_64-darwin = {
    pname = "snyk-ls-bin-x86_64-darwin";
    version = "20241112.105448";
    src = fetchurl {
      url = "https://static.snyk.io/snyk-ls/16/snyk-ls_20241112.105448_darwin_amd64";
      sha256 = "sha256-878peGIlwKTgRF850NeLI1spdIvv7nmkP0MNe9TRnb0=";
    };
  };
  snyk-ls-bin-x86_64-linux = {
    pname = "snyk-ls-bin-x86_64-linux";
    version = "20241112.105448";
    src = fetchurl {
      url = "https://static.snyk.io/snyk-ls/16/snyk-ls_20241112.105448_linux_amd64";
      sha256 = "sha256-9onD6FX9xchGLKMAhp2jWepXntPtnpJ0ByOXfRFOcQg=";
    };
  };
}
