# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cloudreverb = {
    pname = "cloudreverb";
    version = "a0e4e41b152069d1446f3b90acd4c7ab9b42006c";
    src = fetchgit {
      url = "https://github.com/xunil-cloud/CloudReverb";
      rev = "a0e4e41b152069d1446f3b90acd4c7ab9b42006c";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-iNZguvdaJNVwmre10bBy50sEXhXb0lPdP6VqVkBhqIs=";
    };
    date = "2026-02-17";
  };
}
