# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cloudreverb = {
    pname = "cloudreverb";
    version = "56ba2071a1b53677a8d7d5adfaf07adbb0264b5b";
    src = fetchgit {
      url = "https://github.com/xunil-cloud/CloudReverb";
      rev = "56ba2071a1b53677a8d7d5adfaf07adbb0264b5b";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-KPi7n5/LMrOBIYiYfSlNZq4gP4fBLGE66e0oG2A64ak=";
    };
    date = "2025-06-28";
  };
}
