# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cloudreverb = {
    pname = "cloudreverb";
    version = "ef2d87aceced56d108d6e43d692c1d6e2948c527";
    src = fetchgit {
      url = "https://github.com/xunil-cloud/CloudReverb";
      rev = "ef2d87aceced56d108d6e43d692c1d6e2948c527";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-JOSJXASpdMdxp1pNSOzja9uynXCLj42O/N2V4/GPxjs=";
    };
    date = "2025-10-12";
  };
}
