# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  giada = {
    pname = "giada";
    version = "1.2.1";
    src = fetchFromGitHub {
      owner = "monocasual";
      repo = "giada";
      rev = "1.2.1";
      fetchSubmodules = true;
      sha256 = "sha256-mp+6MFwUqV6aa1ACdIlel5VhjWDXf5QzfFu1I6If4aU=";
    };
  };
}
