# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  giada = {
    pname = "giada";
    version = "1.2.0";
    src = fetchFromGitHub {
      owner = "monocasual";
      repo = "giada";
      rev = "1.2.0";
      fetchSubmodules = true;
      sha256 = "sha256-EKDqdv4/xsdT0X42n4HdH1fUYpJ79MfHaNpoO2c5VG8=";
    };
  };
}
