# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  giada = {
    pname = "giada";
    version = "1.1.1";
    src = fetchFromGitHub {
      owner = "monocasual";
      repo = "giada";
      rev = "1.1.1";
      fetchSubmodules = true;
      sha256 = "sha256-t24S8tmx9VFcpEwe5EzoMQ7xhX8dj92Mq43gaWc+C50=";
    };
  };
}
