# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  clap-juce-extensions = {
    pname = "clap-juce-extensions";
    version = "4d454e5125da75a0e75d95615cbec26d2a09e2bf";
    src = fetchgit {
      url = "https://github.com/free-audio/clap-juce-extensions";
      rev = "4d454e5125da75a0e75d95615cbec26d2a09e2bf";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-+i4w6NOImWkxNIOEKFN5houclbOmtgH6FNvGz+LHw9M=";
    };
    date = "2025-10-21";
  };
  juce = {
    pname = "juce";
    version = "7.0.12";
    src = fetchFromGitHub {
      owner = "juce-framework";
      repo = "JUCE";
      rev = "7.0.12";
      fetchSubmodules = false;
      sha256 = "sha256-/awe6D824ZjF17xjkt0wY7dcDuS/s8KKAv1UKHxF0FM=";
    };
  };
  unplugred = {
    pname = "unplugred";
    version = "fb3e5658fff67da38ea096cf1d7cdc8ac3d0cda3";
    src = fetchgit {
      url = "https://github.com/unplugred/vsts";
      rev = "fb3e5658fff67da38ea096cf1d7cdc8ac3d0cda3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-S8ODQMoAZldOhQ9GjzjGfjBcGT1Mm0k6VPV/fgpHxdU=";
    };
    date = "2025-11-15";
  };
}
