# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  clap-juce-extensions = {
    pname = "clap-juce-extensions";
    version = "ea834dfd366ab2103b98e92eaacb581c69fc2e0b";
    src = fetchgit {
      url = "https://github.com/free-audio/clap-juce-extensions";
      rev = "ea834dfd366ab2103b98e92eaacb581c69fc2e0b";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-hbelV7Bo1bKLjanoSHdOPedgNxvI7j2cHXM1bFaywmI=";
    };
    date = "2025-03-17";
  };
  juce = {
    pname = "juce";
    version = "7.0.12";
    src = fetchFromGitHub {
      owner = "juce-framework";
      repo = "JUCE";
      rev = "7.0.12";
      fetchSubmodules = false;
      sha256 = "sha256-/awe6D824ZjF17xjkt0wY7dcDuS/s8KKAv1UKHxF0FM=";
    };
  };
  unplugred = {
    pname = "unplugred";
    version = "f9d30ca5766f0f163b452bd5033be1fbbb4a083b";
    src = fetchgit {
      url = "https://github.com/unplugred/vsts";
      rev = "f9d30ca5766f0f163b452bd5033be1fbbb4a083b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-M24kOcLD/aCVGoq1vfmNUAXfs2UeweHOL+9FQOaAbUE=";
    };
    date = "2025-10-07";
  };
}
