# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  clap-juce-extensions = {
    pname = "clap-juce-extensions";
    version = "51a9359315298de632cf44e9d7524940868441e6";
    src = fetchFromGitHub {
      owner = "free-audio";
      repo = "clap-juce-extensions";
      rev = "51a9359315298de632cf44e9d7524940868441e6";
      fetchSubmodules = true;
      sha256 = "sha256-VJuWiw9wtFcBhDXvjwaEmbeFkZgZC5RYg8U+MXl53II=";
    };
    date = "2026-06-01";
  };
  juce = {
    pname = "juce";
    version = "7.0.12";
    src = fetchFromGitHub {
      owner = "juce-framework";
      repo = "JUCE";
      rev = "7.0.12";
      fetchSubmodules = false;
      sha256 = "sha256-/awe6D824ZjF17xjkt0wY7dcDuS/s8KKAv1UKHxF0FM=";
    };
  };
  unplugred = {
    pname = "unplugred";
    version = "fee1dbba04fda405f23111546cf140e7ce3f297c";
    src = fetchFromGitHub {
      owner = "unplugred";
      repo = "vsts";
      rev = "fee1dbba04fda405f23111546cf140e7ce3f297c";
      fetchSubmodules = false;
      sha256 = "sha256-m3xyLXpVq46ak6GbteSczPVY6VwVz8cEFYWh1X0zDCo=";
    };
    date = "2026-06-02";
  };
}
