# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  roomreverb = {
    pname = "roomreverb";
    version = "v1.3.0";
    src = fetchFromGitHub {
      owner = "cvde";
      repo = "RoomReverb";
      rev = "v1.3.0";
      fetchSubmodules = true;
      sha256 = "sha256-GAyJLKixXb948XHhrmOoXZ7tZ2swn9sI3CSgB7fe3BU=";
    };
  };
}
