# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  carla-git = {
    pname = "carla-git";
    version = "e312817b6f3d95e928dfde119934e7657092e7cc";
    src = fetchgit {
      url = "https://github.com/falkTX/Carla";
      rev = "e312817b6f3d95e928dfde119934e7657092e7cc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-jznejvHl6+L0IHmbfSEkdk5vxWbueN9BVa+xl1NQQ4c=";
    };
    date = "2024-10-01";
  };
  zrythm = {
    pname = "zrythm";
    version = "6ce35f2de52f55342f0d05157cc5dc571310670c";
    src = fetchgit {
      url = "https://gitlab.zrythm.org/zrythm/zrythm.git";
      rev = "6ce35f2de52f55342f0d05157cc5dc571310670c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-+kWiyX6ZPmmHzDqHFL/ucaLIWeuoqtZHMCrZ+ugVtho=";
    };
    date = "2024-10-03";
  };
}
