# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  carla-git = {
    pname = "carla-git";
    version = "862c1ec129111f25a3af972851f8adb0a102b521";
    src = fetchFromGitHub {
      owner = "falkTX";
      repo = "Carla";
      rev = "862c1ec129111f25a3af972851f8adb0a102b521";
      fetchSubmodules = false;
      sha256 = "sha256-H1+THBLD4lKXDVfT+u/lS+bzMVKbPdNG90ZAynd1Opg=";
    };
    date = "2024-04-16";
  };
  gtk-4_14_0 = {
    pname = "gtk-4_14_0";
    version = "4.14.0";
    src = fetchFromGitHub {
      owner = "GNOME";
      repo = "gtk";
      rev = "4.14.0";
      fetchSubmodules = false;
      sha256 = "sha256-4iXmGCnRpCzOK/UMsxlVlLFpdM0xP7NwzlW92/vxjuY=";
    };
  };
  libadwaita-1_5 = {
    pname = "libadwaita-1_5";
    version = "1.5.0";
    src = fetchFromGitHub {
      owner = "GNOME";
      repo = "libadwaita";
      rev = "1.5.0";
      fetchSubmodules = false;
      sha256 = "sha256-uEaBI2jHlMdVprMGRZe/8HszO3nEBUJaJtvJjrMOjE4=";
    };
  };
  rtaudio-git = {
    pname = "rtaudio-git";
    version = "6.0.1";
    src = fetchFromGitHub {
      owner = "thestk";
      repo = "rtaudio";
      rev = "6.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-Acsxbnl+V+Y4mKC1gD11n0m03E96HMK+oEY/YV7rlIY=";
    };
  };
  zrythm = {
    pname = "zrythm";
    version = "f9dd197bd773d816ee7f5a871b62e535287294b5";
    src = fetchgit {
      url = "https://gitlab.zrythm.org/zrythm/zrythm.git";
      rev = "f9dd197bd773d816ee7f5a871b62e535287294b5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-PoBIIaydKpx1Kua0/4HK5lU9yyGGa+Rqw3Vm6WJlHa4=";
    };
    date = "2024-04-16";
  };
}
