# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  vkdoom = {
    pname = "vkdoom";
    version = "b68c7545cdd7086a1e633e4810ac3ff2d8a1113d";
    src = fetchgit {
      url = "https://github.com/dpjudas/VkDoom";
      rev = "b68c7545cdd7086a1e633e4810ac3ff2d8a1113d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sparseCheckout = [];
      sha256 = "sha256-SN5occgA1z0uPoH4qJ53eMGp+tcuf/SrsNmmChHmvQY=";
    };
    date = "2025-01-21";
  };
}
