# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  vkdoom = {
    pname = "vkdoom";
    version = "b04ded680c9c7d01a6be16105615411ad4e6aae9";
    src = fetchgit {
      url = "https://github.com/dpjudas/VkDoom";
      rev = "b04ded680c9c7d01a6be16105615411ad4e6aae9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sparseCheckout = [];
      sha256 = "sha256-C4HVT14dldgovfKF4kipzdvTLPN87MAmPg9z2Gdkrto=";
    };
    date = "2025-01-29";
  };
}
