# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  chorusexmachina-bin = {
    pname = "chorusexmachina-bin";
    version = "v1.2";
    src = fetchurl {
      url = "https://github.com/peastman/ChorusExMachina/releases/download/v1.2/chorus_ex_machina-linux-x86.zip";
      sha256 = "sha256-5pbOuYqIAvugmr2D3gSX/nFjCxam+OS6FlcC4vfeJHM=";
    };
  };
}
