# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  keepmenu = {
    pname = "keepmenu";
    version = "cc35779b3cbc14588ce25fa9b768b1a97f0eae3b";
    src = fetchFromGitHub {
      owner = "firecat53";
      repo = "keepmenu";
      rev = "cc35779b3cbc14588ce25fa9b768b1a97f0eae3b";
      fetchSubmodules = false;
      sha256 = "sha256-ASbDjIb294IRmBwGfhNnAHMGzs09d6NoJVZTCPUFEiU=";
    };
    date = "2025-04-08";
  };
}
