# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  keepmenu = {
    pname = "keepmenu";
    version = "43970a3c6156601912a26f5b3d4e64dbc956a6d9";
    src = fetchFromGitHub {
      owner = "firecat53";
      repo = "keepmenu";
      rev = "43970a3c6156601912a26f5b3d4e64dbc956a6d9";
      fetchSubmodules = false;
      sha256 = "sha256-TGSyXkGEo7eybggiofEBe1K9QUISiauff/2iU15wSws=";
    };
    date = "2026-01-11";
  };
}
