# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  keepmenu = {
    pname = "keepmenu";
    version = "9fd3c0cd832a9cf41bc61bf9880e746b44731476";
    src = fetchFromGitHub {
      owner = "firecat53";
      repo = "keepmenu";
      rev = "9fd3c0cd832a9cf41bc61bf9880e746b44731476";
      fetchSubmodules = false;
      sha256 = "sha256-7y3sl+V1pmJVHhFjtLl0FVaemuHObG8O3Yg1D3vWByk=";
    };
    date = "2026-02-05";
  };
}
