# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  absorb = {
    pname = "absorb";
    version = "dc340430494213db40c67a04e9796b0462e61363";
    src = fetchgit {
      url = "https://github.com/Mrugalla/Absorb";
      rev = "dc340430494213db40c67a04e9796b0462e61363";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-+nU0+QJ730mVnbqavJCzvTEs1555S0+gYVW+3rhmN2c=";
    };
    date = "2025-09-12";
  };
  adsr = {
    pname = "adsr";
    version = "428545e2840abc6fd2e22cb8046df1be862c3aa5";
    src = fetchgit {
      url = "https://github.com/Mrugalla/ADSR";
      rev = "428545e2840abc6fd2e22cb8046df1be862c3aa5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-MBepbiyjPci51k5g0SuDGe4jJgs/bIJgHvnG0LzC6HU=";
    };
    date = "2025-09-15";
  };
  allhaas = {
    pname = "allhaas";
    version = "1c897e3ed25c37b6b64a093c42d2363d4b23189f";
    src = fetchgit {
      url = "https://github.com/Mrugalla/ALLHaas";
      rev = "1c897e3ed25c37b6b64a093c42d2363d4b23189f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-0YnO0QNiPYFdcw22dVbOyFZlwOLq1orWrEVF7kmk9lE=";
    };
    date = "2025-09-12";
  };
  hammer-and-meiszel = {
    pname = "hammer-and-meiszel";
    version = "8ab4654287809054a6e28a17c8d6bb4584f9f284";
    src = fetchgit {
      url = "https://github.com/Mrugalla/Hammer-and-Meiszel";
      rev = "8ab4654287809054a6e28a17c8d6bb4584f9f284";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-1tY/vGJnpxs+DVyALIZ6gja4/MhNXkLZLRFSgsaepXk=";
    };
    date = "2025-10-10";
  };
  jif = {
    pname = "jif";
    version = "d82e0283684b494630b2fee2c3d976f491a68f3e";
    src = fetchgit {
      url = "https://github.com/Mrugalla/JIF";
      rev = "d82e0283684b494630b2fee2c3d976f491a68f3e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-nAP8ru38FG/vUoFFVgXNZZ8i/5JhmamDMFV4flAoUYw=";
    };
    date = "2025-09-15";
  };
  manta = {
    pname = "manta";
    version = "57a76552853dc3d49341497cd61257f9ed6e81d0";
    src = fetchgit {
      url = "https://github.com/Mrugalla/Manta";
      rev = "57a76552853dc3d49341497cd61257f9ed6e81d0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Gclqi3u2W1afOXJdlfLCFLZ5Yfb0jy1cAyy427n0wSw=";
    };
    date = "2024-11-02";
  };
  nel-19 = {
    pname = "nel-19";
    version = "eb112420eb8547c419ffd1fe5f66672bb600fe47";
    src = fetchgit {
      url = "https://github.com/Mrugalla/NEL-19";
      rev = "eb112420eb8547c419ffd1fe5f66672bb600fe47";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-+6C54F57BPplWcu8DN8bCzHP9KFeWcUYTA6Y9MP/qwc=";
    };
    date = "2024-09-08";
  };
  nelorbit = {
    pname = "nelorbit";
    version = "9fd3eb30351216e400e09c9e322242a059f0355c";
    src = fetchgit {
      url = "https://github.com/Mrugalla/NELOrbit";
      rev = "9fd3eb30351216e400e09c9e322242a059f0355c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-1HlCuO8r0M5UUvF1ZNYXv68MhMy1a/+0Sp4keOl8so4=";
    };
    date = "2025-09-12";
  };
  overdrive-reneo = {
    pname = "overdrive-reneo";
    version = "a7ab76e2915a0e68f2e6946d8389ad6e308643ac";
    src = fetchgit {
      url = "https://github.com/Mrugalla/Overdrive-ReNEO";
      rev = "a7ab76e2915a0e68f2e6946d8389ad6e308643ac";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-UjimeLAxXVFKhClAuirM34xLHzL5FbORUuqiUeH9q38=";
    };
    date = "2025-09-15";
  };
  perlinnoisemod = {
    pname = "perlinnoisemod";
    version = "5951a7f8ca94045e09ebbe2757c4a15a91595c46";
    src = fetchgit {
      url = "https://github.com/Mrugalla/PerlinNoiseMod";
      rev = "5951a7f8ca94045e09ebbe2757c4a15a91595c46";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-0g9l8nJyt+JHzp9TJIiTkF3Axfz6Jk/sJDp96WKcNFM=";
    };
    date = "2025-09-15";
  };
  pitchglitcher = {
    pname = "pitchglitcher";
    version = "1c95571b5548f1f0aa7283ebacedb2bdf07c0431";
    src = fetchgit {
      url = "https://github.com/Mrugalla/PitchGlitcher";
      rev = "1c95571b5548f1f0aa7283ebacedb2bdf07c0431";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-o4p2ZqNPOWiP2tTEShFE3fUhzJXZ5BFxKjI7ulN2t2k=";
    };
    date = "2025-09-15";
  };
  slew-over = {
    pname = "slew-over";
    version = "c1d8e253931a10acb7c221960dfa760db964cedd";
    src = fetchgit {
      url = "https://github.com/Mrugalla/Slew-Over";
      rev = "c1d8e253931a10acb7c221960dfa760db964cedd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-co/SwY0PLH1zgpk5qI9Y94/M62r+Rr7tNl0XQpKlaeU=";
    };
    date = "2025-09-12";
  };
  susquash = {
    pname = "susquash";
    version = "3af376db597195005b655c708483ccce8be49c5f";
    src = fetchgit {
      url = "https://github.com/Mrugalla/susquash";
      rev = "3af376db597195005b655c708483ccce8be49c5f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-4t4xJWaYuqfxvSXOGL73JWbyqfr8a4/FT51u7cg0oUs=";
    };
    date = "2025-09-15";
  };
  xen = {
    pname = "xen";
    version = "6a91348f365bd12c46c1a286679f9a6c844fa16d";
    src = fetchgit {
      url = "https://github.com/Mrugalla/Xen";
      rev = "6a91348f365bd12c46c1a286679f9a6c844fa16d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-/JwXdp2B2YXbFbYzC2mqeP+mp2rMy7r98tQRp+iocbs=";
    };
    date = "2025-11-05";
  };
}
