# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  hammer-and-meiszel = {
    pname = "hammer-and-meiszel";
    version = "c9de84a00c7386f9b6c8e17af8bd7a38fd1e9054";
    src = fetchgit {
      url = "https://github.com/Mrugalla/Hammer-and-Meiszel";
      rev = "c9de84a00c7386f9b6c8e17af8bd7a38fd1e9054";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-jVC8g5/iLSjP7CCmKwRNnw2eKIN7UfE7KmpzATzUljQ=";
    };
    date = "2025-04-29";
  };
  manta = {
    pname = "manta";
    version = "57a76552853dc3d49341497cd61257f9ed6e81d0";
    src = fetchgit {
      url = "https://github.com/Mrugalla/Manta";
      rev = "57a76552853dc3d49341497cd61257f9ed6e81d0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Gclqi3u2W1afOXJdlfLCFLZ5Yfb0jy1cAyy427n0wSw=";
    };
    date = "2024-11-02";
  };
  nel-19 = {
    pname = "nel-19";
    version = "eb112420eb8547c419ffd1fe5f66672bb600fe47";
    src = fetchgit {
      url = "https://github.com/Mrugalla/NEL-19";
      rev = "eb112420eb8547c419ffd1fe5f66672bb600fe47";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-+6C54F57BPplWcu8DN8bCzHP9KFeWcUYTA6Y9MP/qwc=";
    };
    date = "2024-09-08";
  };
}
