# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  absorb = {
    pname = "absorb";
    version = "dc340430494213db40c67a04e9796b0462e61363";
    src = fetchgit {
      url = "https://github.com/Mrugalla/Absorb";
      rev = "dc340430494213db40c67a04e9796b0462e61363";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-+nU0+QJ730mVnbqavJCzvTEs1555S0+gYVW+3rhmN2c=";
    };
    date = "2025-09-12";
  };
  allhaas = {
    pname = "allhaas";
    version = "1c897e3ed25c37b6b64a093c42d2363d4b23189f";
    src = fetchgit {
      url = "https://github.com/Mrugalla/ALLHaas";
      rev = "1c897e3ed25c37b6b64a093c42d2363d4b23189f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-0YnO0QNiPYFdcw22dVbOyFZlwOLq1orWrEVF7kmk9lE=";
    };
    date = "2025-09-12";
  };
  hammer-and-meiszel = {
    pname = "hammer-and-meiszel";
    version = "c9de84a00c7386f9b6c8e17af8bd7a38fd1e9054";
    src = fetchgit {
      url = "https://github.com/Mrugalla/Hammer-and-Meiszel";
      rev = "c9de84a00c7386f9b6c8e17af8bd7a38fd1e9054";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-jVC8g5/iLSjP7CCmKwRNnw2eKIN7UfE7KmpzATzUljQ=";
    };
    date = "2025-04-29";
  };
  manta = {
    pname = "manta";
    version = "57a76552853dc3d49341497cd61257f9ed6e81d0";
    src = fetchgit {
      url = "https://github.com/Mrugalla/Manta";
      rev = "57a76552853dc3d49341497cd61257f9ed6e81d0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Gclqi3u2W1afOXJdlfLCFLZ5Yfb0jy1cAyy427n0wSw=";
    };
    date = "2024-11-02";
  };
  nel-19 = {
    pname = "nel-19";
    version = "eb112420eb8547c419ffd1fe5f66672bb600fe47";
    src = fetchgit {
      url = "https://github.com/Mrugalla/NEL-19";
      rev = "eb112420eb8547c419ffd1fe5f66672bb600fe47";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-+6C54F57BPplWcu8DN8bCzHP9KFeWcUYTA6Y9MP/qwc=";
    };
    date = "2024-09-08";
  };
  nelorbit = {
    pname = "nelorbit";
    version = "9fd3eb30351216e400e09c9e322242a059f0355c";
    src = fetchgit {
      url = "https://github.com/Mrugalla/NELOrbit";
      rev = "9fd3eb30351216e400e09c9e322242a059f0355c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-1HlCuO8r0M5UUvF1ZNYXv68MhMy1a/+0Sp4keOl8so4=";
    };
    date = "2025-09-12";
  };
  slew-over = {
    pname = "slew-over";
    version = "c1d8e253931a10acb7c221960dfa760db964cedd";
    src = fetchgit {
      url = "https://github.com/Mrugalla/Slew-Over";
      rev = "c1d8e253931a10acb7c221960dfa760db964cedd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-co/SwY0PLH1zgpk5qI9Y94/M62r+Rr7tNl0XQpKlaeU=";
    };
    date = "2025-09-12";
  };
}
