# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  osirus-clap-aarch64 = {
    pname = "osirus-clap-aarch64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_aarch64-Osirus-CLAP.zip";
      sha256 = "sha256-hz1PUQJCRXQ7STf1poydTy8oM078P99YdOUlWLcJjl4=";
    };
  };
  osirus-clap-x86_64 = {
    pname = "osirus-clap-x86_64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_x86_64-Osirus-CLAP.zip";
      sha256 = "sha256-3ZPQ3agzLI7jxzAUIcczCOE5u3WTJCxIJ4xsp/H4guY=";
    };
  };
  osirus-lv2-aarch64 = {
    pname = "osirus-lv2-aarch64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_aarch64-Osirus-LV2.zip";
      sha256 = "sha256-Ii9GlTi7mGzmtki6XbdFT37rtywAtfChvn8nVlA97Zg=";
    };
  };
  osirus-lv2-x86_64 = {
    pname = "osirus-lv2-x86_64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_x86_64-Osirus-LV2.zip";
      sha256 = "sha256-jLnRBgiuhiSEfeXULIzcbCoz/EnFni9XdaDDPlPn410=";
    };
  };
  osirus-test-console-aarch64 = {
    pname = "osirus-test-console-aarch64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_aarch64-OsirusTestConsole.zip";
      sha256 = "sha256-Js1Gz+MM2/lw/fzBj59h/SGohBVCGAK2iqN7ai7rjMY=";
    };
  };
  osirus-test-console-x86_64 = {
    pname = "osirus-test-console-x86_64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_x86_64-OsirusTestConsole.zip";
      sha256 = "sha256-hV7IHPE50TqMPZ9S1VI3CqsNLVqHdtpmbwRI9o8OHEo=";
    };
  };
  osirus-vst2-aarch64 = {
    pname = "osirus-vst2-aarch64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_aarch64-Osirus-VST2.zip";
      sha256 = "sha256-/JBOcWrUH2ENTk4ckvnj8+3i10OsPgylSMT2Ph2F5gs=";
    };
  };
  osirus-vst2-x86_64 = {
    pname = "osirus-vst2-x86_64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_x86_64-Osirus-VST2.zip";
      sha256 = "sha256-nf0Vr7iaK8SF5Kjzlw+RlSEQeedvznnKuO2Wpb6L5hg=";
    };
  };
  osirus-vst3-aarch64 = {
    pname = "osirus-vst3-aarch64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_aarch64-Osirus-VST3.zip";
      sha256 = "sha256-X8Rdm8rz93cYGBYt6HwmLUKxlXKqAdIIKDZXbFOVvnc=";
    };
  };
  osirus-vst3-x86_64 = {
    pname = "osirus-vst3-x86_64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_x86_64-Osirus-VST3.zip";
      sha256 = "sha256-lRrbF1DXXJvcIGVEGRrKm2HHNmnRbyIgKu72JKmfW2s=";
    };
  };
  osirusfx-clap-aarch64 = {
    pname = "osirusfx-clap-aarch64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_aarch64-OsirusFX-CLAP.zip";
      sha256 = "sha256-3yu6mg6UL7rAJmPBPEvqV+5RstbUlzEA1ylRSTbjpAc=";
    };
  };
  osirusfx-clap-x86_64 = {
    pname = "osirusfx-clap-x86_64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_x86_64-OsirusFX-CLAP.zip";
      sha256 = "sha256-ch6gBO77rgTTBiIv60BSN/QO5C30Sh9V/r/fxVcZb/g=";
    };
  };
  osirusfx-lv2-aarch64 = {
    pname = "osirusfx-lv2-aarch64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_aarch64-OsirusFX-LV2.zip";
      sha256 = "sha256-qZHC6zuA/v2/XRlVrha3RrvfSYLBYLHVRdhmZg/lcxA=";
    };
  };
  osirusfx-lv2-x86_64 = {
    pname = "osirusfx-lv2-x86_64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_x86_64-OsirusFX-LV2.zip";
      sha256 = "sha256-WjXD01lE1UTl/a9nn57yw6W/RhLrLtFx5O0Uh/gYRgU=";
    };
  };
  osirusfx-vst2-aarch64 = {
    pname = "osirusfx-vst2-aarch64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_aarch64-OsirusFX-VST2.zip";
      sha256 = "sha256-NYHYxSx/P5FI5sz+wfYA7MuFx+nZerzv0boCGRV1UWo=";
    };
  };
  osirusfx-vst2-x86_64 = {
    pname = "osirusfx-vst2-x86_64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_x86_64-OsirusFX-VST2.zip";
      sha256 = "sha256-tgBB0K9X6SrGkQzAyaKwYbucIfIVxi7tuxya05HgZzs=";
    };
  };
  osirusfx-vst3-aarch64 = {
    pname = "osirusfx-vst3-aarch64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_aarch64-OsirusFX-VST3.zip";
      sha256 = "sha256-TwVgNa5RMUmtEVCBIM77Pi2huas05uqgI8VQ2CmtzwY=";
    };
  };
  osirusfx-vst3-x86_64 = {
    pname = "osirusfx-vst3-x86_64";
    version = "1.3.14";
    src = fetchurl {
      url = "https://futurenoize.com/dsp56300/builds/osirus/DSP56300Emu-1.3.14-Linux_x86_64-OsirusFX-VST3.zip";
      sha256 = "sha256-IycZI6O91vSPjMEISg0e187T4BFxKzhUR0O/fPahcZA=";
    };
  };
}
