# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  airwin2rack = {
    pname = "airwin2rack";
    version = "389462ac57ec37057c1c86338f8b858c62760b34";
    src = fetchgit {
      url = "https://github.com/baconpaul/airwin2rack";
      rev = "389462ac57ec37057c1c86338f8b858c62760b34";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-Nokt2ubAvVx0XHalmGxL1hK1ugKXRKKPoLbt7eGTbU4=";
    };
    date = "2025-01-19";
  };
  clap-juce-extensions = {
    pname = "clap-juce-extensions";
    version = "4f33b4930b6af806018c009f0f24b3a50808af99";
    src = fetchgit {
      url = "https://github.com/free-audio/clap-juce-extensions";
      rev = "4f33b4930b6af806018c009f0f24b3a50808af99";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-M+T7ll3Ap6VIP5ub+kfEKwT2RW2IxxY4wUPRQKFIotk=";
    };
    date = "2024-12-29";
  };
  juce-7_0_12 = {
    pname = "juce-7_0_12";
    version = "7.0.12";
    src = fetchFromGitHub {
      owner = "juce-framework";
      repo = "JUCE";
      rev = "7.0.12";
      fetchSubmodules = false;
      sha256 = "sha256-/awe6D824ZjF17xjkt0wY7dcDuS/s8KKAv1UKHxF0FM=";
    };
  };
}
