# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  gate-12 = {
    pname = "gate-12";
    version = "v1.1.6";
    src = fetchFromGitHub {
      owner = "tiagolr";
      repo = "gate12";
      rev = "v1.1.6";
      fetchSubmodules = true;
      sha256 = "sha256-Jw9OsQFg82XanzaurVpfPWksMu/kx9B7Gk2ACiXFduA=";
    };
  };
}
