# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  gate-12 = {
    pname = "gate-12";
    version = "v1.2.2";
    src = fetchFromGitHub {
      owner = "tiagolr";
      repo = "gate12";
      rev = "v1.2.2";
      fetchSubmodules = true;
      sha256 = "sha256-+HK4BaYn3qq7SOwLmpZm30dXWDpnQJXc/XFo13LboTQ=";
    };
  };
}
