# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  gate-12 = {
    pname = "gate-12";
    version = "v1.3.1";
    src = fetchFromGitHub {
      owner = "tiagolr";
      repo = "gate12";
      rev = "v1.3.1";
      fetchSubmodules = true;
      sha256 = "sha256-WjVVYUWcPI2nAdeK1ztq+01FVQ5gII1WEW1kYSH2RHk=";
    };
  };
}
