# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  monique = {
    pname = "monique";
    version = "df7d3395bce862847d40237350d0161a463dcc0d";
    src = fetchFromGitHub {
      owner = "surge-synthesizer";
      repo = "monique-monosynth";
      rev = "df7d3395bce862847d40237350d0161a463dcc0d";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = true;
      sparseCheckout = [ ];
      sha256 = "sha256-G2mdy9l9lo6m7DHlFd9EYHd2hQbXPQIH/mt9ibVLPOk=";
    };
    date = "2024-07-30";
  };
}
