# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  dwm-flexipatch = {
    pname = "dwm-flexipatch";
    version = "050e728c6bded3e01390a7c2e1102545839180a9";
    src = fetchFromGitHub {
      owner = "bakkeby";
      repo = "dwm-flexipatch";
      rev = "050e728c6bded3e01390a7c2e1102545839180a9";
      fetchSubmodules = false;
      sha256 = "sha256-nSnUR/fBnfaQ0Tfi9kXL4oR5y6RD1opT115o17c4P5w=";
    };
    date = "2026-04-28";
  };
}
