# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  dwm-flexipatch = {
    pname = "dwm-flexipatch";
    version = "15dbec1aaa8133135a323b7c5ea830ea0a683d54";
    src = fetchFromGitHub {
      owner = "bakkeby";
      repo = "dwm-flexipatch";
      rev = "15dbec1aaa8133135a323b7c5ea830ea0a683d54";
      fetchSubmodules = false;
      sha256 = "sha256-FMNqjC36ApomkKszCpek0/4t4kPPjOoId+vTrl50UyA=";
    };
    date = "2026-01-30";
  };
}
