# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  dwm-flexipatch = {
    pname = "dwm-flexipatch";
    version = "2c3725aa18bc118cd1d6691f387ff932f897c4e6";
    src = fetchFromGitHub {
      owner = "bakkeby";
      repo = "dwm-flexipatch";
      rev = "2c3725aa18bc118cd1d6691f387ff932f897c4e6";
      fetchSubmodules = false;
      sha256 = "sha256-XshsFLN9K8UKL4ZmOHGCfYB8XhHMsoh9mkZRZxlHpSY=";
    };
    date = "2026-05-19";
  };
}
