# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  nu-plugin-regex = {
    pname = "nu-plugin-regex";
    version = "v0.24.0";
    src = fetchFromGitHub {
      owner = "fdncred";
      repo = "nu_plugin_regex";
      rev = "v0.24.0";
      fetchSubmodules = false;
      sha256 = "sha256-AQzpqv8gBwM3k4Qs6lLha6MBZb7kp2tu5lQImSQNnIg=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-AQzpqv8gBwM3k4Qs6lLha6MBZb7kp2tu5lQImSQNnIg=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
}
