[dwm-flexipatch]
src.git = "https://github.com/bakkeby/dwm-flexipatch"
fetch.github = "bakkeby/dwm-flexipatch"

[st-flexipatch]
src.git = "https://github.com/bakkeby/st-flexipatch"
fetch.github = "bakkeby/st-flexipatch"

[dmenu-flexipatch]
src.git = "https://github.com/bakkeby/dmenu-flexipatch"
fetch.github = "bakkeby/dmenu-flexipatch"

[slock-flexipatch]
src.git = "https://github.com/bakkeby/slock-flexipatch"
fetch.github = "bakkeby/slock-flexipatch"
