# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  pi-acp = {
    pname = "pi-acp";
    version = "v0.0.30";
    src = fetchFromGitHub {
      owner = "svkozak";
      repo = "pi-acp";
      rev = "v0.0.30";
      fetchSubmodules = false;
      sha256 = "sha256-shIGSJYBcbsDg9UdZIHJoI6E4M4gH25FRaXOQuJVFZo=";
    };
    extract = {
      "package-lock.json" = ./. + "/sha256-shIGSJYBcbsDg9UdZIHJoI6E4M4gH25FRaXOQuJVFZo=/package-lock.json";
      "package.json" = ./. + "/sha256-shIGSJYBcbsDg9UdZIHJoI6E4M4gH25FRaXOQuJVFZo=/package.json";
    };
  };
}
