# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  pi-acp = {
    pname = "pi-acp";
    version = "v0.0.28";
    src = fetchFromGitHub {
      owner = "svkozak";
      repo = "pi-acp";
      rev = "v0.0.28";
      fetchSubmodules = false;
      sha256 = "sha256-Hv5AeNJTnfXAowQFSWAWzKk/03G/H2JVTS7KLafpRGg=";
    };
    extract = {
      "package-lock.json" = ./. + "/sha256-Hv5AeNJTnfXAowQFSWAWzKk_03G_H2JVTS7KLafpRGg=/package-lock.json";
      "package.json" = ./. + "/sha256-Hv5AeNJTnfXAowQFSWAWzKk_03G_H2JVTS7KLafpRGg=/package.json";
    };
  };
}
