# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  kiwmi = {
    pname = "kiwmi";
    version = "392b6c38fd189e304aa97f9c6fc88a5c7113a140";
    src = fetchFromGitHub {
      owner = "buffet";
      repo = "kiwmi";
      rev = "392b6c38fd189e304aa97f9c6fc88a5c7113a140";
      fetchSubmodules = false;
      sha256 = "sha256-xTvCq8vq1bztfVxd9Kn9KT2Hl5C6toWl/CS8VojkZw0=";
    };
    date = "2022-07-30";
  };
}
