[snyk-ls-bin-x86_64-linux]
src.cmd = 'curl https://static.snyk.io/snyk-ls/16/metadata.json | jq .version | sed -e s/\"//g'
fetch.url = "https://static.snyk.io/snyk-ls/16/snyk-ls_$ver_linux_amd64"

[snyk-ls-bin-i686-linux]
src.cmd = 'curl https://static.snyk.io/snyk-ls/16/metadata.json | jq .version | sed -e s/\"//g'
fetch.url = "https://static.snyk.io/snyk-ls/16/snyk-ls_$ver_linux_386"

[snyk-ls-bin-aarch64-linux]
src.cmd = 'curl https://static.snyk.io/snyk-ls/16/metadata.json | jq .version | sed -e s/\"//g'
fetch.url = "https://static.snyk.io/snyk-ls/16/snyk-ls_$ver_linux_arm64"

[snyk-ls-bin-x86_64-darwin]
src.cmd = 'curl https://static.snyk.io/snyk-ls/16/metadata.json | jq .version | sed -e s/\"//g'
fetch.url = "https://static.snyk.io/snyk-ls/16/snyk-ls_$ver_darwin_amd64"

[snyk-ls-bin-aarch64-darwin]
src.cmd = 'curl https://static.snyk.io/snyk-ls/16/metadata.json | jq .version | sed -e s/\"//g'
fetch.url = "https://static.snyk.io/snyk-ls/16/snyk-ls_$ver_darwin_arm64"
