# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  compressor = {
    pname = "compressor";
    version = "4f0c9ac8ef91e1bf102cf4d28e7cc62992bf3aa7";
    src = fetchgit {
      url = "https://github.com/ZL-Audio/ZLCompressor";
      rev = "4f0c9ac8ef91e1bf102cf4d28e7cc62992bf3aa7";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-lW5lTgETNwI6Et+aMeBcqASswwtnRhdIuz//yETOSEg=";
    };
    date = "2025-11-16";
  };
  equalizer = {
    pname = "equalizer";
    version = "1.0.2";
    src = fetchFromGitHub {
      owner = "ZL-Audio";
      repo = "ZLEqualizer";
      rev = "1.0.2";
      fetchSubmodules = true;
      sha256 = "sha256-F0abEbX0Xpvx3/enk6XOW6v4m6HXa+g5HYDYAGRa+Lc=";
    };
  };
  inflator = {
    pname = "inflator";
    version = "0.3.0";
    src = fetchFromGitHub {
      owner = "ZL-Audio";
      repo = "ZLInflator";
      rev = "0.3.0";
      fetchSubmodules = true;
      sha256 = "sha256-HR2zZYEZvAIZCM05VAcDbCbyp16uma3v8+U66XgW/RY=";
    };
  };
  lmakeup = {
    pname = "lmakeup";
    version = "v0.2.7";
    src = fetchFromGitHub {
      owner = "ZL-Audio";
      repo = "ZLLMakeup";
      rev = "v0.2.7";
      fetchSubmodules = true;
      sha256 = "sha256-H6R5ZN005coDrf19nHpogAe+jY2/VA3B4w23gzYq+EM=";
    };
  };
  lmatch = {
    pname = "lmatch";
    version = "v0.2.4";
    src = fetchFromGitHub {
      owner = "ZL-Audio";
      repo = "ZLLMatch";
      rev = "v0.2.4";
      fetchSubmodules = true;
      sha256 = "sha256-HswX1bWg1Rej+em21N1H3G1TVmeXY+tq0ib9OKNlTN4=";
    };
  };
  splitter = {
    pname = "splitter";
    version = "0.2.0";
    src = fetchFromGitHub {
      owner = "ZL-Audio";
      repo = "ZLSplitter";
      rev = "0.2.0";
      fetchSubmodules = true;
      sha256 = "sha256-8a/t1yJG5CUr4udnKIy80exQejDy0HzOi7uMjelPldg=";
    };
  };
  warm = {
    pname = "warm";
    version = "0.2.1";
    src = fetchFromGitHub {
      owner = "ZL-Audio";
      repo = "ZLWarm";
      rev = "0.2.1";
      fetchSubmodules = true;
      sha256 = "sha256-+koLt4HZKbDvveMD9HrN+/4fq9H+Y4irCjcZZGBL59s=";
    };
  };
}
