# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  st-flexipatch = {
    pname = "st-flexipatch";
    version = "490d2440da7bf264d851e80c1719e3ebe0d84b57";
    src = fetchFromGitHub {
      owner = "bakkeby";
      repo = "st-flexipatch";
      rev = "490d2440da7bf264d851e80c1719e3ebe0d84b57";
      fetchSubmodules = false;
      sha256 = "sha256-585VQ3MRWKtnIVFWzy3/rSHT/pveDj45P1HFJHiutgA=";
    };
    date = "2026-01-15";
  };
}
