# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  st-flexipatch = {
    pname = "st-flexipatch";
    version = "1d3f20096c9b5cea0452343a97c644f5987da6d9";
    src = fetchFromGitHub {
      owner = "bakkeby";
      repo = "st-flexipatch";
      rev = "1d3f20096c9b5cea0452343a97c644f5987da6d9";
      fetchSubmodules = false;
      sha256 = "sha256-VnfC64Uvy0OExM3ENbQfCNKaERq/fD2Wh3UXqlyjhjc=";
    };
    date = "2026-03-27";
  };
}
