# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  st-flexipatch = {
    pname = "st-flexipatch";
    version = "b8056cbf24eea5121d362ea3757b10d0dfe21652";
    src = fetchFromGitHub {
      owner = "bakkeby";
      repo = "st-flexipatch";
      rev = "b8056cbf24eea5121d362ea3757b10d0dfe21652";
      fetchSubmodules = false;
      sha256 = "sha256-Q8ZnkrWiBdKPrUgZi37LNXpacoabPWtEs0ubsd8vfWA=";
    };
    date = "2026-01-29";
  };
}
