# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  audible-planets-lv2 = {
    pname = "audible-planets-lv2";
    version = "1.2.3";
    src = fetchurl {
      url = "https://github.com/gregrecco67/AudiblePlanets/releases/download/v1.2.3/Audible.Planets-1.2.3-Linux.lv2.zip";
      sha256 = "sha256-H3hVyC7qeipLDF/+iL5YMdKd0MFxS0nzJatYExFlJgk=";
    };
  };
  audible-planets-vst3 = {
    pname = "audible-planets-vst3";
    version = "1.2.3";
    src = fetchurl {
      url = "https://github.com/gregrecco67/AudiblePlanets/releases/download/v1.2.3/Audible.Planets-1.2.3-Linux.vst3.zip";
      sha256 = "sha256-2NzyG7czvKRPyT64gA5FhqxP4xQCuquJqgK1b7ow8Tc=";
    };
  };
}
