# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  luakit = {
    pname = "luakit";
    version = "d90c248ce6aac334a6fa07f934d361e69f311d9c";
    src = fetchFromGitHub {
      owner = "luakit";
      repo = "luakit";
      rev = "d90c248ce6aac334a6fa07f934d361e69f311d9c";
      fetchSubmodules = false;
      sha256 = "sha256-kOrlZmYCeWw7nY+l2L6SBoEeM/HYNOa0Le7TRZHidx0=";
    };
    date = "2025-01-27";
  };
}
