# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  luakit = {
    pname = "luakit";
    version = "a916b20c93b1c13812df65c4386a2fc8a3762b23";
    src = fetchFromGitHub {
      owner = "luakit";
      repo = "luakit";
      rev = "a916b20c93b1c13812df65c4386a2fc8a3762b23";
      fetchSubmodules = false;
      sha256 = "sha256-Bjhkk43ix75f/KiLNHLb+UYdaGXhdfqd7fiaOKEbGjA=";
    };
    date = "2025-01-26";
  };
}
