# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  luakit = {
    pname = "luakit";
    version = "ed6d587bbebad260282d19492b74e0de56a09901";
    src = fetchFromGitHub {
      owner = "luakit";
      repo = "luakit";
      rev = "ed6d587bbebad260282d19492b74e0de56a09901";
      fetchSubmodules = false;
      sha256 = "sha256-vzdx9XjiElcH1nGIERuHsxUScZW8P8W1LVOl+4lRgWg=";
    };
    date = "2025-01-25";
  };
}
