# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  onagre = {
    pname = "onagre";
    version = "c68c716b086afa3cc8ca02a9a03334493ecb5cb1";
    src = fetchTarball {
      url = "https://github.com/onagre-launcher/onagre/archive/c68c716b086afa3cc8ca02a9a03334493ecb5cb1.tar.gz";
      sha256 = "sha256-X2ZffwkCZdH0fbSFTpVITIpFFqY8djCteo11sp/FU3E=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-X2ZffwkCZdH0fbSFTpVITIpFFqY8djCteo11sp_FU3E=/Cargo.lock";
      outputHashes = {

      };
    };
    date = "2025-04-24";
  };
}
