# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  element = {
    pname = "element";
    version = "1203c6630181324d7ff4588fd7f2e0977135a69f";
    src = fetchgit {
      url = "https://gitlab.com/kushview/element.git";
      rev = "1203c6630181324d7ff4588fd7f2e0977135a69f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sparseCheckout = [];
      sha256 = "sha256-q98fRwpwlKvnVUMJKrYRiLX+WbX5z3ikz+LRclIviXQ=";
    };
    date = "2025-01-21";
  };
  juce-element = {
    pname = "juce-element";
    version = "34b98e72bf4406d6a11c9b81a8a404c1abd5a02e";
    src = fetchgit {
      url = "https://gitlab.com/kushview/juce";
      rev = "34b98e72bf4406d6a11c9b81a8a404c1abd5a02e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-vdtU5CvKjCtqqbGyMrkdavHkNCb91IERnzySoJXXbwE=";
    };
    date = "2024-06-13";
  };
  lvtk = {
    pname = "lvtk";
    version = "0797fdcabef84f57b064c7b4507743afebc66589";
    src = fetchgit {
      url = "https://github.com/lvtk/lvtk.git";
      rev = "0797fdcabef84f57b064c7b4507743afebc66589";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-Z79zy2/OZTO6RTrAqgTHTzB00LtFTFiJ272RvQRpbH8=";
    };
    date = "2024-11-05";
  };
}
