# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  element = {
    pname = "element";
    version = "c2d7e0d61def46cb50f0fa8eabddceeb0f9fdb3d";
    src = fetchFromGitHub {
      owner = "kushview";
      repo = "element";
      rev = "c2d7e0d61def46cb50f0fa8eabddceeb0f9fdb3d";
      fetchSubmodules = true;
      sha256 = "sha256-MS8/rHQ/FAyb2IFeM4u9Ch4MJ0LCYhDysWddCDXLRgo=";
    };
    date = "2026-06-19";
  };
}
