# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  element = {
    pname = "element";
    version = "2fa280c56b6afda4cdaed069f966b32ee661949a";
    src = fetchgit {
      url = "https://github.com/kushview/element";
      rev = "2fa280c56b6afda4cdaed069f966b32ee661949a";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-FXvkzBiJqMgls/xUN9CR9gQD0H5MhqNeammsv4kFCXY=";
    };
    date = "2026-02-13";
  };
}
