# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  nu-lint = {
    pname = "nu-lint";
    version = "5a29c2624b65c8bf6915251725cf67feb6083c9c";
    src = fetchgit {
      url = "https://codeberg.org/wvhulle/nu-lint.git";
      rev = "5a29c2624b65c8bf6915251725cf67feb6083c9c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-vVRZLe1LgvqVpeAp5aJ7HOfdjQ1d0qe+oA+Knnembx8=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./nu-lint-5a29c2624b65c8bf6915251725cf67feb6083c9c/Cargo.lock;
      outputHashes = {

      };
    };
    date = "2026-01-14";
  };
}
