# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  nu-lint = {
    pname = "nu-lint";
    version = "5ff53f8b1cb4a2720c54360fb67e017e1a13045b";
    src = fetchgit {
      url = "https://codeberg.org/wvhulle/nu-lint.git";
      rev = "5ff53f8b1cb4a2720c54360fb67e017e1a13045b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-fbP0NUWGayJmbmvHlBj+X7zbD2USuDFsC5I8l+oHw/U=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./nu-lint-5ff53f8b1cb4a2720c54360fb67e017e1a13045b/Cargo.lock;
      outputHashes = {

      };
    };
    date = "2026-01-16";
  };
}
