# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  nu-lint = {
    pname = "nu-lint";
    version = "4fd0218f6d703439aed12b1b55232ae16eb055a5";
    src = fetchgit {
      url = "https://codeberg.org/wvhulle/nu-lint.git";
      rev = "4fd0218f6d703439aed12b1b55232ae16eb055a5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-nMf/476I3lSpk97nDyXIPuPboBKWy75U49AbW62mhsw=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./nu-lint-4fd0218f6d703439aed12b1b55232ae16eb055a5/Cargo.lock;
      outputHashes = {

      };
    };
    date = "2026-01-07";
  };
}
