# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  nu-plugin-mime = {
    pname = "nu-plugin-mime";
    version = "cf85352b95b02587252e1450803767010eec0e30";
    src = fetchgit {
      url = "https://github.com/kik4444/nu_plugin_mime.git";
      rev = "cf85352b95b02587252e1450803767010eec0e30";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-f9dkMRH7PHmcnYhIypgsdUhsIa+gPDPAAC5GJOuP2xo=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-f9dkMRH7PHmcnYhIypgsdUhsIa+gPDPAAC5GJOuP2xo=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2026-03-08";
  };
}
