# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  nu-plugin-mime = {
    pname = "nu-plugin-mime";
    version = "7dd4ae2bf757f1732d5e0a4d9e615bc0586b09d8";
    src = fetchgit {
      url = "https://github.com/kik4444/nu_plugin_mime.git";
      rev = "7dd4ae2bf757f1732d5e0a4d9e615bc0586b09d8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ZlUCM105Bfe7QsWMyDSOoVT/WXBJTKdFjvEdPc2KD0w=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-ZlUCM105Bfe7QsWMyDSOoVT_WXBJTKdFjvEdPc2KD0w=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2026-05-09";
  };
}
