# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  nu-plugin-mime = {
    pname = "nu-plugin-mime";
    version = "8e5872a5c94573d0ede3127b5ab8628b8d7f4a4c";
    src = fetchFromGitHub {
      owner = "kik4444";
      repo = "nu_plugin_mime";
      rev = "8e5872a5c94573d0ede3127b5ab8628b8d7f4a4c";
      fetchSubmodules = false;
      sha256 = "sha256-XK8rco+OQWsgwD/a0zht6PKgj8ZhiZAhop5+eFefowc=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-XK8rco+OQWsgwD_a0zht6PKgj8ZhiZAhop5+eFefowc=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2026-08-15";
  };
}
