# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  some-sass-language-server = {
    pname = "some-sass-language-server";
    version = "some-sass-language-server@2.3.7";
    src = fetchgit {
      url = "https://github.com/wkillerud/some-sass.git";
      rev = "some-sass-language-server@2.3.7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ieJYW1sB2Ir3A/xTxOg8AtOwJpnDEwTE+yegmIFIiLM=";
    };
    extract = {
      "package-lock.json" =
        ./. + "/sha256-ieJYW1sB2Ir3A_xTxOg8AtOwJpnDEwTE+yegmIFIiLM=/package-lock.json";
      "package.json" = ./. + "/sha256-ieJYW1sB2Ir3A_xTxOg8AtOwJpnDEwTE+yegmIFIiLM=/package.json";
    };
  };
}
