# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {};
in
{
  some-sass-language-server = nodeEnv.buildNodePackage {
    name = "some-sass-language-server";
    packageName = "some-sass-language-server";
    version = "2.3.7";
    src = fetchurl {
      url = "https://registry.npmjs.org/some-sass-language-server/-/some-sass-language-server-2.3.7.tgz";
      sha512 = "Nm/GIM8+h++7BleIY0/it9zoxs0KYwW6K+7Unjaze26F5wLd2D7yXdGJts0G5EHKqtLbXGBKQu3yh1QHVG7UVA==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "LSP server for SCSS and Sass indented. Full support for @use and @forward, including aliases, prefixes and hiding. Rich documentation through SassDoc. Workspace-wide code navigation and refactoring.";
      homepage = "https://github.com/wkillerud/some-sass/blob/main/packages/language-server#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
