name: Lint
on:
  push:
    branches:
      - staging
  workflow_run:
    workflows:
      - Update sources
    types:
      - completed

jobs:
  dupes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: staging
          fetch-depth: 0

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@latest
        with:
          extra_nix_config: |
            accept-flake-config = true

      - name: Check for nixpkgs dupes
        run: |
          nix eval .#_DUPES --json | jq 'map("- `\(. | join("."))`") | .[]' -r >> $GITHUB_STEP_SUMMARY

  hammer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: staging
          fetch-depth: 0

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@latest
        with:
          extra_nix_config: |
            accept-flake-config = true

      - name: Run nixpkgs-hammering
        shell: nix develop .#lint -c nu {0}
        run: |
          nix eval .#_BUILDABLE --apply builtins.attrNames --json
          | from json
          | par-each {|pkg|
            (nixpkgs-hammer
              -e=attribute-ordering
              -e=no-build-output
              -e=explicit-phases
              --json
              ($pkg | str replace -a "/" "."))
            | from json
          }
          | reduce {|it, acc| $acc | merge $it}
          | items {|n, v|
            if ($v | is-not-empty) {
              $"# `($n)`\n" ++ (
                $v | each {|prob|
                  $"- ($prob.name) - ($prob.msg)"}
                  | flatten
                  | str join "\n"
                )
            }
          }
          | where { is-not-empty}
          | str join "\n"
          | save -a $env.GITHUB_STEP_SUMMARY
