# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  uhhyou = {
    pname = "uhhyou";
    version = "UhhyouPlugins0.64.0";
    src = fetchFromGitHub {
      owner = "ryukau";
      repo = "VSTPlugins";
      rev = "UhhyouPlugins0.64.0";
      fetchSubmodules = true;
      sha256 = "sha256-7RImmD7IYRyKzfR72tj8GSRDZgb3I/zw3sDWMC+UyfA=";
    };
  };
}
