# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  uhhyou = {
    pname = "uhhyou";
    version = "UhhyouPlugins0.67.0";
    src = fetchFromGitHub {
      owner = "ryukau";
      repo = "VSTPlugins";
      rev = "UhhyouPlugins0.67.0";
      fetchSubmodules = true;
      sha256 = "sha256-8YGfcnWkOQwwq6m3510GPpZu6UbDmVi3K/dOGLrAnhM=";
    };
  };
}
