# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  clap-juce-extensions = {
    pname = "clap-juce-extensions";
    version = "e8de9e8571626633b8541a54c2406fccc4272767";
    src = fetchFromGitHub {
      owner = "free-audio";
      repo = "clap-juce-extensions";
      rev = "e8de9e8571626633b8541a54c2406fccc4272767";
      fetchSubmodules = true;
      sha256 = "sha256-dgKBa+7KXa6hI/zAdg762an6URGtNyUqMtXglRpMtGY=";
    };
    date = "2026-04-24";
  };
  hamburger = {
    pname = "hamburger";
    version = "v0.5";
    src = fetchFromGitHub {
      owner = "Davit-G";
      repo = "Hamburger";
      rev = "v0.5";
      fetchSubmodules = false;
      sha256 = "sha256-U/xy+uYTtDnBEHuZmVQkjTxy191oyLRs+ofnE/sHMPA=";
    };
  };
  juce = {
    pname = "juce";
    version = "51d11a2be6d5c97ccf12b4e5e827006e19f0555a";
    src = fetchFromGitHub {
      owner = "juce-framework";
      repo = "JUCE";
      rev = "51d11a2be6d5c97ccf12b4e5e827006e19f0555a";
      fetchSubmodules = false;
      sha256 = "sha256-iAueT+yHwUUHOzqfK5zXEZQ0GgOKJ9q9TyRrVfWdewc=";
    };
  };
}
