# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  clap-juce-extensions = {
    pname = "clap-juce-extensions";
    version = "02f91b7988298f7f1f05c706da16e1d9da852a87";
    src = fetchgit {
      url = "https://github.com/free-audio/clap-juce-extensions.git";
      rev = "02f91b7988298f7f1f05c706da16e1d9da852a87";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-cPi+prl+jLq/KvjZ5M2MxxZVLSKCiJB9SQHK8psW2OU=";
    };
    date = "2026-01-26";
  };
  hamburger = {
    pname = "hamburger";
    version = "v0.5";
    src = fetchFromGitHub {
      owner = "Davit-G";
      repo = "Hamburger";
      rev = "v0.5";
      fetchSubmodules = false;
      sha256 = "sha256-U/xy+uYTtDnBEHuZmVQkjTxy191oyLRs+ofnE/sHMPA=";
    };
  };
  juce = {
    pname = "juce";
    version = "51d11a2be6d5c97ccf12b4e5e827006e19f0555a";
    src = fetchgit {
      url = "https://github.com/juce-framework/JUCE.git";
      rev = "51d11a2be6d5c97ccf12b4e5e827006e19f0555a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-iAueT+yHwUUHOzqfK5zXEZQ0GgOKJ9q9TyRrVfWdewc=";
    };
  };
}
