# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  clap-juce-extensions = {
    pname = "clap-juce-extensions";
    version = "e44a9e53ea8d22e2fbe2f366921d494534bb2b52";
    src = fetchgit {
      url = "https://github.com/free-audio/clap-juce-extensions.git";
      rev = "e44a9e53ea8d22e2fbe2f366921d494534bb2b52";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-X77BO4yHf1Nu3bopt0fDw28o3NI1vYFnDbRQT/5EH90=";
    };
    date = "2026-01-16";
  };
  hamburger = {
    pname = "hamburger";
    version = "v0.5";
    src = fetchFromGitHub {
      owner = "Davit-G";
      repo = "Hamburger";
      rev = "v0.5";
      fetchSubmodules = false;
      sha256 = "sha256-U/xy+uYTtDnBEHuZmVQkjTxy191oyLRs+ofnE/sHMPA=";
    };
  };
  juce = {
    pname = "juce";
    version = "51d11a2be6d5c97ccf12b4e5e827006e19f0555a";
    src = fetchgit {
      url = "https://github.com/juce-framework/JUCE.git";
      rev = "51d11a2be6d5c97ccf12b4e5e827006e19f0555a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-iAueT+yHwUUHOzqfK5zXEZQ0GgOKJ9q9TyRrVfWdewc=";
    };
  };
}
