# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  sgdboop-bin = {
    pname = "sgdboop-bin";
    version = "v1.3.2";
    src = fetchurl {
      url = "https://github.com/SteamGridDB/SGDBoop/releases/download/v1.3.2/sgdboop-linux64.tar.gz";
      sha256 = "sha256-p1xPmAwKbYnWc8DE3RW6V/yecTVGh9/wbFS+H5Gtl2U=";
    };
  };
}
