# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  sgdboop-bin = {
    pname = "sgdboop-bin";
    version = "v1.3.1";
    src = fetchurl {
      url = "https://github.com/SteamGridDB/SGDBoop/releases/download/v1.3.1/sgdboop-linux64.tar.gz";
      sha256 = "sha256-NRP5b/Idpiq54bAFNsNcsfNXECgqLp2i/lys0fqsLUo=";
    };
  };
}
